#include "repl_examples.h"

#include <stddef.h>

/* Each example is an array of source lines terminated by NULL.
 * Lines are processed sequentially:
 *   "for(...) {"  -> CMD_FOR_BEGIN + CMD_FOR_END, enters block
 *   "funcN {"     -> CMD_FUNC_DEF + CMD_FUNC_END, enters block
 *   "if(...) {"   -> CMD_IF_BEGIN + CMD_IF_END, enters block
 *   "}"           -> closes current block
 *   "x = expr;"   -> CMD_VAR_ASSIGN
 *   "funcN()"     -> CMD_CALL
 *   anything else -> parse_command() as a regular GL command
 */

/* Example 0: Lit cube (default) */
static const char *const g_example_cube[] = {
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glShadeModel(GL_SMOOTH);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "//glEnable(GL_LINE_SMOOTH);",
    "glColor3f(1, 1, 1);",
    "glBegin(GL_QUAD_STRIP);",
    "glNormal3f(0, 1, 0);",
    "glVertex3f(1, 1, 1);",
    "glNormal3f(0, 1, 0);",
    "glVertex3f(-1, 1, 1);",
    "glNormal3f(0, 0, 1);",
    "glVertex3f(1, -1, 1);",
    "glNormal3f(0, 0, 1);",
    "glVertex3f(-1, -1, 1);",
    "glNormal3f(-0, -1, -0);",
    "glVertex3f(1, -1, -1);",
    "glNormal3f(-0, -1, -0);",
    "glVertex3f(-1, -1, -1);",
    "glNormal3f(0, 0, -1);",
    "glVertex3f(1, 1, -1);",
    "glNormal3f(0, 0, -1);",
    "glVertex3f(-1, 1, -1);",
    "glNormal3f(0, 1, -0);",
    "glVertex3f(1, 1, 1);",
    "glNormal3f(0, 1, -0);",
    "glVertex3f(-1, 1, 1);",
    "glEnd();",
    NULL
};

/* Example 1: Animated ring — for-loop + t variable */
static const char *const g_example_ring[] = {
    "glEnable(GL_DEPTH_TEST);",
    "glBegin(GL_LINE_LOOP);",
    "for(i, 0, 48) {",
        "glColor3f(sin(i*TAU/48)*0.5+0.5, cos(i*TAU/48)*0.5+0.5, 0.5);",
        "glVertex3f(cos(i*TAU/48+t)*2, sin(i*TAU/48+t)*2, sin(i*TAU/12+t)*0.5);",
    "}",
    "glEnd();",
    "glBegin(GL_TRIANGLE_FAN);",
    "glColor3f(0.2, 0.5, 1);",
    "glVertex3f(0, 0, 0);",
    "for(i, 0, 25) {",
        "glColor3f(sin(i*TAU/24+t)*0.5+0.5, 0.3, cos(i*TAU/24+t)*0.5+0.5);",
        "glVertex3f(cos(i*TAU/24)*1.5, sin(i*TAU/24)*1.5, 0);",
    "}",
    "glEnd();",
    NULL
};

/* Example 2: Function demo — define reusable triangle, call with transforms */
static const char *const g_example_func[] = {
    "glEnable(GL_DEPTH_TEST);",
    "func0 {",
        "glBegin(GL_TRIANGLES);",
        "glNormal3f(0, 0, 1);",
        "glVertex3f(0, 0.8, 0);",
        "glVertex3f(-0.7, -0.4, 0);",
        "glVertex3f(0.7, -0.4, 0);",
        "glEnd();",
    "}",
    "glColor3f(1, 0.3, 0.3);",
    "func0();",
    "glTranslatef(2, 0, 0);",
    "glColor3f(0.3, 1, 0.3);",
    "func0();",
    "glTranslatef(-4, 0, 0);",
    "glColor3f(0.3, 0.3, 1);",
    "func0();",
    NULL
};

/* Example 3: Parametric polygon helper — function args driving local for-loops */
static const char *const g_example_func_loop[] = {
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "func0(radius, sides, phase) {",
        "glBegin(GL_TRIANGLE_FAN);",
        "glNormal3f(0, 0, 1);",
        "glColor3f(1, 1, 1);",
        "glVertex3f(0, 0, 0);",
        "for(i, 0, sides + 1) {",
            "glColor3f(sin(i*TAU/sides + phase)*0.5+0.5, cos(i*TAU/sides + phase)*0.5+0.5, 0.8);",
            "glVertex3f(cos(i*TAU/sides + phase)*radius, sin(i*TAU/sides + phase)*radius, 0);",
        "}",
        "glEnd();",
    "}",
    "glPushMatrix();",
    "glTranslatef(-2.4, 0, 0);",
    "func0(0.9, 3, t*0.4);",
    "glPopMatrix();",
    "glPushMatrix();",
    "func0(0.9, 6, -t*0.25);",
    "glPopMatrix();",
    "glPushMatrix();",
    "glTranslatef(2.4, 0, 0);",
    "func0(0.9, 10, t*0.15);",
    "glPopMatrix();",
    NULL
};

/* Example 4: Branching helper — function args driving local if-blocks */
static const char *const g_example_func_if[] = {
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "func0(scale, phase) {",
        "if(scale > 1) {",
            "glColor3f(1, 0.35, 0.2);",
            "glBegin(GL_QUADS);",
            "glNormal3f(0, 0, 1);",
            "glVertex3f(-0.7*scale, -0.7*scale, 0);",
            "glVertex3f(0.7*scale, -0.7*scale, 0);",
            "glVertex3f(0.7*scale, 0.7*scale, 0);",
            "glVertex3f(-0.7*scale, 0.7*scale, 0);",
            "glEnd();",
        "}",
        "if(scale <= 1) {",
            "glColor3f(0.2, 0.75, 1);",
            "glBegin(GL_TRIANGLES);",
            "glNormal3f(0, 0, 1);",
            "glVertex3f(cos(phase)*0.9*scale, sin(phase)*0.9*scale, 0);",
            "glVertex3f(cos(phase+TAU/3)*0.9*scale, sin(phase+TAU/3)*0.9*scale, 0);",
            "glVertex3f(cos(phase+2*TAU/3)*0.9*scale, sin(phase+2*TAU/3)*0.9*scale, 0);",
            "glEnd();",
        "}",
    "}",
    "glPushMatrix();",
    "glTranslatef(-2.2, 0, 0);",
    "func0(0.9, t);",
    "glPopMatrix();",
    "glPushMatrix();",
    "func0(1.4, t*0.5);",
    "glPopMatrix();",
    "glPushMatrix();",
    "glTranslatef(2.2, 0, 0);",
    "func0(0.65, -t*0.8);",
    "glPopMatrix();",
    NULL
};

/* Example 5: Recursive helper — transformed child calls with depth countdown */
static const char *const g_example_func_recurse[] = {
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "// Recursive triangle tree: child calls shrink and rotate from the parent",
    "func0(depth, size, spin) {",
        "glColor3f(0.25 + depth*0.14, 0.45 + 0.2*sin(spin), 1 - depth*0.12);",
        "glBegin(GL_LINE_LOOP);",
        "glNormal3f(0, 0, 1);",
        "glVertex3f(0, size, 0);",
        "glVertex3f(-0.866*size, -0.5*size, 0);",
        "glVertex3f(0.866*size, -0.5*size, 0);",
        "glEnd();",
        "if(depth <= 0) {",
            "glColor3f(1, 0.8, 0.2);",
            "glBegin(GL_TRIANGLES);",
            "glNormal3f(0, 0, 1);",
            "glVertex3f(0, size*0.55, 0);",
            "glVertex3f(-0.48*size, -0.25*size, 0);",
            "glVertex3f(0.48*size, -0.25*size, 0);",
            "glEnd();",
        "}",
        "if(depth > 0) {",
            "glPushMatrix();",
            "glTranslatef(0, size*1.02, 0);",
            "glRotatef(18 + spin*14, 0, 0, 1);",
            "func0(depth - 1, size*0.62, spin + 0.15);",
            "glPopMatrix();",
            "glPushMatrix();",
            "glTranslatef(-size*0.9, -size*0.38, 0);",
            "glRotatef(-30 - spin*12, 0, 0, 1);",
            "func0(depth - 1, size*0.58, spin + 0.12);",
            "glPopMatrix();",
            "glPushMatrix();",
            "glTranslatef(size*0.9, -size*0.38, 0);",
            "glRotatef(30 + spin*12, 0, 0, 1);",
            "func0(depth - 1, size*0.58, spin + 0.12);",
            "glPopMatrix();",
        "}",
    "}",
    "glRotatef(sin(t*0.35)*12, 0, 0, 1);",
    "func0(4, 1.05, sin(t*0.4));",
    NULL
};

/* Example 6: Conditional colors — if-blocks + t variable */
static const char *const g_example_cond[] = {
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glBegin(GL_QUADS);",
    "if(sin(t) > 0) {",
        "glColor3f(1, 0.2, 0.2);",
    "}",
    "if(sin(t) <= 0) {",
        "glColor3f(0.2, 0.2, 1);",
    "}",
    "glNormal3f(0, 0, 1);",
    "glVertex3f(-1, -1, 0);",
    "glVertex3f(1, -1, 0);",
    "glVertex3f(1, 1, 0);",
    "glVertex3f(-1, 1, 0);",
    "if(cos(t) > 0) {",
        "glColor3f(0.2, 1, 0.2);",
    "}",
    "if(cos(t) <= 0) {",
        "glColor3f(1, 1, 0.2);",
    "}",
    "glNormal3f(0, 0, -1);",
    "glVertex3f(-1, -1, -1);",
    "glVertex3f(-1, 1, -1);",
    "glVertex3f(1, 1, -1);",
    "glVertex3f(1, -1, -1);",
    "glEnd();",
    NULL
};

/* Example 7: Parametric torus — nested for-loops */
static const char *const g_example_torus[] = {
    "glEnable(GL_DEPTH_TEST);",
    "//glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "glShadeModel(GL_SMOOTH);",
    "for(i, 0, 24) {",
        "glBegin(GL_QUAD_STRIP);",
        "for(j, 0, 25) {",
            "glColor3f(sin(i*TAU/24)*0.4+0.6, cos(j*TAU/24)*0.4+0.6, 0.5);",
            "glVertex3f((2+cos(j*TAU/24))*cos(i*TAU/24), (2+cos(j*TAU/24))*sin(i*TAU/24), sin(j*TAU/24));",
            "glVertex3f((2+cos(j*TAU/24))*cos((i+1)*TAU/24), (2+cos(j*TAU/24))*sin((i+1)*TAU/24), sin(j*TAU/24));",
        "}",
        "glEnd();",
    "}",
    NULL
};

/* Example 8: GLU tessellator — concave arrow polygon with per-vertex color */
static const char *const g_example_tess[] = {
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "glShadeModel(GL_SMOOTH);",
    "glFrontFace(GL_CW);",
    "// Arrow shape - concave, tessellated with per-vertex color",
    "gluBegin(GLU_POLYGON);",
    "gluBegin(GLU_CONTOUR);",
    "gluNormal(0, 0, 1);",
    "gluColor(0.2, 0.4, 1, 1);",
    "gluVertex(-1.2, -0.45, 0);",
    "gluColor(0.2, 0.4, 1, 1);",
    "gluVertex(-1.2, 0.45, 0);",
    "gluColor(0.55, 0.3, 1, 1);",
    "gluVertex(0, 0.45, 0);",
    "gluColor(1, 0.45, 0.05, 1);",
    "gluVertex(0, 1.1, 0);",
    "gluColor(1, 0.9, 0.1, 1);",
    "gluVertex(1.3, 0, 0);",
    "gluColor(1, 0.45, 0.05, 1);",
    "gluVertex(0, -1.1, 0);",
    "gluColor(0.55, 0.3, 1, 1);",
    "gluVertex(0, -0.45, 0);",
    "gluEnd();",
    "gluEnd();",
    NULL
};

/* Example 9: GLU tessellator — concave arrow polygon cutout */
static const char *const g_example_tess_cutout[] = {
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "glShadeModel(GL_SMOOTH);",
    "glFrontFace(GL_CW);",
    "z = -0.55;",
    "glRotatef(10*t, 0, 0, 1);",
    "glScalef(0.5, 0.5, 0.5);",
    "// Arrow shape - concave, tessellated with per-vertex color",
    "gluBegin(GLU_POLYGON);",
    "  gluBegin(GLU_CONTOUR);",
    "    glBegin(GL_QUAD_STRIP);",
    "    gluNormal(0, 0, 1);",
    "  // Side 0",
    "    gluColor(0.2, 0.4, 1, 1);",
    "      glColor3f(0.2, 0.4, 1);",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(-1.2, -0.45, 0);",
    "      glVertex3f(-1.2, -0.45, z);",
    "    gluVertex(-1.2, -0.45, 0);",
    "  // Side 1",
    "    gluColor(0.2, 0.4, 1, 1);",
    "      glColor3f(0.2, 0.4, 1);",
    "      glNormal3f(0, 1, 0);",
    "      glVertex3f(-1.2, 0.45, 0);",
    "      glVertex3f(-1.2, 0.45, z);",
    "    gluVertex(-1.2, 0.45, 0);",
    "  // Side 2",
    "    gluColor(0.55, 0.3, 1, 1);",
    "      glColor3f(0.55, 0.3, 1);",
    "      glNormal3f(-1, 1, 0);",
    "      glVertex3f(0, 0.45, 0);",
    "      glVertex3f(0, 0.45, z);",
    "    gluVertex(0, 0.45, 0);",
    "  // Side 3",
    "    gluColor(1, 0.45, 0.05, 1);",
    "      glColor3f(1, 0.45, 0.05);",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(0, 1.1, 0);",
    "      glVertex3f(0, 1.1, z);",
    "    gluVertex(0, 1.1, 0);",
    "  // Side 4",
    "    gluColor(1, 0.9, 0.1, 1);",
    "      glColor3f(1, 0.9, 0.1);",
    "      glNormal3f(1, 0, 0);",
    "      glVertex3f(1.3, 0, 0);",
    "      glVertex3f(1.3, 0, z);",
    "    gluVertex(1.3, 0, 0);",
    "  // Side 5",
    "    gluColor(1, 0.45, 0.05, 1);",
    "      glColor3f(1, 0.45, 0.05);",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(0, -1.1, 0);",
    "      glVertex3f(0, -1.1, z);",
    "    gluVertex(0, -1.1, 0);",
    "  // Side 6",
    "    gluColor(0.55, 0.3, 1, 1);",
    "      glColor3f(0.55, 0.3, 1);",
    "      glNormal3f(-1, -1, 0);",
    "      glVertex3f(0, -0.45, 0);",
    "      glVertex3f(0, -0.45, z);",
    "    gluVertex(0, -0.45, 0);",
    "  // Quade side 7",
    "      glColor3f(0.2, 0.4, 1);",
    "      glNormal3f(0, -1, 0);",
    "      glVertex3f(-1.2, -0.45, 0);",
    "      glVertex3f(-1.2, -0.45, z);",
    "    glEnd();",
    "  gluEnd();",
    "  gluBegin(GLU_CONTOUR);",
    "    glBegin(GL_QUAD_STRIP);",
    "      glColor3f(0.5, 0.5, 0.5);",
    "    gluNormal(0, 0, 1);",
    "  // Side 0",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(-0.6, -0.225, 0);",
    "      glVertex3f(-0.6, -0.225, z);",
    "    gluVertex(-0.6, -0.225, 0);",
    "  // Side 1",
    "      glNormal3f(0, 1, 0);",
    "      glVertex3f(-0.6, 0.225, 0);",
    "      glVertex3f(-1.2/2, 0.45/2, z);",
    "    gluVertex(-0.6, 0.225, 0);",
    "  // Side 2",
    "      glNormal3f(-1, 1, 0);",
    "      glVertex3f(0.2, 0.225, 0);",
    "      glVertex3f(0.2, 0.45/2, z);",
    "    gluVertex(0.2, 0.225, 0);",
    "  // Side 3",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(0.2, 0.55, 0);",
    "      glVertex3f(0.2, 1.1/2, z);",
    "    gluVertex(0.2, 0.55, 0);",
    "  // Side 4",
    "      glNormal3f(1, 0, 0);",
    "      glVertex3f(0.85, 0, 0);",
    "      glVertex3f(1.7/2, 0, z);",
    "    gluVertex(0.85, 0, 0);",
    "  // Side 5",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(0.2, -0.55, 0);",
    "      glVertex3f(0.2, -1.1/2, z);",
    "    gluVertex(0.2, -0.55, 0);",
    "  // Side 6",
    "      glNormal3f(-1, -1, 0);",
    "      glVertex3f(0.2, -0.225, 0);",
    "      glVertex3f(0.2, -0.45/2, z);",
    "    gluVertex(0.2, -0.225, 0);",
    "  // Quad side 7",
    "      glNormal3f(0, -1, 0);",
    "      glVertex3f(-0.6, -0.225, 0);",
    "      glVertex3f(-1.2/2, -0.45/2, z);",
    "    glEnd();",
    "  gluEnd();",
    "gluEnd();",
    NULL
};

/* Example 10: 2D assignment sketch — runtime assignment without goto.
 * No predefined goto examples are shipped because goto support is partial:
 * top-level only, not replay-safe, and not suitable for variable-driven
 * geometry loops. Keep coverage in tests/docs instead of F12 examples. */
static const char *const g_example_assign_2d[] = {
    "// 2D assignment sketch: tests runtime variable assignment without goto",
    "glDisable(GL_LIGHTING);",
    "glDisable(GL_DEPTH_TEST);",
    "x = -1.7;",
    "y = 0.12*sin(t*0.8);",
    "glBegin(GL_LINE_STRIP);",
    "for(i, 0, 48) {",
    "  glColor3f(0.30 + i*0.010, 0.55 + 0.28*sin(i*0.20 + t), 0.95 - i*0.008);",
    "  glVertex3f(x, y, 0);",
    "  x = x + 0.07;",
    "  y = sin(x*2.5 + t)*0.52 + cos(i*0.25 + t*0.6)*0.16;",
    "}",
    "glEnd();",
    NULL
};

/* Example 11: Stateless particle field using deterministic rand(seed, iter) */
static const char *const g_example_particles_stateless[] = {
    "// Stateless particle field: deterministic rand(seed, iter)",
    "glDisable(GL_LIGHTING);",
    "glPointSize(3);",
    "n = 260;",
    "glBegin(GL_POINTS);",
    "for(i, 0, n) {",
    "  x = rand(i, 0)*2 - 1;",
    "  y = rand(i, 1)*2 - 1;",
    "  z = rand(i, 2)*2 - 1;",
    "  k = rand(i, 3)*TAU;",
    "  j = 0.35 + rand(i, 4)*1.25;",
    "  x = x + cos(k)*j*t*0.25;",
    "  y = y + sin(k)*j*t*0.25;",
    "  z = z + (rand(i, 5)*2 - 1)*t*0.35;",
    "  glColor3f(0.3 + 0.7*rand(i, 6), 0.35 + 0.65*rand(i, 7), 0.5 + 0.5*rand(i, 8));",
    "  glVertex3f(x, y, z);",
    "}",
    "glEnd();",
    "glEnable(GL_LIGHTING);",
    NULL
};

/* Example 12: Additive glow particles — glPointSize + distance attenuation + blend */
static const char *const g_example_glow_particles[] = {
    "// Glow sprites: additive blend + distance-attenuated point size",
    "glDisable(GL_LIGHTING);",
    "glDisable(GL_DEPTH_TEST);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE);",
    "glEnable(GL_POINT_SMOOTH);",
    "glPointSize(24);",
    "glPointParameterfv(GL_POINT_DISTANCE_ATTENUATION, 0.2, 0, 0.15);",
    "n = 160;",
    "glBegin(GL_POINTS);",
    "for(i, 0, n) {",
    "  k = rand(i, 0)*TAU;",
    "  j = 0.4 + rand(i, 1)*1.8;",
    "  x = cos(k + t*0.4)*j;",
    "  y = sin(k*1.3 + t*0.6)*0.9;",
    "  z = sin(k + t*0.4)*j;",
    "  glColor4f(0.4 + 0.6*rand(i, 2), 0.3 + 0.5*rand(i, 3), 0.8 + 0.2*rand(i, 4), 0.55);",
    "  glVertex3f(x, y, z);",
    "}",
    "glEnd();",
    "glDisable(GL_POINT_SMOOTH);",
    "glDisable(GL_BLEND);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    NULL
};

/* Example 13: Stress test — exercises parser, code UI, nested structures,
 * multiple functions, recursion, conditionals, variables, tessellation,
 * GLU primitives, matrix stack, animation, and long line count. */
static const char *const g_example_stress[] = {
    "// ===== Stress-test scene: parser + code UI torture =====",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT2);",
    "glEnable(GL_LIGHT3);",
    "glShadeModel(GL_SMOOTH);",
    "glColorMaterial(GL_FRONT_AND_BACK, GL_AMBIENT_AND_DIFFUSE);",
    "glLightModeli(GL_LIGHT_MODEL_TWO_SIDE, 1);",
    "",
    "// --- func0: parametric surface patch (nested for + math) ---",
    "func0(rows, cols, amp, phase) {",
        "for(i, 0, rows) {",
            "glBegin(GL_TRIANGLE_STRIP);",
            "for(j, 0, cols + 1) {",
                "x = -1.5 + 3.0*j/cols;",
                "z = -1.5 + 3.0*i/rows;",
                "y = amp*sin(x*2.5 + phase)*cos(z*2.5 + phase*0.7);",
                "n = 1.0/sqrt(1 + amp*amp*6.25*(cos(x*2.5 + phase)*cos(x*2.5 + phase)*cos(z*2.5 + phase*0.7)*cos(z*2.5 + phase*0.7) + sin(x*2.5 + phase)*sin(x*2.5 + phase)*sin(z*2.5 + phase*0.7)*sin(z*2.5 + phase*0.7)));",
                "glNormal3f(-amp*2.5*cos(x*2.5 + phase)*cos(z*2.5 + phase*0.7)*n, n, amp*2.5*sin(x*2.5 + phase)*sin(z*2.5 + phase*0.7)*n);",
                "glColor3f(0.35 + 0.35*sin(x + phase), 0.5 + 0.3*cos(z + phase*0.5), 0.65 + 0.25*sin(x*z + phase));",
                "glVertex3f(x, y, z);",
                "z = -1.5 + 3.0*(i + 1)/rows;",
                "y = amp*sin(x*2.5 + phase)*cos(z*2.5 + phase*0.7);",
                "n = 1.0/sqrt(1 + amp*amp*6.25*(cos(x*2.5 + phase)*cos(x*2.5 + phase)*cos(z*2.5 + phase*0.7)*cos(z*2.5 + phase*0.7) + sin(x*2.5 + phase)*sin(x*2.5 + phase)*sin(z*2.5 + phase*0.7)*sin(z*2.5 + phase*0.7)));",
                "glNormal3f(-amp*2.5*cos(x*2.5 + phase)*cos(z*2.5 + phase*0.7)*n, n, amp*2.5*sin(x*2.5 + phase)*sin(z*2.5 + phase*0.7)*n);",
                "glColor3f(0.35 + 0.35*sin(x + phase), 0.5 + 0.3*cos(z + phase*0.5), 0.65 + 0.25*sin(x*z + phase));",
                "glVertex3f(x, y, z);",
            "}",
            "glEnd();",
        "}",
    "}",
    "",
    "// --- func1: recursive branching tree (recursion + if + matrix stack) ---",
    "func1(depth, len, twist) {",
        "glColor3f(0.35 + depth*0.12, 0.25 + 0.15*sin(twist), 0.15);",
        "glBegin(GL_LINES);",
        "glNormal3f(0, 0, 1);",
        "glVertex3f(0, 0, 0);",
        "glVertex3f(0, len, 0);",
        "glEnd();",
        "if(depth > 0) {",
            "// Right branch",
            "glPushMatrix();",
            "glTranslatef(0, len, 0);",
            "glRotatef(25 + twist*8, 0, 0, 1);",
            "glScalef(0.72, 0.72, 0.72);",
            "func1(depth - 1, len, twist + 0.3);",
            "glPopMatrix();",
            "// Left branch",
            "glPushMatrix();",
            "glTranslatef(0, len, 0);",
            "glRotatef(-30 - twist*6, 0, 0, 1);",
            "glScalef(0.68, 0.68, 0.68);",
            "func1(depth - 1, len, twist + 0.25);",
            "glPopMatrix();",
            "// Forward branch (z-axis splay)",
            "glPushMatrix();",
            "glTranslatef(0, len*0.9, 0);",
            "glRotatef(15 + twist*4, 1, 0, 0);",
            "glScalef(0.6, 0.6, 0.6);",
            "func1(depth - 1, len*0.85, twist + 0.2);",
            "glPopMatrix();",
        "}",
        "if(depth <= 0) {",
            "// Leaf: small filled triangle",
            "glColor3f(0.2, 0.7 + 0.3*sin(twist*5), 0.15);",
            "glBegin(GL_TRIANGLES);",
            "glNormal3f(0, 0, 1);",
            "glVertex3f(0, len, 0);",
            "glVertex3f(-len*0.3, len*1.3, 0);",
            "glVertex3f(len*0.3, len*1.3, 0);",
            "glEnd();",
        "}",
    "}",
    "",
    "// --- func2: tessellated star floor with circular cutout ---",
    "func2(radius, hole) {",
        "glFrontFace(GL_CW);",
        "gluBegin(GLU_POLYGON);",
        "// Outer contour: 10-pointed star",
        "gluBegin(GLU_CONTOUR);",
        "gluNormal(0, 1, 0);",
        "for(i, 0, 20) {",
            "k = radius;",
            "if(i % 2 > 0) {",
                "k = radius*0.5;",
            "}",
            "gluColor(0.25 + 0.15*sin(i*0.6), 0.3 + 0.15*cos(i*0.8), 0.55 + 0.1*sin(i));",
            "gluVertex(k*cos(i*TAU/20), 0, k*sin(i*TAU/20));",
        "}",
        "gluEnd();",
        "// Inner contour: circular cutout (tessellator infers hole from overlap)",
        "gluBegin(GLU_CONTOUR);",
        "for(i, 0, 24) {",
            "gluColor(0.1, 0.1, 0.15);",
            "gluVertex(hole*cos(-i*TAU/24), 0, hole*sin(-i*TAU/24));",
        "}",
        "gluEnd();",
        "gluEnd();",
        "glFrontFace(GL_CCW);",
    "}",
    "",
    "// --- func3: orbiting GLU quadric satellites ---",
    "func3(count, orbit_r, sat_size, spin) {",
        "for(i, 0, count) {",
            "glPushMatrix();",
            "glRotatef(i*360/count + spin, 0, 1, 0);",
            "glTranslatef(orbit_r, 0, 0);",
            "// Sphere body",
            "glColor3f(0.8 + 0.2*sin(i + spin*0.02), 0.5, 0.3 + 0.2*cos(i));",
            "gluSphere(sat_size, 12, 8);",
            "// Antenna cylinder",
            "glColor3f(0.5, 0.5, 0.6);",
            "glTranslatef(0, sat_size, 0);",
            "glRotatef(-90, 1, 0, 0);",
            "gluCylinder(sat_size*0.15, sat_size*0.05, sat_size*1.5, 8, 1);",
            "// Dish at top",
            "glTranslatef(0, 0, sat_size*1.5);",
            "glColor3f(0.9, 0.85, 0.5);",
            "gluDisk(0, sat_size*0.35, 12, 1);",
            "glPopMatrix();",
        "}",
    "}",
    "",
    "// ===== Main scene composition =====",
    "",
    "// Animated variables",
    "n = 8;",
    "x = 0.4*sin(t*0.6);",
    "y = 0.15*cos(t*0.8);",
    "",
    "// Ground: tessellated star floor",
    "glPushMatrix();",
    "glTranslatef(0, -1.8, 0);",
    "func2(3.0, 0.8);",
    "glPopMatrix();",
    "",
    "// Wavy parametric surface",
    "glPushMatrix();",
    "glTranslatef(0, x, 0);",
    "glRotatef(t*12, 0, 1, 0);",
    "func0(n, n, 0.35 + 0.15*sin(t), t*0.5);",
    "glPopMatrix();",
    "",
    "// Fractal tree (recursive)",
    "glPushMatrix();",
    "glTranslatef(-2.5, -1.8, 0);",
    "glRotatef(-5*sin(t*0.3), 0, 0, 1);",
    "func1(3, 0.7, t*0.2);",
    "glPopMatrix();",
    "",
    "// Second tree, mirrored",
    "glPushMatrix();",
    "glTranslatef(2.5, -1.8, 0);",
    "glScalef(-1, 1, 1);",
    "glRotatef(-5*cos(t*0.25), 0, 0, 1);",
    "func1(3, 0.65, t*0.15 + 1);",
    "glPopMatrix();",
    "",
    "// Orbiting satellites",
    "glPushMatrix();",
    "glTranslatef(0, y + 1.0, 0);",
    "func3(5, 2.8, 0.18, t*35);",
    "glPopMatrix();",
    "",
    "// Central decoration: torus + sphere",
    "glPushMatrix();",
    "glTranslatef(0, 0.5 + 0.3*sin(t*1.2), 0);",
    "glRotatef(t*45, 0, 1, 0);",
    "glRotatef(t*20, 1, 0, 0);",
    "glColor3f(0.85, 0.6, 0.25);",
    "glutSolidTorus(0.12, 0.55, 16, 24);",
    "glColor3f(0.95, 0.90, 0.70);",
    "gluSphere(0.25, 16, 12);",
    "glPopMatrix();",
    "",
    "// Wireframe accent ring",
    "glDisable(GL_LIGHTING);",
    "glBegin(GL_LINE_LOOP);",
    "for(i, 0, 64) {",
        "glColor3f(0.3 + 0.3*sin(i*TAU/64 + t), 0.5 + 0.2*cos(i*TAU/32 + t*0.7), 0.8);",
        "glVertex3f(3.5*cos(i*TAU/64), -1.75, 3.5*sin(i*TAU/64));",
    "}",
    "glEnd();",
    "glEnable(GL_LIGHTING);",
    "",
    "// Long expression stress: animated vertex spiral",
    "glDisable(GL_LIGHTING);",
    "glBegin(GL_LINE_STRIP);",
    "for(i, 0, 120) {",
        "x = (1.5 + 0.4*sin(i*TAU/30 + t*2))*cos(i*TAU/60 + t*0.3);",
        "y = -1.75 + i*0.025 + 0.08*sin(i*0.5 + t*3);",
        "z = (1.5 + 0.4*sin(i*TAU/30 + t*2))*sin(i*TAU/60 + t*0.3);",
        "glColor3f(0.1 + 0.5*sin(i*0.08 + t), 0.9 - 0.4*cos(i*0.06), 0.5 + 0.3*sin(i*0.12 + t*0.5));",
        "glVertex3f(x, y, z);",
    "}",
    "glEnd();",
    "glEnable(GL_LIGHTING);",
    NULL
};

static const char *const *const g_examples[] = {
    g_example_cube,
    g_example_ring,
    g_example_func,
    g_example_func_loop,
    g_example_func_if,
    g_example_func_recurse,
    g_example_cond,
    g_example_torus,
    g_example_tess,
    g_example_tess_cutout,
    g_example_assign_2d,
    g_example_particles_stateless,
    g_example_glow_particles,
    g_example_stress,
};

static const char *const g_example_names[] = {
    "Lit cube",
    "Animated ring (for + t)",
    "Function demo (func0)",
    "Function polygons (args + for)",
    "Function branching (args + if)",
    "Recursive triangle tree (func + recursion)",
    "Conditional colors (if + t)",
    "Parametric torus (nested for)",
    "GLU tessellator (concave arrow)",
    "GLU tessellator (concave arrow cutout)",
    "2D assignment sketch (vars only)",
    "Stateless particles (rand seed+iter)",
    "Glow sprites (blend + point attenuation)",
    "Stress test (all features)",
};

int repl_examples_count(void) {
    return (int)(sizeof(g_examples) / sizeof(g_examples[0]));
}

const char *repl_examples_name(int idx) {
    if (idx < 0 || idx >= repl_examples_count())
        return NULL;
    return g_example_names[idx];
}

const char *const *repl_examples_lines(int idx) {
    if (idx < 0 || idx >= repl_examples_count())
        return NULL;
    return g_examples[idx];
}
