/* Generated by gl-repl. */
/* */
/* This is a standalone GLUT/OpenGL C file. You can edit it by hand, */
/* or load it back into gl-repl to keep working on the scene. */
/* */
/* Linux: */
/*   cc -std=c89 -Wall -Wextra -o scene scene.c -lglut -lGL -lGLU -lm */
/* */
/* macOS: */
/*   cc -std=c89 -Wall -Wextra -o scene scene.c -framework OpenGL -framework GLUT -lm */
/* */
/* SPDX-License-Identifier: MIT */
/* See the gl-repl repository LICENSE file for the full text. */

/* @workspace: REPL state (auto-saved) */

/* @func 0 = computeVerticalMotion */
/* @func 1 = computeLifespan */
/* @func 2 = computeDriftX */
/* @func 3 = computeDriftZ */
/* @func 4 = drawWhale */
/* @cfg msaa = 1 */
/* @cfg line_smooth = 0 */
/* @cfg accum_effect = 1 */
/* @cfg accum_passes = 1 */
/* @cfg wireframe = 0 */
/* @cfg point_attenuation = 1 */
/* @cfg auto_time = 1 */
/* @cfg replay = 0 */
/* @cfg replay_mode = 1 */
/* @cfg replay_expand = 1 */
/* @cfg grid = GRID_THEME_OCEAN */
/* @cfg grid_extent = GRID_EXTENT_MID */
/* @cfg grid_brightness = GRID_BRIGHTNESS_NORMAL */
/* @cfg grid_major = GRID_MAJOR_1 */
/* @cfg axes = AXES_THEME_OFF */
/* @cfg xform_guides = 2 */
/* @cfg light_indicators = 0 */
/* @cfg light_theme = LIGHT_THEME_DEFAULT */
/* @cfg backdrop = RENDER3D_BACKDROP_OFF */
/* @cfg auto_normals = 0 */
/* @cfg view_mode = RENDER3D_VIEW_3D */
/* @cfg camera_rotate = 0 */
/* @cfg vertex_labels = OVERLAY_VERTEX_LABEL_INDEX */
/* @cfg normal_vectors = 0 */
/* @cfg vertex_outlines = 0 */
/* @cfg vertex_points = 0 */
/* @cfg poly_highlight = 1 */
/* @cfg variable_panel = 1 */
/* @cfg compute_profile = 0 */
/* @cfg memory_profile = 0 */
/* @cfg code_panel = 1 */
/* @cfg wrap_at_commas = 1 */
/* @cfg syntax_highlight = 1 */
/* @cfg paren_match = 1 */
/* @cfg paren_scope = 1 */
/* @cfg audio = 1 */

#define j0 _j0
#define j1 _j1
#define jn _jn
#define y0 _y0
#define y1 _y1
#define yn _yn
#define gamma _gamma
#define lgamma _lgamma
#define tgamma _tgamma
#include <stddef.h>
#if defined(__APPLE__)
#include <OpenGL/gl.h>
#include <OpenGL/glu.h>
#include <GLUT/glut.h>
#else
#define GL_GLEXT_PROTOTYPES
#include <GL/gl.h>
#include <GL/glext.h>
#include <GL/glu.h>
#include <GL/freeglut.h>
#endif
#include <math.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdio.h>
#undef j0
#undef j1
#undef jn
#undef y0
#undef y1
#undef yn
#undef gamma
#undef lgamma
#undef tgamma

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

static float g_angle = -114.3999f;
static int   g_rotating = 0;


/* C89 replacement for C99 compound GLfloat literals. */
static GLfloat repl_glfloat1_buf[1];
static GLfloat repl_glfloat3_buf[3];
static GLfloat repl_glfloat4_buf[4];

static GLfloat *repl_glfloat1(GLfloat a) {
  repl_glfloat1_buf[0] = a;
  return repl_glfloat1_buf;
}

static GLfloat *repl_glfloat3(GLfloat a, GLfloat b, GLfloat c) {
  repl_glfloat3_buf[0] = a;
  repl_glfloat3_buf[1] = b;
  repl_glfloat3_buf[2] = c;
  return repl_glfloat3_buf;
}

static GLfloat *repl_glfloat4(GLfloat a, GLfloat b, GLfloat c, GLfloat d) {
  repl_glfloat4_buf[0] = a;
  repl_glfloat4_buf[1] = b;
  repl_glfloat4_buf[2] = c;
  repl_glfloat4_buf[3] = d;
  return repl_glfloat4_buf;
}

/* Scene state variables.
 * Initializers are the live snapshot at export time, so the
 * program starts in the same state the REPL preview ended in.
 * Variables other than t keep mutations from frame to frame. */
static float t = 0.0f;
static float launchVelX = 1.5703125;
static float launchVelY = 3.59375;
static float launchVelZ = -0.1640625;
static float currentVelY = -1.4774656;
static float particleLife = 2.2350917;
static float particleAge = 1.4489188;
static float dragDecay = 0.9;
static float gravityY = -3.5;
static float dragRate = 10;
static float particleX = 2.1165864;
static float particleY = 2.2431624;
static float particleZ = -0.12188217;
static float floorY = -10;
static float spawnDelay = 1.4824219;
static float emitDuration = 5.99568;
static float fluke_ang = -28.575768;
static float fin_ang = -1.522293;
static float speed = 0.5;
static float detail = 30;
static float blowHoleX = 0.95;
static float blowHoleY = 0.71;
static float blowHoleZ = 0;
static float waterDroplets = 250;

static float repl_randf(float seed, float iter) {
  float h = sinf(seed * 12.9898f + iter * 78.233f) * 43758.5453f;
  float frac = h - floorf(h);
  if (frac < 0.0f) frac += 1.0f;
  return frac;
}

static float repl_rand2f(float seed, float iter) {
  return repl_randf(seed, iter) * 2.0f - 1.0f;
}



static void computeVerticalMotion(float ageSeconds, float launchY) {
    /* Velocity is linear in age: currentVelY = gravityY*ageSeconds + launchVelY. */
    /* Position is its integral: */
    /*   (gravityY/2)*ageSeconds^2 + launchVelY*ageSeconds + launchY */
    currentVelY = launchVelY + gravityY*ageSeconds;
    particleY = launchY + gravityY/2 * ageSeconds * ageSeconds + launchVelY * ageSeconds;
}



static void computeLifespan(float launchY) {
    /* Solve particleY(age) = floorY for age: how long the particle takes to fall */
    /* from launchY to the floor. particleY is the projectile */
    /*   (gravityY/2)*age^2 + launchVelY*age + (launchY - floorY) = 0 */
    /* a quadratic with a = gravityY/2, b = launchVelY, c = launchY - floorY, so */
    /*   age = (-b - sqrt(b^2 - 4ac)) / 2a */
    /* Substituting a = gravityY/2: 4ac = 2*gravityY*c and 2a = gravityY. */
    particleLife = (-launchVelY - sqrtf(launchVelY*launchVelY - 2 * gravityY*(launchY - floorY))) / gravityY;
}



static void computeDriftX(float ageSeconds, float launchX) {
    /* Integral over [0, age] of the decaying horizontal velocity */
    /*   velX(s) = launchVelX * dragDecay^(dragRate*s) */
    particleX = launchX + (launchVelX * powf(dragDecay, ageSeconds*dragRate) - launchVelX) / (dragRate*logf(dragDecay));
}



static void computeDriftZ(float ageSeconds, float launchZ) {
    /* Integral over [0, age] of the decaying horizontal velocity */
    /*   velZ(s) = launchVelZ * dragDecay^(dragRate*s) */
    particleZ = launchZ + (launchVelZ * powf(dragDecay, ageSeconds*dragRate) - launchVelZ) / (dragRate*logf(dragDecay));
}



static void drawWhale(float blowHoleX, float blowHoleY, float blowHoleZ) {
    fluke_ang = sinf(speed*t*(2*M_PI))* 30;
    fin_ang = cosf(speed*t*(2*M_PI))* 5;
    detail = fmaxf(12, floorf(detail));

    /* Shiny wet whale */
    glMaterialfv(GL_FRONT_AND_BACK, GL_SPECULAR, repl_glfloat4(0.2, 0.2, 0.2, 1));
    glMaterialf(GL_FRONT_AND_BACK, GL_SHININESS, 100);

    /* Main body: elongated ellipsiod, dark blue-grey on top */
    glColor3f(0.24, 0.3, 0.4);

    glPushMatrix();
      glScalef(2, 0.85, 1.05);
      glutSolidSphere(1, detail, detail);
    glPopMatrix();

    /* Belly: lighter, sits just under the body so it shows the underside */
    glColor3f(0.72, 0.76, 0.78);
    glPushMatrix();
      glTranslatef(0.05, -0.42, 0);
      glScalef(1.65, 0.45, 0.75);
      glutSolidSphere(1, detail, detail);
    glPopMatrix();

    glColor3f(0.24, 0.3, 0.4);
    glPushMatrix(); /* begin tail */
      glTranslatef(-1.85, -0.2, 0);
      glRotatef(fluke_ang/2, 0, 0, 1);

      /* Tail peduncle (narrow part before the flukes) */
      glPushMatrix();
        glScalef(0.75, 0.3, 0.4);
        glutSolidSphere(1, detail, detail);
      glPopMatrix();

      /* Tail flukes -- two flat libes, animated with fluke_angle */
      glPushMatrix();
        glTranslatef(-0.65, 0, 0);
        glRotatef(fluke_ang, 0, 0, 1);
        glPushMatrix();
          glTranslatef(-0.1, 0, 0.55);
          glRotatef(15, 0, 1, 0);
          glScalef(0.35, 0.06, 0.65);
          glutSolidSphere(1, detail, detail); /* right fluke */
        glPopMatrix();
        glPushMatrix();
          glTranslatef(-0.1, 0, -0.55);
          glRotatef(-15, 0, 1, 0);
          glScalef(0.35, 0.06, 0.65);
          glutSolidSphere(1, detail, detail); /* left fluke */
        glPopMatrix();
      glPopMatrix(); /* end flukes */
    glPopMatrix(); /* end tail */

    /* Pectoral fins */
    glPushMatrix();
      glRotatef(fin_ang, 0, 0, 1);
      glRotatef(fin_ang/4, 0, 1, 0);

      glPushMatrix();
        glTranslatef(0.45, -0.25, 1);
        glRotatef(25, 0, 1, 0);
        glScalef(0.4, 0.08, 0.45);
        glutSolidSphere(1, 14, 10); /* right pectoral fin */
      glPopMatrix();

      glPushMatrix();
        glTranslatef(0.45, -0.25, -1);
        glScalef(0.4, 0.08, 0.45);
        glutSolidSphere(1, 14, 10); /* left pectoral fin */
      glPopMatrix();
    glPopMatrix(); /* end fins */

    /* Eyes */
    glDisable(GL_LIGHTING);
    glColor3f(0.04, 0.04, 0.04);
    glPushMatrix();
      glTranslatef(1.45, 0.18, 0.63);
      glutSolidSphere(0.07, 10, 8);
      glTranslatef(0, 0, -1.26);
      glutSolidSphere(0.07, 10, 8);
    glPopMatrix();

    /* Blowhole */
    glColor3f(0.08, 0.08, 0.12);
    glPushMatrix();
      glTranslatef(blowHoleX, blowHoleY, blowHoleZ);
      glScalef(0.15, 0.04, 0.1);
      glutSolidSphere(1, 10, 8);
    glPopMatrix();
}

/* User scene commands captured from gl-repl. */
static void draw_scene(void) {
  /* Snippet start */
  /* @declare launchVelX launchVelY launchVelZ */
  /* @declare currentVelY */
  /* @declare particleLife particleAge */
  /* @declare dragDecay */
  /* @declare gravityY */
  /* @declare dragRate */
  /* @declare particleX particleY particleZ */
  /* @declare floorY */
  /* @declare spawnDelay */
  /* @declare emitDuration */
  /* @declare fluke_ang fin_ang */
  /* @declare speed */
  /* @declare detail */
  /* @declare blowHoleX blowHoleY blowHoleZ */
  /* @declare waterDroplets @tune */

  glColor4f(0.25, 0.45, 0.85, 0.46);
  glEnable(GL_BLEND);
  glBlendFunc(GL_SRC_ALPHA, GL_ONE);
  glEnable(GL_DEPTH_TEST);
  glDepthFunc(GL_ALWAYS);
  glPointSize(10);

  if(t > 2*emitDuration) {
    t = 0;
  }

  glBegin(GL_POINTS);
    { /* repl-export-c89-loop-scope */
    float i; /* repl-export-c89-loop-var */
    for (i = 0; i < waterDroplets; i += 1.0f) {
      launchVelX = 3 * repl_rand2f(i,1);
      launchVelY = 2 + 2 * repl_randf(i, 2);
      launchVelZ = 3 * repl_rand2f(i, 3);

      computeLifespan(blowHoleY);
      spawnDelay = 3 * repl_randf(i,4);

      if((t - spawnDelay) > 0 && ( t <= ceilf(emitDuration/particleLife)*particleLife + spawnDelay)) {
        particleAge = fmodf(t - spawnDelay, particleLife);

        computeDriftX(particleAge, blowHoleX);
        computeVerticalMotion(particleAge, blowHoleY);
        computeDriftZ(particleAge, blowHoleZ);

        glVertex3f(particleX + 0.05, particleY, particleZ);
      }
    }
    } /* repl-export-c89-loop-scope */
  glEnd();

  glDepthFunc(GL_LESS);

  glEnable(GL_DEPTH_TEST);
  glEnable(GL_NORMALIZE);
  glDisable(GL_BLEND);

  glEnable(GL_LIGHT0);
  glEnable(GL_LIGHT1);

  glEnable(GL_LIGHTING);

  drawWhale(blowHoleX, blowHoleY, blowHoleZ);
  /* Snippet end */
}

/* @tune knobs: keyboard-adjustable variables + overlay, generated because
 * one or more `float` decls carried a `// @tune` tag. */
static int window_width = 800;
static int window_height = 600;

/* Mirror of repl_eval_swatch_step() (src/repl/eval.c); pinned by the
 * swatch-parity test in tests/test_repl_tune.c so it cannot drift. */
static float tuning_step(float value) {
  float magnitude = fabsf(value);
  float exponent = (magnitude < 10.0f) ? 0.0f : floorf(log10f(magnitude));
  return 0.05f * powf(10.0f, exponent);
}

/* Draw formatted bitmap text in screen-space HUD coordinates. */
static void hud_text(float x, float y, const char *fmt, ...) {
  const char *ch;
  char line_text[96];
  va_list args;

  va_start(args, fmt);
  vsnprintf(line_text, sizeof line_text, fmt, args);
  va_end(args);

  glRasterPos2f(x, y);
  for (ch = line_text; *ch; ch++)
    glutBitmapCharacter(GLUT_BITMAP_9_BY_15, (unsigned char)*ch);
}

static void draw_tuning_overlay(void) {
  int overlay_width = window_width;
  int overlay_height = window_height;
  float text_y = (float)overlay_height - 18.0f;

  glMatrixMode(GL_PROJECTION);
  glPushMatrix();
  glLoadIdentity();
  glOrtho(0, overlay_width, 0, overlay_height, -1, 1);

  glMatrixMode(GL_MODELVIEW);
  glPushMatrix();
  glLoadIdentity();

  glPushAttrib(GL_ALL_ATTRIB_BITS);
  glDisable(GL_LIGHTING);
  glDisable(GL_DEPTH_TEST);
  glColor3f(1.0f, 1.0f, 1.0f);


  hud_text(8.0f, text_y, "q/a  waterDroplets = %.4g", (double)waterDroplets);
  text_y -= 16.0f;
  glPopAttrib();

  glMatrixMode(GL_PROJECTION);
  glPopMatrix();
  glMatrixMode(GL_MODELVIEW);
  glPopMatrix();
}

/* Draw one frame. */
void display(void) {
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
  glLoadIdentity();
  glPushAttrib(GL_ALL_ATTRIB_BITS);
  glEnable(GL_MULTISAMPLE);
  glDisable(GL_LINE_SMOOTH);
  glTranslatef(0.0000f, 0.0000f, -6.5473f);
  glRotatef(20.6076f, 1.0f, 0.0f, 0.0f);
  glRotatef(g_angle, 0.0f, 1.0f, 0.0f);
  glTranslatef(0.2893f, -0.0000f, -0.0242f);
  /* Light positions, set after the camera so they stay anchored in world space. */
  glLightfv(GL_LIGHT0, GL_POSITION, repl_glfloat4(2, 4, 5, 0));
  glLightfv(GL_LIGHT1, GL_POSITION, repl_glfloat4(-3, 2, -2, 1));
  glLightfv(GL_LIGHT2, GL_POSITION, repl_glfloat4(0, -1, 3, 1));
  glLightfv(GL_LIGHT3, GL_POSITION, repl_glfloat4(1, 1, -4, 0));

  /* Vertex Fill Pass */
  glPushAttrib(GL_ALL_ATTRIB_BITS);
  glPushMatrix();
  draw_scene();
  glPopMatrix();
  glPopAttrib();
  draw_tuning_overlay();
  glPopAttrib();
  glutSwapBuffers();
}

/* Keep the projection matched to the current window size. */
void reshape(int w, int h) {
  window_width = w;
  window_height = h;
  glViewport(0, 0, w, h);
  glMatrixMode(GL_PROJECTION);
  glLoadIdentity();
  gluPerspective(45, (double)w/(double)h, 0.1, 200);
  glMatrixMode(GL_MODELVIEW);
}

/* Keyboard controls: Space toggles rotation; Esc exits. */
void keyboard(unsigned char key, int mouse_x, int mouse_y) {
  int modifiers = glutGetModifiers();
  unsigned char normalized_key = key;
  float step_scale = 1.0f;

  (void)mouse_x;
  (void)mouse_y;

  if ((modifiers & GLUT_ACTIVE_CTRL) && normalized_key >= 1 && normalized_key <= 26) {
    normalized_key = (unsigned char)(normalized_key - 1 + 'a');
  } else if (normalized_key >= 'A' && normalized_key <= 'Z') {
    normalized_key = (unsigned char)(normalized_key + ('a' - 'A'));
  }

  if (modifiers & GLUT_ACTIVE_SHIFT)
    step_scale *= 0.2f;
  if (modifiers & GLUT_ACTIVE_CTRL)
    step_scale *= 10.0f;

  if (normalized_key == 'q') waterDroplets += tuning_step(waterDroplets) * step_scale;
  if (normalized_key == 'a') waterDroplets -= tuning_step(waterDroplets) * step_scale;
  if (key == ' ')
    g_rotating = !g_rotating;
  if (key == 27)
    exit(0);
}

static double timer_now_ms(void) {
  return (double)glutGet(GLUT_ELAPSED_TIME);
}

static int timer_delay_ms(double *next_deadline_ms) {
  double now = timer_now_ms();
  int delay;

  if (*next_deadline_ms == 0.0)
    *next_deadline_ms = now;
  *next_deadline_ms += 1000.0 / 60.0;
  if (*next_deadline_ms < now)
    *next_deadline_ms = now;

  delay = (int)(*next_deadline_ms - now + 0.5);
  if (delay < 1)
    delay = 1;
  return delay;
}

/* Advance animation at roughly 60 frames per second. */
void tick(int value) {
  static double next_deadline_ms = 0.0;
  int delay;

  (void)value;
  /* Fixed-step time advance, matching the live REPL's
   * repl_state_time_advance(0.01667) timer. Keeps tDelta = (t -
   * tLast) * 10 constant across frames, independent of how long
   * each render actually takes. */
  t += 0.01667f;
  if (g_rotating)
    g_angle += 0.5f;
  glutPostRedisplay();
  delay = timer_delay_ms(&next_deadline_ms);
  glutTimerFunc((unsigned int)delay, tick, 0);
}

/* One-time OpenGL state setup. */
void init(void) {
  glLineWidth(1.5f);
  glLightModelfv(GL_LIGHT_MODEL_AMBIENT, repl_glfloat4(0.15f, 0.15f, 0.20f, 1.0f));
  /* Per-light colors. World-space POSITION is set in display() after the */
  /* camera transforms (glLightfv(GL_POSITION) snapshots the active */
  /* modelview); eye-space slots (headlight theme) push POSITION here at */
  /* identity, before main() drives the first display callback. */
  glLightfv(GL_LIGHT0, GL_DIFFUSE,  repl_glfloat4(0.8, 0.8, 0.75, 1));
  glLightfv(GL_LIGHT0, GL_AMBIENT,  repl_glfloat4(0.1, 0.1, 0.12, 1));
  glLightfv(GL_LIGHT0, GL_SPECULAR, repl_glfloat4(1, 1, 0.95, 1));
  glDisable(GL_LIGHT0);
  glLightfv(GL_LIGHT1, GL_DIFFUSE,  repl_glfloat4(0.45, 0.3, 0.15, 1));
  glLightfv(GL_LIGHT1, GL_AMBIENT,  repl_glfloat4(0.05, 0.03, 0.02, 1));
  glLightfv(GL_LIGHT1, GL_SPECULAR, repl_glfloat4(0.3, 0.2, 0.1, 1));
  glDisable(GL_LIGHT1);
  glLightfv(GL_LIGHT2, GL_DIFFUSE,  repl_glfloat4(0.15, 0.25, 0.5, 1));
  glLightfv(GL_LIGHT2, GL_AMBIENT,  repl_glfloat4(0.02, 0.03, 0.06, 1));
  glLightfv(GL_LIGHT2, GL_SPECULAR, repl_glfloat4(0.1, 0.15, 0.35, 1));
  glDisable(GL_LIGHT2);
  glLightfv(GL_LIGHT3, GL_DIFFUSE,  repl_glfloat4(0.35, 0.35, 0.4, 1));
  glLightfv(GL_LIGHT3, GL_AMBIENT,  repl_glfloat4(0.05, 0.05, 0.06, 1));
  glLightfv(GL_LIGHT3, GL_SPECULAR, repl_glfloat4(0.2, 0.2, 0.25, 1));
  glDisable(GL_LIGHT3);
  /* Background color used by glClear at the start of every frame. */
  glClearColor(0.1, 0.1, 0.1, 1);
  /* Color material: glColor* values drive ambient + diffuse so user */
  /* code can tint lit geometry without explicit glMaterial calls. */
  glEnable(GL_COLOR_MATERIAL);
  glColorMaterial(GL_FRONT_AND_BACK, GL_AMBIENT_AND_DIFFUSE);
  /* Light both sides of each face, and set non-zero specular and */
  /* shininess defaults so user-enabled lighting matches the REPL */
  /* preview instead of the GL-default black specular. */
  glLightModeli(GL_LIGHT_MODEL_TWO_SIDE, GL_TRUE);
  glMaterialfv(GL_FRONT_AND_BACK, GL_SPECULAR, repl_glfloat4(0.4, 0.4, 0.4, 1));
  glMaterialfv(GL_FRONT_AND_BACK, GL_SHININESS, repl_glfloat1(30));
  /* Blending: standard src-over for translucent geometry. */
  glEnable(GL_BLEND);
  glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
  /* Point attenuation: points hold a constant world-space footprint, */
  /* shrinking as 1/distance like everything else under perspective. */
  glPointParameterfv(GL_POINT_DISTANCE_ATTENUATION, repl_glfloat3(0.01, 0, 0.0625));
}

int main(int argc, char **argv) {
  glutInit(&argc, argv);
  glutInitDisplayMode(GLUT_DOUBLE|GLUT_RGB|GLUT_DEPTH|GLUT_MULTISAMPLE);
  glutInitWindowSize(1200, 440);
  glutCreateWindow("OpenGL REPL");
  init();
  glutDisplayFunc(display);
  glutReshapeFunc(reshape);
  glutKeyboardFunc(keyboard);
  glutTimerFunc(16, tick, 0);
  glutMainLoop();
  return 0;
}
