#include "repl/examples.h"
#include "repl/catalog_tags.h"

#include <stddef.h>
#include "c_compat.h"   /* STATIC_ASSERT (C99/C11 portable) */

/* Each example is an array of source lines terminated by NULL.
 * Lines are processed sequentially:
 *   "for(...) {"  -> CMD_FOR_BEGIN + CMD_FOR_END, enters block
 *   "funcN {"     -> CMD_FUNC_DEF + CMD_FUNC_END, enters block
 *   "if(...) {"   -> CMD_IF_BEGIN + CMD_IF_END, enters block
 *   "}"           -> closes current block
 *   "x = expr;"   -> CMD_VAR_ASSIGN
 *   "funcN()"     -> CMD_CALL
 *   anything else -> parse_command() as a regular GL command
 *
 * Predefined examples can optionally start with contiguous scene-presentation
 * config metadata lines using the exported-file format:
 *   "// @cfg axes = AXES_THEME_COMPASS"
 *   "// @cfg vertex_outlines = 0"
 * Supported slugs are limited to visual scene settings such as wireframe,
 * grid, axes, vertex overlays, backdrop, and camera_rotate. These metadata
 * lines are consumed by the example loader and are not shown in the code panel.
 *
 * A camera preset may then follow immediately after the cfg lines:
 *   "// camera"
 *   "glTranslatef(0.0f, 0.0f, -dist);"
 *   "glRotatef(rx, 1.0f, 0.0f, 0.0f);"
 *   "glRotatef(ry, 0.0f, 1.0f, 0.0f);"
 *   "glTranslatef(-tx, -ty, -tz);"
 * Both cfg and camera metadata are consumed by the example loader and are not
 * shown in the code panel.
 */

/* Example 0: Lit cube (default) */
static const char *const g_example_cube[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(20.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(35.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glShadeModel(GL_SMOOTH);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "//glEnable(GL_LINE_SMOOTH);",
    "glColor3f(1, 1, 1);",
    "glBegin(GL_QUAD_STRIP);",
    "glNormal3f(0, 1, 0);",
    "glVertex3f(1, 1, 1);",
    "glNormal3f(0, 1, 0);",
    "glVertex3f(-1, 1, 1);",
    "glNormal3f(0, 0, 1);",
    "glVertex3f(1, -1, 1);",
    "glNormal3f(0, 0, 1);",
    "glVertex3f(-1, -1, 1);",
    "glNormal3f(-0, -1, -0);",
    "glVertex3f(1, -1, -1);",
    "glNormal3f(-0, -1, -0);",
    "glVertex3f(-1, -1, -1);",
    "glNormal3f(0, 0, -1);",
    "glVertex3f(1, 1, -1);",
    "glNormal3f(0, 0, -1);",
    "glVertex3f(-1, 1, -1);",
    "glNormal3f(0, 1, -0);",
    "glVertex3f(1, 1, 1);",
    "glNormal3f(0, 1, -0);",
    "glVertex3f(-1, 1, 1);",
    "glEnd();",
    NULL
};

/* Example 1: Animated ring - for-loop + t variable */
static const char *const g_example_ring[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(10.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(10.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glBegin(GL_LINE_LOOP);",
    "for(i, 0, 48) {",
        "glColor3f(sin(i*TAU/48)*0.5+0.5, cos(i*TAU/48)*0.5+0.5, 0.5);",
        "glVertex3f(cos(i*TAU/48+t)*2, sin(i*TAU/48+t)*2, sin(i*TAU/12+t)*0.5);",
    "}",
    "glEnd();",
    "glBegin(GL_TRIANGLE_FAN);",
    "glColor3f(0.2, 0.5, 1);",
    "glVertex3f(0, 0, 0);",
    "for(i, 0, 25) {",
        "glColor3f(sin(i*TAU/24+t)*0.5+0.5, 0.3, cos(i*TAU/24+t)*0.5+0.5);",
        "glVertex3f(cos(i*TAU/24)*1.5, sin(i*TAU/24)*1.5, 0);",
    "}",
    "glEnd();",
    NULL
};

/* Example 2: Function demo - define a named reusable function (alias for a
 * funcN slot), call it repeatedly with transforms between calls. */
static const char *const g_example_func[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -3.0f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "// @cfg vertex_points = 0",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "triangle() {",
        "glBegin(GL_TRIANGLES);",
        "glNormal3f(0, 0, 1);",
        "glVertex3f(0, 0.8, 0);",
        "glVertex3f(-0.7, -0.4, 0);",
        "glVertex3f(0.7, -0.4, 0);",
        "glEnd();",
    "}",
    "glColor3f(1, 0.3, 0.3);",
    "triangle();",
    "glTranslatef(2, 0, 0);",
    "glColor3f(0.3, 1, 0.3);",
    "triangle();",
    "glTranslatef(-4, 0, 0);",
    "glColor3f(0.3, 0.3, 1);",
    "triangle();",
    NULL
};

/* Example 3: Parametric polygon helper - function args driving local for-loops */
static const char *const g_example_func_loop[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -4.0f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "polygon(radius, sides, phase) {",
        "glBegin(GL_TRIANGLE_FAN);",
        "glNormal3f(0, 0, 1);",
        "glColor3f(1, 1, 1);",
        "glVertex3f(0, 0, 0);",
        "for(i, 0, sides + 1) {",
            "glColor3f(sin(i*TAU/sides + phase)*0.5+0.5, cos(i*TAU/sides + phase)*0.5+0.5, 0.8);",
            "glVertex3f(cos(i*TAU/sides + phase)*radius, sin(i*TAU/sides + phase)*radius, 0);",
        "}",
        "glEnd();",
    "}",
    "glPushMatrix();",
    "glTranslatef(-2.4, 0, 0);",
    "polygon(0.9, 3, t*0.4);",
    "glPopMatrix();",
    "glPushMatrix();",
    "polygon(0.9, 6, -t*0.25);",
    "glPopMatrix();",
    "glPushMatrix();",
    "glTranslatef(2.4, 0, 0);",
    "polygon(0.9, 10, t*0.15);",
    "glPopMatrix();",
    NULL
};

/* Example 4: Branching helper - function args driving local if-blocks */
static const char *const g_example_func_if[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -4.0f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "shape(scale, phase) {",
        "if(scale > 1) {",
            "glColor3f(1, 0.35, 0.2);",
            "glBegin(GL_QUADS);",
            "glNormal3f(0, 0, 1);",
            "glVertex3f(-0.7*scale, -0.7*scale, 0);",
            "glVertex3f(0.7*scale, -0.7*scale, 0);",
            "glVertex3f(0.7*scale, 0.7*scale, 0);",
            "glVertex3f(-0.7*scale, 0.7*scale, 0);",
            "glEnd();",
        "}",
        "if(scale <= 1) {",
            "glColor3f(0.2, 0.75, 1);",
            "glBegin(GL_TRIANGLES);",
            "glNormal3f(0, 0, 1);",
            "glVertex3f(cos(phase)*0.9*scale, sin(phase)*0.9*scale, 0);",
            "glVertex3f(cos(phase+TAU/3)*0.9*scale, sin(phase+TAU/3)*0.9*scale, 0);",
            "glVertex3f(cos(phase+2*TAU/3)*0.9*scale, sin(phase+2*TAU/3)*0.9*scale, 0);",
            "glEnd();",
        "}",
    "}",
    "glPushMatrix();",
    "glTranslatef(-2.2, 0, 0);",
    "shape(0.9, t);",
    "glPopMatrix();",
    "glPushMatrix();",
    "shape(1.4, t*0.5);",
    "glPopMatrix();",
    "glPushMatrix();",
    "glTranslatef(2.2, 0, 0);",
    "shape(0.65, -t*0.8);",
    "glPopMatrix();",
    NULL
};

/* Example 5: Recursive helper - transformed child calls with depth countdown */
static const char *const g_example_func_recurse[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "// Recursive triangle tree: child calls shrink and rotate from the parent",
    "branch(depth, size, spin) {",
        "glColor3f(0.25 + depth*0.14, 0.45 + 0.2*sin(spin), 1 - depth*0.12);",
        "glBegin(GL_LINE_LOOP);",
        "glNormal3f(0, 0, 1);",
        "glVertex3f(0, size, 0);",
        "glVertex3f(-0.866*size, -0.5*size, 0);",
        "glVertex3f(0.866*size, -0.5*size, 0);",
        "glEnd();",
        "if(depth <= 0) {",
            "glColor3f(1, 0.8, 0.2);",
            "glBegin(GL_TRIANGLES);",
            "glNormal3f(0, 0, 1);",
            "glVertex3f(0, size*0.55, 0);",
            "glVertex3f(-0.48*size, -0.25*size, 0);",
            "glVertex3f(0.48*size, -0.25*size, 0);",
            "glEnd();",
        "}",
        "if(depth > 0) {",
            "glPushMatrix();",
            "glTranslatef(0, size*1.02, 0);",
            "glRotatef(18 + spin*14, 0, 0, 1);",
            "branch(depth - 1, size*0.62, spin + 0.15);",
            "glPopMatrix();",
            "glPushMatrix();",
            "glTranslatef(-size*0.9, -size*0.38, 0);",
            "glRotatef(-30 - spin*12, 0, 0, 1);",
            "branch(depth - 1, size*0.58, spin + 0.12);",
            "glPopMatrix();",
            "glPushMatrix();",
            "glTranslatef(size*0.9, -size*0.38, 0);",
            "glRotatef(30 + spin*12, 0, 0, 1);",
            "branch(depth - 1, size*0.58, spin + 0.12);",
            "glPopMatrix();",
        "}",
    "}",
    "glRotatef(sin(t*0.35)*12, 0, 0, 1);",
    "branch(4, 1.05, sin(t*0.4));",
    NULL
};

/* Example 6: Conditional colors - if-blocks + t variable */
static const char *const g_example_cond[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(20.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(35.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glBegin(GL_QUADS);",
    "if(sin(t) > 0) {",
        "glColor3f(1, 0.2, 0.2);",
    "}",
    "if(sin(t) <= 0) {",
        "glColor3f(0.2, 0.2, 1);",
    "}",
    "glNormal3f(0, 0, 1);",
    "glVertex3f(-1, -1, 0);",
    "glVertex3f(1, -1, 0);",
    "glVertex3f(1, 1, 0);",
    "glVertex3f(-1, 1, 0);",
    "if(cos(t) > 0) {",
        "glColor3f(0.2, 1, 0.2);",
    "}",
    "if(cos(t) <= 0) {",
        "glColor3f(1, 1, 0.2);",
    "}",
    "glNormal3f(0, 0, -1);",
    "glVertex3f(-1, -1, -1);",
    "glVertex3f(-1, 1, -1);",
    "glVertex3f(1, 1, -1);",
    "glVertex3f(1, -1, -1);",
    "glEnd();",
    NULL
};

/* Example 7: Parametric torus - nested for-loops.
 * Standard parametrization:
 *   P(u, v) = ((R + r*cos v) * cos u,
 *              (R + r*cos v) * sin u,
 *              r * sin v)
 * with u sweeping the major (ring) angle and v the minor (tube) angle. */
static const char *const g_example_torus[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -8.0f);",
    "glRotatef(20.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(35.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "static float R = 2;  // major radius (ring center to tube center)",
    "static float r = 1;  // minor radius (tube thickness)",
    "static float n = 24; // segment count around both u and v",
    "static float u, v;   // current major/minor angles",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "//glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "glShadeModel(GL_SMOOTH);",
    "n = floor(n); // keep an an integer",
    "n = min(25, max(n, 3)); // clamp to reasonable range",
    "for(i, 0, n) {",
        "glBegin(GL_QUAD_STRIP);",
        "for(j, 0, n+1) {",
            "// step v across the tube; emit two vertices, one at u=i and one at u=i+1",
            "v = j*TAU/n;",
            "u = i*TAU/n;",
            "glColor3f(sin(u)*0.4+0.6, cos(v)*0.4+0.6, 0.5);",
            "glVertex3f((R + r*cos(v))*cos(u), (R + r*cos(v))*sin(u), r*sin(v));",
            "u = (i+1)*TAU/n;",
            "glVertex3f((R + r*cos(v))*cos(u), (R + r*cos(v))*sin(u), r*sin(v));",
        "}",
        "glEnd();",
    "}",
    NULL
};

/* Example 8: GLU tessellator - concave arrow polygon with per-vertex color */
static const char *const g_example_tess[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(10.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(15.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "glShadeModel(GL_SMOOTH);",
    "glFrontFace(GL_CW);",
    "// Arrow shape - concave, tessellated with per-vertex color",
    "gluBegin(GLU_POLYGON);",
    "gluBegin(GLU_CONTOUR);",
    "gluNormal(0, 0, 1);",
    "gluColor(0.2, 0.4, 1, 1);",
    "gluVertex(-1.2, -0.45, 0);",
    "gluColor(0.2, 0.4, 1, 1);",
    "gluVertex(-1.2, 0.45, 0);",
    "gluColor(0.55, 0.3, 1, 1);",
    "gluVertex(0, 0.45, 0);",
    "gluColor(1, 0.45, 0.05, 1);",
    "gluVertex(0, 1.1, 0);",
    "gluColor(1, 0.9, 0.1, 1);",
    "gluVertex(1.3, 0, 0);",
    "gluColor(1, 0.45, 0.05, 1);",
    "gluVertex(0, -1.1, 0);",
    "gluColor(0.55, 0.3, 1, 1);",
    "gluVertex(0, -0.45, 0);",
    "gluEnd();",
    "gluEnd();",
    NULL
};

/* Example 9: GLU tessellator - concave arrow polygon cutout */
static const char *const g_example_tess_cutout[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(10.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(15.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "static float z;",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "glShadeModel(GL_SMOOTH);",
    "glFrontFace(GL_CW);",
    "z = -0.55;",
    "glRotatef(10*t, 0, 0, 1);",
    "// glScalef(0.5, 0.5, 0.5);",
    "// Arrow shape - concave, tessellated with per-vertex color",
    "gluBegin(GLU_POLYGON);",
    "  gluBegin(GLU_CONTOUR);",
    "    glBegin(GL_QUAD_STRIP);",
    "    gluNormal(0, 0, 1);",
    "  // Side 0",
    "    gluColor(0.2, 0.4, 1, 1);",
    "      glColor3f(0.2, 0.4, 1);",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(-1.2, -0.45, 0);",
    "      glVertex3f(-1.2, -0.45, z);",
    "    gluVertex(-1.2, -0.45, 0);",
    "  // Side 1",
    "    gluColor(0.2, 0.4, 1, 1);",
    "      glColor3f(0.2, 0.4, 1);",
    "      glNormal3f(0, 1, 0);",
    "      glVertex3f(-1.2, 0.45, 0);",
    "      glVertex3f(-1.2, 0.45, z);",
    "    gluVertex(-1.2, 0.45, 0);",
    "  // Side 2",
    "    gluColor(0.55, 0.3, 1, 1);",
    "      glColor3f(0.55, 0.3, 1);",
    "      glNormal3f(-1, 1, 0);",
    "      glVertex3f(0, 0.45, 0);",
    "      glVertex3f(0, 0.45, z);",
    "    gluVertex(0, 0.45, 0);",
    "  // Side 3",
    "    gluColor(1, 0.45, 0.05, 1);",
    "      glColor3f(1, 0.45, 0.05);",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(0, 1.1, 0);",
    "      glVertex3f(0, 1.1, z);",
    "    gluVertex(0, 1.1, 0);",
    "  // Side 4",
    "    gluColor(1, 0.9, 0.1, 1);",
    "      glColor3f(1, 0.9, 0.1);",
    "      glNormal3f(1, 0, 0);",
    "      glVertex3f(1.3, 0, 0);",
    "      glVertex3f(1.3, 0, z);",
    "    gluVertex(1.3, 0, 0);",
    "  // Side 5",
    "    gluColor(1, 0.45, 0.05, 1);",
    "      glColor3f(1, 0.45, 0.05);",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(0, -1.1, 0);",
    "      glVertex3f(0, -1.1, z);",
    "    gluVertex(0, -1.1, 0);",
    "  // Side 6",
    "    gluColor(0.55, 0.3, 1, 1);",
    "      glColor3f(0.55, 0.3, 1);",
    "      glNormal3f(-1, -1, 0);",
    "      glVertex3f(0, -0.45, 0);",
    "      glVertex3f(0, -0.45, z);",
    "    gluVertex(0, -0.45, 0);",
    "  // Quade side 7",
    "      glColor3f(0.2, 0.4, 1);",
    "      glNormal3f(0, -1, 0);",
    "      glVertex3f(-1.2, -0.45, 0);",
    "      glVertex3f(-1.2, -0.45, z);",
    "    glEnd();",
    "  gluEnd();",
    "  gluBegin(GLU_CONTOUR);",
    "    glBegin(GL_QUAD_STRIP);",
    "      glColor3f(0.5, 0.5, 0.5);",
    "    gluNormal(0, 0, 1);",
    "  // Side 0",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(-0.6, -0.225, 0);",
    "      glVertex3f(-0.6, -0.225, z);",
    "    gluVertex(-0.6, -0.225, 0);",
    "  // Side 1",
    "      glNormal3f(0, 1, 0);",
    "      glVertex3f(-0.6, 0.225, 0);",
    "      glVertex3f(-1.2/2, 0.45/2, z);",
    "    gluVertex(-0.6, 0.225, 0);",
    "  // Side 2",
    "      glNormal3f(-1, 1, 0);",
    "      glVertex3f(0.2, 0.225, 0);",
    "      glVertex3f(0.2, 0.45/2, z);",
    "    gluVertex(0.2, 0.225, 0);",
    "  // Side 3",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(0.2, 0.55, 0);",
    "      glVertex3f(0.2, 1.1/2, z);",
    "    gluVertex(0.2, 0.55, 0);",
    "  // Side 4",
    "      glNormal3f(1, 0, 0);",
    "      glVertex3f(0.85, 0, 0);",
    "      glVertex3f(1.7/2, 0, z);",
    "    gluVertex(0.85, 0, 0);",
    "  // Side 5",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(0.2, -0.55, 0);",
    "      glVertex3f(0.2, -1.1/2, z);",
    "    gluVertex(0.2, -0.55, 0);",
    "  // Side 6",
    "      glNormal3f(-1, -1, 0);",
    "      glVertex3f(0.2, -0.225, 0);",
    "      glVertex3f(0.2, -0.45/2, z);",
    "    gluVertex(0.2, -0.225, 0);",
    "  // Quad side 7",
    "      glNormal3f(0, -1, 0);",
    "      glVertex3f(-0.6, -0.225, 0);",
    "      glVertex3f(-1.2/2, -0.45/2, z);",
    "    glEnd();",
    "  gluEnd();",
    "gluEnd();",
    NULL
};

/* Example 10: 2D assignment sketch - runtime assignment without goto.
 * No predefined goto examples are shipped because goto support is partial:
 * top-level only, not replay-safe, and not suitable for variable-driven
 * geometry loops. Keep coverage in tests/docs instead of F12 examples. */
static const char *const g_example_assign_2d[] = {
    "// @cfg view_mode = 1",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -2.5f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "static float x, y;",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "// 2D assignment sketch: tests runtime variable assignment without goto",
    "glDisable(GL_LIGHTING);",
    "x = -1.7;",
    "glBegin(GL_LINE_STRIP);",
    "for(i, 0, 48) {",
    "  x = x + 0.07;",
    "  y = sin(x*2.5 + t)*0.52 + cos(i*0.25 + t*0.6)*0.16;",
    "  glColor3f(0.30 + i*0.010, 0.55 + 0.28*sin(i*0.20 + t), 0.95 - i*0.008);",
    "  glVertex3f(x, y, 0);",
    "}",
    "glEnd();",
    NULL
};

/* Example 11: Additive glow particles - glPointSize + distance attenuation + blend */
static const char *const g_example_glow_particles[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg grid = GRID_THEME_EMBER",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -5.0f);",
    "glRotatef(15.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(10.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "static float radius, angle, x, y, z; // per-particle: orbit radius, base angle, world pos",
    "static float count = 160;       // number of glow points",
    "static float radMin = 0.4;      // nearest orbital radius (xz plane)",
    "static float radSpan = 1.8;     // additional radius range; radius in [radMin, radMin+radSpan]",
    "static float orbitRate = 0.4;   // angular speed of the xz orbit (animates with t)",
    "static float yWobbleFreq = 1.3; // y wobble frequency relative to the base angle",
    "static float yWobbleRate = 0.6; // y wobble time-rate (animates with t)",
    "static float yAmp = 0.9;        // y wobble amplitude",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "// Glow sprites: additive blend + distance-attenuated point size.",
    "// Each particle orbits in xz at (radius, angle) while y wobbles independently.",
    "glDisable(GL_LIGHTING);",
    "glDisable(GL_DEPTH_TEST);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE);",
    "glEnable(GL_POINT_SMOOTH);",
    "glPointSize(24);",
    "glPointParameterfv(GL_POINT_DISTANCE_ATTENUATION, 0.2, 0, 0.15);",
    "glBegin(GL_POINTS);",
    "for(i, 0, count) {",
    "  angle = rand(i, 0)*TAU;                  // random base angle in [0, TAU)",
    "  radius = radMin + rand(i, 1)*radSpan;    // random radius in the configured range",
    "  x = cos(angle + t*orbitRate)*radius;",
    "  y = sin(angle*yWobbleFreq + t*yWobbleRate)*yAmp;",
    "  z = sin(angle + t*orbitRate)*radius;",
    "  // per-particle base color: rand seeds 2/3/4 keep r/g/b stable across frames",
    "  glColor4f(0.4 + 0.6*rand(i, 2), 0.3 + 0.5*rand(i, 3), 0.8 + 0.2*rand(i, 4), 0.55);",
    "  glVertex3f(x, y, z);",
    "}",
    "glEnd();",
    "glDisable(GL_POINT_SMOOTH);",
    "glDisable(GL_BLEND);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    NULL
};

/* Example 13: Procedural terrain - rand(x,z) samples heights at each grid vertex,
 * building GL_QUAD_STRIP rows via nested for-loops. An animated sine ripple
 * (`ripple`) is added per row each frame, giving the flat random field a
 * rolling wave motion. Lit with GL_LIGHT0 + GL_LIGHT3, smooth-shaded. */

static const char *const g_example_random_surface[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -12.0f);",
    "glRotatef(30.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "static float halfExtent, h0, h1, ripple; // grid half-extent; QUAD_STRIP column-pair heights; animated row delta",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glShadeModel(GL_SMOOTH);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT0);",
    "glPointSize(4);",
    "glEnable(GL_BLEND);",
    "glColor4f(0.176, 0.51392, 0.88, 0.713333);",
    "halfExtent = 10; // grid spans [-halfExtent, halfExtent] on x and z",
    "glTranslatef(0, -0.25, 0);",
    "for (x, -halfExtent, halfExtent) {",
    "  glBegin(GL_QUAD_STRIP);",
    "    for (z, -halfExtent, halfExtent) {",
    "      // sample two random heights for the (x, z) and (x+1, z) corners",
    "      h0 = rand(x, z);",
    "      h1 = rand(x+1, z);",
    "      ripple = 0.25 * sin((100+t/2) * (z/200+4));",
    "      // NOTE: both branches add ripple to both heights, so the conditional is",
    "      //       currently dead. Likely intent: alternate which corner moves.",
    "      if(fmod(x, 2) == 0) {",
    "        h0 = h0 + ripple;",
    "        h1 = h1 + ripple;",
    "      }",
    "      if(abs(fmod(x, 2)) == 1) {",
    "        h1 = h1 + ripple;",
    "        h0 = h0 + ripple;",
    "      }",
    "      glVertex3f(x, h0, z);",
    "      glVertex3f(x+1, h1, z);",
    "    }",
    "  glEnd();",
    "}",
    NULL
};


/* Example 14: Animated wave surface - y = sin(freq*x + t)*cos(freq*z + zPhase*t)*amp
 * rendered as GL_TRIANGLE_STRIP rows. Normals are the exact analytic partial
 * derivatives of the wave function (no finite-difference approximation), giving
 * correct smooth lighting across all four lights. Per-vertex color varies with
 * position and t for a shifting iridescent look. */

static const char *const g_example_waves[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -5.0f);",
    "glRotatef(20.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(30.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "// @cfg vertex_points = 0",
    "static float grid, extent, x, y, z, invGradMag; // strip cell index, world extent, vertex coords, 1/|gradient|",
    "static float amp = 0.4;    // wave amplitude (peak |y|)",
    "static float freq = 2.5;   // spatial frequency along x and z",
    "static float zPhase = 0.7; // z-axis time phase: z evolves slower than x (<1)",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "// Animated surface: y = sin(freq*x + t) * cos(freq*z + zPhase*t) * amp",
    "// Drawn as a triangle strip per row with analytic per-vertex normals.",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "glEnable(GL_LIGHT1);",
    "glEnable(GL_LIGHT0);",
    "glShadeModel(GL_SMOOTH);",
    "grid = 16;     // rows/cols of strip cells",
    "extent = 3.0;  // total surface width along x and z",
    "for(i, 0, grid) {",
        "glBegin(GL_TRIANGLE_STRIP);",
        "for(j, 0, grid+1) {",
            "// row i (z fixed), step j across x; emit two vertices per j to feed the strip",
            "x = -extent/2 + extent*j/grid;",
            "z = -extent/2 + extent*i/grid;",
            "y = sin(x*freq + t)*cos(z*freq + zPhase*t)*amp;",
            "// gradient = (dy/dx, 0, dy/dz); normal = (-dy/dx, 1, -dy/dz) / |...|.",
            "// invGradMag = 1 / sqrt(1 + amp^2 * freq^2 * (cos^2*cos^2 + sin^2*sin^2)).",
            "invGradMag = 1.0/sqrt(1 + amp*amp*freq*freq*(cos(x*freq + t)*cos(x*freq + t)*cos(z*freq + zPhase*t)*cos(z*freq + zPhase*t) + sin(x*freq + t)*sin(x*freq + t)*sin(z*freq + zPhase*t)*sin(z*freq + zPhase*t)));",
            "glNormal3f(-amp*freq*cos(x*freq + t)*cos(z*freq + zPhase*t)*invGradMag, invGradMag, amp*freq*sin(x*freq + t)*sin(z*freq + zPhase*t)*invGradMag);",
            "glColor3f(0.35 + 0.35*sin(x + t), 0.5 + 0.3*cos(z + t*0.5), 0.65 + 0.25*sin(x*z + t));",
            "glVertex3f(x, y, z);",
            "// second strip vertex: same x, but z stepped to row i+1",
            "z = -extent/2 + extent*(i + 1)/grid;",
            "y = sin(x*freq + t)*cos(z*freq + zPhase*t)*amp;",
            "invGradMag = 1.0/sqrt(1 + amp*amp*freq*freq*(cos(x*freq + t)*cos(x*freq + t)*cos(z*freq + zPhase*t)*cos(z*freq + zPhase*t) + sin(x*freq + t)*sin(x*freq + t)*sin(z*freq + zPhase*t)*sin(z*freq + zPhase*t)));",
            "glNormal3f(-amp*freq*cos(x*freq + t)*cos(z*freq + zPhase*t)*invGradMag, invGradMag, amp*freq*sin(x*freq + t)*sin(z*freq + zPhase*t)*invGradMag);",
            "glColor3f(0.35 + 0.35*sin(x + t), 0.5 + 0.3*cos(z + t*0.5), 0.65 + 0.25*sin(x*z + t));",
            "glVertex3f(x, y, z);",
        "}",
        "glEnd();",
    "}",
    NULL
};

/* Example 15: Animated spirograph curve - closed parametric line loop
 * driven by t, showing dense iteration and trig-heavy vertex generation. */
static const char *const g_example_spirograph_curve[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -7.5f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "static float dist, n, x, y, ang;",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "dist = 1.4;",
    "n = 400;",
    "glBegin(GL_LINE_LOOP);",
    "  for(i, 0, n) {",
    "    ang = TAU * i/n;",
    "    x = dist * cos(t*ang) + cos(ang);",
    "    y = dist * sin(t*ang) + sin(ang);",
    "    glVertex3f(x, y, 0);",
    "  }",
    "glEnd();",
    NULL
};

/* Example 16: Traveling ripple ring - circular line loop with a narrow
 * modulo-selected radial wave, exercising fmod math and conditional edits. */
static const char *const g_example_traveling_ripple_ring[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -3.5f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "// Traveling ripple ring: nested for + fmod + conditional deformation",
    "static float phase, width, delta, amp, x, y;",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "amp = 0.1 * sin(t * TAU);",
    "phase = fmod(t / 3, TAU);",
    "width = PI / 8;",
    "glBegin(GL_LINE_LOOP);",
    "  for(i, 0, 400) {",
    "    x = cos(TAU * i / 400);",
    "    y = sin(TAU * i / 400);",
    "    delta = fmod(TAU * i / 400 - phase + TAU, TAU);",
    "    if(delta < width) {",
    "      x = x + amp * x * sin(delta * TAU / width);",
    "      y = y + amp * y * sin(delta * TAU / width);",
    "    }",
    "    glVertex3f(x, y, 0);",
    "  }",
    "glEnd();",
    NULL
};

/* Animated quadratic Bezier curve - vertex + line loop with parametric
 * function, showing variable assignment and reuse across calls. */
static const char *const g_example_bezier[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// @cfg poly_highlight = 0",
    "// @cfg msaa = 0",
    "// @cfg line_smooth = 1",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -3.5f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "static float x, y, x0, y0, x1 = 1, y1 = 1, x2 = 2, y2;",
    "static float period = 5;",
    "static float x_a, x_b, y_a, y_b;",
    "// current progress",
    "static float t0;",
    "bezier(x0, y0, x1, y1, x2, y2, u) {",
    "  x = pow(1-u, 2) * x0 + 2 * (1-u)*u * x1 + u*u * x2;",
    "  y = pow(1-u, 2) * y0 + 2 * (1-u)*u * y1 + u*u * y2;",
    "}",
    "glClearColor(0, 0, 0, 1);",
    "glEnable(GL_DEPTH_TEST);",
    "glDisable(GL_LIGHTING);",
    "glDisable(GL_MULTISAMPLE);",
    "glEnable(GL_LINE_SMOOTH);",
    "glEnable(GL_BLEND);",
    "glPointSize(8);",
    "glColor4f(0.8, 0.7, 0.3, 0.9);",
    "glLineWidth(1.3);",
    "t0 = (fmod(t, period)) / period;",
    "glBegin(GL_POINTS);",
    "  glVertex2f(x0, y0);",
    "  glVertex3f(x1, y1, 0);",
    "  glVertex2f(x2, y2);",
    "  bezier(x0, y0, x1, y1, x2, y2, t0);",
    "  glColor3f(0.3, 0.7, 0.9);",
    "  glVertex2f(x, y);",
    "glEnd();",
    "glColor4f(1, 1, 1, 0.9);",
    "glBegin(GL_LINE_STRIP);",
    "  for (u, 0, 1, 0.01f) {",
    "    bezier(x0, y0, x1, y1, x2, y2, u);",
    "    glVertex2f(x, y);",
    "  }",
    "glEnd();",
    "glColor4f(1, 1, 1, 0.3);",
    "x_a = x0*(1-t0) + x1*t0;",
    "y_a = y0*(1-t0) + y1*t0;",
    "x_b = x1*(1-t0) + x2*t0;",
    "y_b = y1*(1-t0) + y2*t0;",
    "glBegin(GL_POINTS);",
    "  glVertex2f(x_a, y_a);",
    "  glVertex2f(x_b, y_b);",
    "glEnd();",
    "glBegin(GL_LINES);",
    "  // Guide Line 1",
    "  glVertex2f(x0, y0);",
    "  glVertex2f(x1, y1);",
    "  // Guide Line 2",
    "  glVertex2f(x1, y1);",
    "  glVertex2f(x2, y2);",
    "  // Derived Line",
    "  glVertex2f(x_a, y_a);",
    "  glVertex2f(x_b, y_b);",
    "glEnd();",
    NULL
};

/* Snowfall - 550 GL_POINTS with x/y/z from rand(seed, iter) + time,
 * creating a looping field of falling points with depth-based color. */
static const char *const g_example_snowfall[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// @cfg poly_highlight = 0",
    "// @cfg grid = GRID_THEME_OFF",
    "// @cfg msaa = 1",
    "// @cfg line_smooth = 0",
    "// @cfg variable_panel = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -13.5f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "static float flakeCount = 550; // @tune",
    "static float flakeX, flakeY; // particle position",
    "static float drift, fall; // per-flake horizontal drift, vertical fall speed",
    "static float depth; // [0,1] random; depth and shade both derive from it",
    "static float driftMax = 0.5; // max horizontal drift magnitude",
    "static float fallBase = -1.5; // base fall speed (NOT gravity)",
    "static float wrapX = 12, wrapY = 5; // half-extents of the wrap region",
    "static float depthScale = 10; // multiplier on `depth` for z position",
    "glClearColor(0.05, 0.05, 0.05, 1);",
    "glEnable(GL_DEPTH_TEST);",
    "glPointSize(10);",
    "glBegin(GL_POINTS);",
    "  for (p, 0, flakeCount) {",
    "    drift = driftMax * rand2(p, 1);",
    "    flakeX = rem(wrapX * rand2(p,4) + t * drift, 2 * wrapX);",
    "",
    "    fall = fallBase - rand(p, 2);",
    "    flakeY = rem(wrapY * rand2(p,3) + t * fall, 2 * wrapY);",
    "",
    "    depth = rand(p, 5); // z affects color and distance",
    "",
    "    glColor3f(0.5 + 0.5 * depth, 0.5 + 0.5 * depth, 0.5 + 0.5 * depth);",
    "    glVertex3f(flakeX, flakeY, depthScale * depth);",
    "  }",
    "glEnd();",
    NULL
};

/* Grass field - deterministic blades from rand(seed, iter), with wind bend
 * derived from t so the scene stays stateless and REPL-friendly. */
static const char *const g_example_grass_field[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// @cfg poly_highlight = 0",
    "// @cfg grid = GRID_THEME_OFF",
    "// @cfg axes = AXES_THEME_OFF",
    "// @cfg msaa = 1",
    "// @cfg variable_panel = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -12.0f);",
    "glRotatef(56.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(-8.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, -0.9f, 0.0f);",
    "static float bladeCount = 72; // @tune",
    "static float field = 7.5; // half-width",
    "static float x, z, h, w, angle, phase, flex;",
    "static float wind, wave, bend, u, cx, cz, halfW, shade;",
    "blade(seed, x0, z0, height, width, ang, ph, stiffness) {",
    "  wind = 0.55 + 0.25*sin(t*0.23);",
    "  wave = sin(t*2.2 + ph + x0*0.35 + z0*0.20) + 0.35*sin(t*4.9 + ph*1.7);",
    "  bend = (0.65 + 0.35*sin(t*0.75))*wave*stiffness*height*0.26;",
    "  glBegin(GL_TRIANGLE_STRIP);",
    "  for(s, 0, 5) {",
    "    u = s/4;",
    "    cx = x0 + 0.08*rand2(seed, 6)*u + cos(wind)*bend*u*u;",
    "    cz = z0 + 0.08*rand2(seed, 7)*u + sin(wind)*bend*u*u;",
    "    halfW = width*(1 - 0.82*u);",
    "    shade = 0.65 + 0.45*u;",
    "    glColor4f((0.08 + 0.07*rand(seed, 8))*shade, (0.38 + 0.32*rand(seed, 9))*shade, (0.06 + 0.07*rand(seed, 10))*shade, 0.95);",
    "    glVertex3f(cx - cos(ang)*halfW, height*u, cz - sin(ang)*halfW);",
    "    glVertex3f(cx + cos(ang)*halfW, height*u, cz + sin(ang)*halfW);",
    "  }",
    "  glEnd();",
    "}",
    "glClearColor(0.025, 0.055, 0.035, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glDisable(GL_LIGHTING);",
    "glDisable(GL_CULL_FACE);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);",
    "glBegin(GL_QUADS);",
    "  glColor3f(0.08, 0.16, 0.07);",
    "  glVertex3f(-10, 0, -10);",
    "  glVertex3f(10, 0, -10);",
    "  glColor3f(0.16, 0.28, 0.10);",
    "  glVertex3f(10, 0, 10);",
    "  glVertex3f(-10, 0, 10);",
    "glEnd();",
    "for(p, 0, bladeCount) {",
    "  x = (rand(p, 0)*2 - 1)*field;",
    "  z = (rand(p, 1)*2 - 1)*field;",
    "  h = 0.28 + rand(p, 2)*0.72;",
    "  w = 0.018 + rand(p, 3)*0.026;",
    "  angle = rand(p, 4)*TAU;",
    "  phase = rand(p, 5)*TAU;",
    "  flex = 0.55 + rand(p, 6)*1.1;",
    "  blade(p, x, z, h, w, angle, phase, flex);",
    "}",
    "glDisable(GL_BLEND);",
    NULL
};

/* Stress test - exercises parser, code UI, nested structures,
 * multiple functions, recursion, conditionals, variables, tessellation,
 * GLU primitives, matrix stack, animation, and long line count. */
static const char *const g_example_stress[] = {
    "// @cfg axes = AXES_THEME_COMPASS",
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg backdrop = SCENE_BACKDROP_CITYSCAPE",
    "// @cfg grid = GRID_THEME_OCEAN",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -12.5f);",
    "glRotatef(27.5f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(-24.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(-0.6f, -0.1f, -0.4f);",
    "static float n, x, y, z, k;",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "// ===== Stress-test scene: parser + code UI torture =====",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT2);",
    "glEnable(GL_LIGHT3);",
    "glShadeModel(GL_SMOOTH);",
    "glColorMaterial(GL_FRONT_AND_BACK, GL_AMBIENT_AND_DIFFUSE);",
    "glLightModeli(GL_LIGHT_MODEL_TWO_SIDE, 1);",
    "",
    "// --- surface: parametric surface patch (nested for + math) ---",
    "surface(rows, cols, amp, phase) {",
        "for(i, 0, rows) {",
            "glBegin(GL_TRIANGLE_STRIP);",
            "for(j, 0, cols + 1) {",
                "x = -1.5 + 3.0*j/cols;",
                "z = -1.5 + 3.0*i/rows;",
                "y = amp*sin(x*2.5 + phase)*cos(z*2.5 + phase*0.7);",
                "n = 1.0/sqrt(1 + amp*amp*6.25*(cos(x*2.5 + phase)*cos(x*2.5 + phase)*cos(z*2.5 + phase*0.7)*cos(z*2.5 + phase*0.7) + sin(x*2.5 + phase)*sin(x*2.5 + phase)*sin(z*2.5 + phase*0.7)*sin(z*2.5 + phase*0.7)));",
                "glNormal3f(-amp*2.5*cos(x*2.5 + phase)*cos(z*2.5 + phase*0.7)*n, n, amp*2.5*sin(x*2.5 + phase)*sin(z*2.5 + phase*0.7)*n);",
                "glColor3f(0.35 + 0.35*sin(x + phase), 0.5 + 0.3*cos(z + phase*0.5), 0.65 + 0.25*sin(x*z + phase));",
                "glVertex3f(x, y, z);",
                "z = -1.5 + 3.0*(i + 1)/rows;",
                "y = amp*sin(x*2.5 + phase)*cos(z*2.5 + phase*0.7);",
                "n = 1.0/sqrt(1 + amp*amp*6.25*(cos(x*2.5 + phase)*cos(x*2.5 + phase)*cos(z*2.5 + phase*0.7)*cos(z*2.5 + phase*0.7) + sin(x*2.5 + phase)*sin(x*2.5 + phase)*sin(z*2.5 + phase*0.7)*sin(z*2.5 + phase*0.7)));",
                "glNormal3f(-amp*2.5*cos(x*2.5 + phase)*cos(z*2.5 + phase*0.7)*n, n, amp*2.5*sin(x*2.5 + phase)*sin(z*2.5 + phase*0.7)*n);",
                "glColor3f(0.35 + 0.35*sin(x + phase), 0.5 + 0.3*cos(z + phase*0.5), 0.65 + 0.25*sin(x*z + phase));",
                "glVertex3f(x, y, z);",
            "}",
            "glEnd();",
        "}",
    "}",
    "",
    "// --- tree: recursive branching tree (recursion + if + matrix stack) ---",
    "tree(depth, len, twist) {",
        "glColor3f(0.35 + depth*0.12, 0.25 + 0.15*sin(twist), 0.15);",
        "glBegin(GL_LINES);",
        "glNormal3f(0, 0, 1);",
        "glVertex3f(0, 0, 0);",
        "glVertex3f(0, len, 0);",
        "glEnd();",
        "if(depth > 0) {",
            "// Right branch",
            "glPushMatrix();",
            "glTranslatef(0, len, 0);",
            "glRotatef(25 + twist*8, 0, 0, 1);",
            "glScalef(0.72, 0.72, 0.72);",
            "tree(depth - 1, len, twist + 0.3);",
            "glPopMatrix();",
            "// Left branch",
            "glPushMatrix();",
            "glTranslatef(0, len, 0);",
            "glRotatef(-30 - twist*6, 0, 0, 1);",
            "glScalef(0.68, 0.68, 0.68);",
            "tree(depth - 1, len, twist + 0.25);",
            "glPopMatrix();",
            "// Forward branch (z-axis splay)",
            "glPushMatrix();",
            "glTranslatef(0, len*0.9, 0);",
            "glRotatef(15 + twist*4, 1, 0, 0);",
            "glScalef(0.6, 0.6, 0.6);",
            "tree(depth - 1, len*0.85, twist + 0.2);",
            "glPopMatrix();",
        "}",
        "if(depth <= 0) {",
            "// Leaf: small filled triangle",
            "glColor3f(0.2, 0.7 + 0.3*sin(twist*5), 0.15);",
            "glBegin(GL_TRIANGLES);",
            "glNormal3f(0, 0, 1);",
            "glVertex3f(0, len, 0);",
            "glVertex3f(-len*0.3, len*1.3, 0);",
            "glVertex3f(len*0.3, len*1.3, 0);",
            "glEnd();",
        "}",
    "}",
    "",
    "// --- starfloor: tessellated star floor with circular cutout ---",
    "starfloor(radius, hole) {",
        "glFrontFace(GL_CW);",
        "gluBegin(GLU_POLYGON);",
        "// Outer contour: 10-pointed star",
        "gluBegin(GLU_CONTOUR);",
        "gluNormal(0, 1, 0);",
        "for(i, 0, 20) {",
            "k = radius;",
            "if(fmod(i, 2) > 0) {",
                "k = radius*0.5;",
            "}",
            "gluColor(0.25 + 0.15*sin(i*0.6), 0.3 + 0.15*cos(i*0.8), 0.55 + 0.1*sin(i));",
            "gluVertex(k*cos(i*TAU/20), 0, k*sin(i*TAU/20));",
        "}",
        "gluEnd();",
        "// Inner contour: circular cutout (tessellator infers hole from overlap)",
        "gluBegin(GLU_CONTOUR);",
        "for(i, 0, 24) {",
            "gluColor(0.1, 0.1, 0.15);",
            "gluVertex(hole*cos(-i*TAU/24), 0, hole*sin(-i*TAU/24));",
        "}",
        "gluEnd();",
        "gluEnd();",
        "glFrontFace(GL_CCW);",
    "}",
    "",
    "// --- satellites: orbiting GLUT solid satellites ---",
    "satellites(count, orbit_r, sat_size, spin) {",
        "for(i, 0, count) {",
            "glPushMatrix();",
            "glRotatef(i*360/count + spin, 0, 1, 0);",
            "glTranslatef(orbit_r, 0, 0);",
            "// Sphere body",
            "glColor3f(0.8 + 0.2*sin(i + spin*0.02), 0.5, 0.3 + 0.2*cos(i));",
            "glutSolidSphere(sat_size, 12, 8);",
            "// Antenna cone",
            "glColor3f(0.5, 0.5, 0.6);",
            "glTranslatef(0, sat_size, 0);",
            "glRotatef(-90, 1, 0, 0);",
            "glutSolidCone(sat_size*0.15, sat_size*1.5, 8, 1);",
            "// Dish ring at top",
            "glTranslatef(0, 0, sat_size*1.5);",
            "glColor3f(0.9, 0.85, 0.5);",
            "glutSolidTorus(0.02*sat_size, sat_size*0.35, 12, 24);",
            "glPopMatrix();",
        "}",
    "}",
    "",
    "// ===== Main scene composition =====",
    "",
    "// Animated variables",
    "n = 8;",
    "x = 0.4*sin(t*0.6);",
    "y = 0.15*cos(t*0.8);",
    "",
    "// Ground: tessellated star floor",
    "glPushMatrix();",
    "glTranslatef(0, -1.8, 0);",
    "starfloor(3.0, 0.8);",
    "glPopMatrix();",
    "",
    "// Wavy parametric surface",
    "glPushMatrix();",
    "glTranslatef(0, x, 0);",
    "glRotatef(t*12, 0, 1, 0);",
    "surface(n, n, 0.35 + 0.15*sin(t), t*0.5);",
    "glPopMatrix();",
    "",
    "// Fractal tree (recursive)",
    "glPushMatrix();",
    "glTranslatef(-2.5, -1.8, 0);",
    "glRotatef(-5*sin(t*0.3), 0, 0, 1);",
    "tree(3, 0.7, t*0.2);",
    "glPopMatrix();",
    "",
    "// Second tree, mirrored",
    "glPushMatrix();",
    "glTranslatef(2.5, -1.8, 0);",
    "glScalef(-1, 1, 1);",
    "glRotatef(-5*cos(t*0.25), 0, 0, 1);",
    "tree(3, 0.65, t*0.15 + 1);",
    "glPopMatrix();",
    "",
    "// Orbiting satellites",
    "glPushMatrix();",
    "glTranslatef(0, y + 1.0, 0);",
    "satellites(5, 2.8, 0.18, t*35);",
    "glPopMatrix();",
    "",
    "// Central decoration: torus + sphere",
    "glPushMatrix();",
    "glTranslatef(0, 0.5 + 0.3*sin(t*1.2), 0);",
    "glRotatef(t*45, 0, 1, 0);",
    "glRotatef(t*20, 1, 0, 0);",
    "glColor3f(0.85, 0.6, 0.25);",
    "glutSolidTorus(0.12, 0.55, 16, 24);",
    "glColor3f(0.95, 0.90, 0.70);",
    "glutSolidSphere(0.25, 16, 12);",
    "glPopMatrix();",
    "",
    "// Wireframe accent ring",
    "glDisable(GL_LIGHTING);",
    "glBegin(GL_LINE_LOOP);",
    "for(i, 0, 64) {",
        "glColor3f(0.3 + 0.3*sin(i*TAU/64 + t), 0.5 + 0.2*cos(i*TAU/32 + t*0.7), 0.8);",
        "glVertex3f(3.5*cos(i*TAU/64), -1.75, 3.5*sin(i*TAU/64));",
    "}",
    "glEnd();",
    "glEnable(GL_LIGHTING);",
    "",
    "// Long expression stress: animated vertex spiral",
    "glDisable(GL_LIGHTING);",
    "glBegin(GL_LINE_STRIP);",
    "for(i, 0, 120) {",
        "x = (1.5 + 0.4*sin(i*TAU/30 + t*2))*cos(i*TAU/60 + t*0.3);",
        "y = -1.75 + i*0.025 + 0.08*sin(i*0.5 + t*3);",
        "z = (1.5 + 0.4*sin(i*TAU/30 + t*2))*sin(i*TAU/60 + t*0.3);",
        "glColor3f(0.1 + 0.5*sin(i*0.08 + t), 0.9 - 0.4*cos(i*0.06), 0.5 + 0.3*sin(i*0.12 + t*0.5));",
        "glVertex3f(x, y, z);",
    "}",
    "glEnd();",
    "glEnable(GL_LIGHTING);",
    NULL
};

/* Transformation stress test - exercises translate/rotate/scale guides in
 * varied contexts: nested push/pop, time-varying args (t), for-loop
 * unrolling, function scopes, and scale-of-origin (3-axis gizmo fallback).
 * Park the cursor on any transform line to see its guide overlay. */
static const char *const g_example_xform_stress[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -5.0f);",
    "glRotatef(00.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, -0.8f, 0.0f);",
    "",
    "glClearColor(0.08, 0.08, 0.1, 1);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_LIGHT0);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_COLOR_MATERIAL);",
    "tri() {",
        "glBegin(GL_TRIANGLES);",
        "glNormal3f(0, 0, 1);",
        "glVertex3f(-0.3, -0.3, 0);",
        "glVertex3f(0.3, -0.3, 0);",
        "glVertex3f(0, 0.4, 0);",
        "glEnd();",
    "}",
    "glColor3f(1, 0.6, 0.3);",
    "glPushMatrix();",
    "glTranslatef(0, 0, 2);",
    "glRotatef(45, 0, 1, 0);",
    "glTranslatef(0, 0, -2);",
    "tri();",
    "glPopMatrix();",
    "glColor3f(0.4, 0.9, 0.6);",
    "glPushMatrix();",
    "glTranslatef(-2, 0, 0);",
    "glRotatef(3*t, 0, 1, 0);",
    "glScalef(1.5, 0.5, 1);",
    "tri();",
    "glPopMatrix();",
    "glColor3f(0.6, 0.7, 1);",
    "for(i, 0, 6) {",
        "glPushMatrix();",
        "glRotatef(i*60, 0, 1, 0);",
        "glTranslatef(2.5, 0, 0);",
        "glScalef(0.6, 0.6, 0.6);",
        "tri();",
        "glPopMatrix();",
    "}",
    "glColor3f(1, 0.4, 0.8);",
    "glPushMatrix();",
    "glTranslatef(0, 2, 0);",
    "glScalef(0.8, 0.8, 0.8);",
    "tri();",
    "glPopMatrix();",
    "glColor3f(1, 1, 0.4);",
    "glPushMatrix();",
    "glRotatef(t*30, 0, 1, 0);",
    "tri();",
    "glPopMatrix();",
    NULL
};

/* Scratch-array demo - cubic Bezier evaluation via de Casteljau updates.
 * A/B/C hold the x/y/z control-point lanes while collapse() implements one
 * in-place interpolation step using ordinary expression math. */
static const char *const g_example_scratch_casteljau[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -8.0f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "glClearColor(0.07, 0.08, 0.12, 1);",
    "glEnable(GL_DEPTH_TEST);",
    "glDisable(GL_LIGHTING);",
    "glLineWidth(3);",
    "static float u;",
    "// collapse(dst, lo, hi, blend): collapse one Bezier edge in place.",
    "collapse(dst, lo, hi, blend) {",
        "A[dst] = A[lo] + (A[hi] - A[lo])*blend;",
        "B[dst] = B[lo] + (B[hi] - B[lo])*blend;",
        "C[dst] = C[lo] + (C[hi] - C[lo])*blend;",
    "}",
    "// Seed A/B/C with control points, then overwrite them with collapse().",
    "glColor3f(1.0, 0.55, 0.2);",
    "glBegin(GL_LINE_STRIP);",
    "for(i, 0, 48) {",
        "A[0] = -3.2;",
        "B[0] = -1.8;",
        "C[0] = -0.8;",
        "A[1] = -1.1 + 0.4*sin(t*0.9);",
        "B[1] = 2.4;",
        "C[1] = -0.1;",
        "A[2] = 1.0;",
        "B[2] = -2.1 + 0.5*cos(t*0.7);",
        "C[2] = 0.5;",
        "A[3] = 3.1;",
        "B[3] = 1.6;",
        "C[3] = 1.0 + 0.25*sin(t*0.5);",
        "u = i/48.0;",
        "collapse(0, 0, 1, u);",
        "collapse(1, 1, 2, u);",
        "collapse(2, 2, 3, u);",
        "collapse(0, 0, 1, u);",
        "collapse(1, 1, 2, u);",
        "collapse(0, 0, 1, u);",
        "glVertex3f(A[0], B[0], C[0]);",
    "}",
    "glEnd();",
    "",
    "// Rebuild the same control polygon from scratch-array state.",
    "A[0] = -3.2;",
    "B[0] = -1.8;",
    "C[0] = -0.8;",
    "A[1] = -1.1 + 0.4*sin(t*0.9);",
    "B[1] = 2.4;",
    "C[1] = -0.1;",
    "A[2] = 1.0;",
    "B[2] = -2.1 + 0.5*cos(t*0.7);",
    "C[2] = 0.5;",
    "A[3] = 3.1;",
    "B[3] = 1.6;",
    "C[3] = 1.0 + 0.25*sin(t*0.5);",
    "glColor3f(0.25, 0.45, 0.95);",
    "glBegin(GL_LINE_STRIP);",
    "glVertex3f(A[0], B[0], C[0]);",
    "glVertex3f(A[1], B[1], C[1]);",
    "glVertex3f(A[2], B[2], C[2]);",
    "glVertex3f(A[3], B[3], C[3]);",
    "glEnd();",
    "glPointSize(9);",
    "glColor3f(1.0, 0.9, 0.35);",
    "glBegin(GL_POINTS);",
    "glVertex3f(A[0], B[0], C[0]);",
    "glVertex3f(A[1], B[1], C[1]);",
    "glVertex3f(A[2], B[2], C[2]);",
    "glVertex3f(A[3], B[3], C[3]);",
    "glEnd();",
    NULL
};

/* Text annotation demo - pairs glRasterPos3f with label() so scene data can
 * carry live numeric readouts instead of geometry alone. */
static const char *const g_example_annotated_orbit_plot[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "static float n, r, x, y, phase, sample;",
    "glClearColor(0.06, 0.07, 0.09, 1);",
    "glDisable(GL_LIGHTING);",
    "glDisable(GL_DEPTH_TEST);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);",
    "glLineWidth(1.4);",
    "// Annotation demo: geometry plus live numeric labels.",
    "phase = fmod(t*0.2, 1);",
    "n = 72;",
    "for(r, 1, 4) {",
        "glColor4f(0.2, 0.35, 0.55, 0.45);",
        "glBegin(GL_LINE_LOOP);",
        "for(i, 0, n) {",
            "glVertex3f(cos(i*TAU/n)*r*0.6, sin(i*TAU/n)*r*0.6, 0);",
        "}",
        "glEnd();",
        "glRasterPos3f(r*0.6 + 0.08, 0, 0);",
        "label(\"r=%f\", r*0.6);",
    "}",
    "glColor4f(0.45, 0.5, 0.65, 0.45);",
    "glBegin(GL_LINES);",
    "for(i, 0, 12) {",
        "glVertex3f(0, 0, 0);",
        "glVertex3f(cos(i*TAU/12)*2.4, sin(i*TAU/12)*2.4, 0);",
    "}",
    "glEnd();",
    "glColor3f(1.0, 0.75, 0.25);",
    "glLineWidth(3);",
    "glBegin(GL_LINE_STRIP);",
    "for(i, 0, n+1) {",
        "sample = i/n;",
        "r = 1.0 + 0.5*sin(sample*TAU*3 + t);",
        "glVertex3f(cos(sample*TAU)*r, sin(sample*TAU)*r, 0);",
    "}",
    "glEnd();",
    "sample = phase;",
    "r = 1.0 + 0.5*sin(sample*TAU*3 + t);",
    "x = cos(sample*TAU)*r;",
    "y = sin(sample*TAU)*r;",
    "glPointSize(11);",
    "glColor3f(0.1, 0.9, 1.0);",
    "glBegin(GL_POINTS);",
    "glVertex3f(x, y, 0);",
    "glEnd();",
    "glColor3f(1.0, 1.0, 1.0);",
    "glRasterPos3f(-2.35, 2.35, 0);",
    "label(\"phase=%f\", phase);",
    "glRasterPos3f(x + 0.12, y + 0.12, 0);",
    "label(\"r=%f\", r);",
    "glRasterPos3f(-2.35, -2.35, 0);",
    "label(\"label text follows glRasterPos3f\");",
    NULL
};

/* 3D raster-text demo: a tiny orrery. Each planet is a glutSolidSphere lit by
 * the SOLAR light theme (light 0 at the world origin), sized to scale against
 * one another (Earth radius = 0.18 units; Mercury/Venus/Mars follow real
 * radius ratios). The sun is drawn unlit so it glows. Every body carries a
 * name label that tracks it through 3D — glRasterPos3f transforms each anchor
 * through the same modelview as the geometry, so the bitmap text follows the
 * moving spheres in depth rather than sitting in a flat HUD; a live %f readout
 * reports Earth's orbital phase. func0 draws one inclined orbit ring reused by
 * all four orbits. (The sun is NOT to scale — at ~109 Earth radii it would
 * dwarf the system.) */
static const char *const g_example_orrery[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// @cfg axes = AXES_THEME_OFF",
    "// @cfg grid = GRID_THEME_OFF",
    "// @cfg light_theme = LIGHT_THEME_SOLAR",
    "// @cfg backdrop = SCENE_BACKDROP_STARS",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -9.5f);",
    "glRotatef(28.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "static float incl, th, px, py, pz;",
    "OrbitRings(rad, tilt) {",
    "  glBegin(GL_LINE_LOOP);",
    "    for(i, 0, 64) {",
    "      glVertex3f(cos(i*TAU/64)*rad, sin(i*TAU/64)*rad*sin(tilt), sin(i*TAU/64)*rad*cos(tilt));",
    "    }",
    "  glEnd();",
    "}",
    "glClearColor(0.02, 0.02, 0.05, 1);",
    "glEnable(GL_NORMALIZE);",
    "// use cull face since we are using blending we want the effect to be view independent",
    "glEnable(GL_CULL_FACE);",
    "",
    "// the sun: drawn unlit so it glows (it sits on the SOLAR light at origin)",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE);",
    "glDisable(GL_DEPTH_TEST);",
    "glColor4f(1, 0.85, 0.3, 0.5);",
    "// Pulsate the sun's radius with two different frequencies to show it's alive.",
    "glutSolidSphere(0.5  + cos(2*t)*0.01, 24, 24);",
    "glutSolidSphere(0.45 + sin(t)*0.01, 24, 24);",
    "glEnable(GL_DEPTH_TEST);",
    "glutSolidSphere(0.4, 24, 24);",
    "glColor3f(1, 0.9, 0.5);",
    "glRasterPos3f(0.6, 0.55, 0);",
    "label(\"Sun\");",
    "",
    "// planets: lit by the central SOLAR light, color via glColor",
    "glEnable(GL_LIGHT0);",
    "glEnable(GL_COLOR_MATERIAL);",
    "// Mercury (0.38 Earth radii)",
    "incl = 0.18;",
    "th = t*1.6;",
    "px = cos(th)*1.3;",
    "py = sin(th)*1.3*sin(incl);",
    "pz = sin(th)*1.3*cos(incl);",
    "glEnable(GL_LIGHTING);",
    "glColor3f(0.7, 0.6, 0.5);",
    "glPushMatrix();",
    "  glTranslatef(px, py, pz);",
    "  glutSolidSphere(0.069, 16, 16);",
    "glPopMatrix();",
    "glDisable(GL_LIGHTING);",
    "glColor3f(0.9, 0.75, 0.6);",
    "glRasterPos3f(px + 0.12, py + 0.14, pz);",
    "label(\"Mercury\");",
    "// Venus (0.95 Earth radii)",
    "incl = 0.06;",
    "th = t*1.15 + 1.0;",
    "px = cos(th)*2.1;",
    "py = sin(th)*2.1*sin(incl);",
    "pz = sin(th)*2.1*cos(incl);",
    "glEnable(GL_LIGHTING);",
    "glColor3f(0.95, 0.8, 0.5);",
    "glPushMatrix();",
    "  glTranslatef(px, py, pz);",
    "  glutSolidSphere(0.171, 16, 16);",
    "glPopMatrix();",
    "glDisable(GL_LIGHTING);",
    "glColor3f(1, 0.9, 0.65);",
    "glRasterPos3f(px + 0.14, py + 0.16, pz);",
    "label(\"Venus\");",
    "// Earth (1.0, the reference radius)",
    "incl = 0.0;",
    "th = t*0.85 + 2.5;",
    "px = cos(th)*2.9;",
    "py = sin(th)*2.9*sin(incl);",
    "pz = sin(th)*2.9*cos(incl);",
    "glEnable(GL_LIGHTING);",
    "glColor3f(0.35, 0.55, 1);",
    "glPushMatrix();",
    "  glTranslatef(px, py, pz);",
    "  glutSolidSphere(0.18, 16, 16);",
    "glPopMatrix();",
    "glDisable(GL_LIGHTING);",
    "glColor3f(0.6, 0.8, 1);",
    "glRasterPos3f(px + 0.16, py + 0.18, pz);",
    "label(\"Earth\");",
    "// Mars (0.53 Earth radii)",
    "incl = 0.22;",
    "th = t*0.62 + 4.0;",
    "px = cos(th)*3.7;",
    "py = sin(th)*3.7*sin(incl);",
    "pz = sin(th)*3.7*cos(incl);",
    "glEnable(GL_LIGHTING);",
    "glColor3f(0.9, 0.45, 0.3);",
    "glPushMatrix();",
    "  glTranslatef(px, py, pz);",
    "  glutSolidSphere(0.096, 16, 16);",
    "glPopMatrix();",
    "glDisable(GL_LIGHTING);",
    "glColor3f(1, 0.6, 0.45);",
    "glRasterPos3f(px + 0.13, py + 0.15, pz);",
    "label(\"Mars\");",
    "// live readout: Earth's orbital phase, anchored in 3D below the system",
    "glColor3f(0.75, 0.8, 0.9);",
    "glRasterPos3f(-1.6, -3, 0);",
    "label(\"Earth phase = %f\", fmod(t*0.85 + 2.5, TAU));",
    "",
    "// faint orbit rings (unlit lines); func0 = one inclined ring",
    "glDisable(GL_LIGHTING);",
    "glColor3f(0.22, 0.24, 0.34);",
    "glLineWidth(1.2);",
    "OrbitRings(1.3, 0.18);",
    "OrbitRings(2.1, 0.06);",
    "OrbitRings(2.9, 0.0);",
    "OrbitRings(3.7, 0.22);",
    NULL
};

/* Torus knot: a single closed (p, q) curve winding p times around the
 * torus axis and q times through the hole, drawn as one GL_LINE_LOOP.
 * Per-vertex color sweeps the hue around the curve and drifts with t, so
 * a rainbow band flows along the knot. Pure trig in one for-loop. */
static const char *const g_example_torus_knot[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -9.0f);",
    "glRotatef(25.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "static float n, p, q, ang, rr, x, y, z; // samples, winds, angle, ring radius, coords",
    "glClearColor(0.05, 0.05, 0.08, 1.0);",
    "glLineWidth(2.0);",
    "n = 400;   // samples around the closed curve",
    "p = 2;     // turns around the torus axis",
    "q = 3;     // turns through the torus hole",
    "glBegin(GL_LINE_LOOP);",
    "  for(i, 0, n) {",
    "    ang = TAU * i/n;",
    "    rr = 2.0 + cos(q*ang);          // distance from the axis",
    "    x = rr * cos(p*ang);",
    "    y = rr * sin(p*ang);",
    "    z = sin(q*ang);",
    "    glColor3f(0.5 + 0.5*sin(ang + t), 0.5 + 0.5*sin(ang + t + 2.0), 0.5 + 0.5*sin(ang + t + 4.0));",
    "    glVertex3f(x, y, z);",
    "  }",
    "glEnd();",
    NULL
};

static const char *const g_example_whale[] = {
    "// @cfg grid = GRID_THEME_OCEAN",
    "// @cfg axes = AXES_THEME_OFF",
    "// @cfg light_theme = LIGHT_THEME_DEFAULT",
    "// @cfg normal_vectors = 0",
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// camera",
    "glTranslatef(0.0000f, 0.0000f, -6.5473f);",
    "glRotatef(20.6076f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(-114.3999f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.2893f, -0.0000f, -0.0242f);",
    "",
    "static float launchVelX, launchVelY, launchVelZ;",
    "static float currentVelY;",
    "static float particleLife, particleAge;",
    "static float dragDecay = 0.9;",
    "static float gravityY = -3.5;",
    "static float dragRate = 10;",
    "static float particleX, particleY, particleZ;",
    "static float floorY = 0;",
    "static float spawnDelay;",
    "static float emitDuration = 5.99568;",
    "static float fluke_ang, fin_ang;",
    "static float speed = 0.5;",
    "static float detail = 30;",
    "static float blowHoleX = 0.95, blowHoleY = 0.71, blowHoleZ;",
    "computeVerticalMotion(ageSeconds, launchY) {",
    "  // Velocity is linear in age: currentVelY = gravityY*ageSeconds + launchVelY.",
    "  // Position is its integral:",
    "  //   (gravityY/2)*ageSeconds^2 + launchVelY*ageSeconds + launchY",
    "  currentVelY = launchVelY + gravityY*ageSeconds;",
    "  particleY = launchY + gravityY/2 * ageSeconds * ageSeconds + launchVelY * ageSeconds;",
    "}",
    "computeLifespan(launchY) {",
    "  // Solve particleY(age) = floorY for age: how long the particle takes to fall",
    "  // from launchY to the floor. particleY is the projectile",
    "  //   (gravityY/2)*age^2 + launchVelY*age + (launchY - floorY) = 0",
    "  // a quadratic with a = gravityY/2, b = launchVelY, c = launchY - floorY, so",
    "  //   age = (-b - sqrt(b^2 - 4ac)) / 2a",
    "  // Substituting a = gravityY/2: 4ac = 2*gravityY*c and 2a = gravityY.",
    "  particleLife = (-launchVelY - sqrt(launchVelY*launchVelY - 2 * gravityY*(launchY - floorY))) / gravityY;",
    "}",
    "computeDriftX(ageSeconds, launchX) {",
    "  // Integral over [0, age] of the decaying horizontal velocity",
    "  //   velX(s) = launchVelX * dragDecay^(dragRate*s)",
    "  particleX = launchX + (launchVelX * pow(dragDecay, ageSeconds*dragRate) - launchVelX) / (dragRate*ln(dragDecay));",
    "}",
    "",
    "computeDriftZ(ageSeconds, launchZ) {",
    "  // Integral over [0, age] of the decaying horizontal velocity",
    "  //   velZ(s) = launchVelZ * dragDecay^(dragRate*s)",
    "  particleZ = launchZ + (launchVelZ * pow(dragDecay, ageSeconds*dragRate) - launchVelZ) / (dragRate*ln(dragDecay));",
    "}",
    "",
    "drawWhale(blowHoleX, blowHoleY, blowHoleZ) {",
    "  fluke_ang = sin(speed*t*TAU)* 30;",
    "  fin_ang = cos(speed*t*TAU)* 5;",
    "  detail = max(12, floor(detail));",
    "",
    "  // Shiny wet whale",
    "  glMaterialfv(GL_FRONT_AND_BACK, GL_SPECULAR, (GLfloat[]){0.2, 0.2, 0.2, 1});",
    "  glMaterialf(GL_FRONT_AND_BACK, GL_SHININESS, 100);",
    "",
    "  // Main body: elongated ellipsiod, dark blue-grey on top",
    "  glColor3f(0.24, 0.3, 0.4);",
    "",
    "  glPushMatrix();",
    "    glScalef(2, 0.85, 1.05);",
    "    glutSolidSphere(1, detail, detail);",
    "  glPopMatrix();",
    "",
    "  // Belly: lighter, sits just under the body so it shows the underside",
    "  glColor3f(0.72, 0.76, 0.78);",
    "  glPushMatrix();",
    "    glScalef(1.65, 0.45, 0.75);",
    "    glutSolidSphere(1, detail, detail);",
    "  glPopMatrix();",
    "",
    "  glColor3f(0.24, 0.3, 0.4);",
    "  glPushMatrix(); // begin tail",
    "    glTranslatef(-1.85, -0.2, 0);",
    "    glRotatef(fluke_ang/2, 0, 0, 1);",
    "",
    "    // Tail peduncle (narrow part before the flukes)",
    "    glPushMatrix();",
    "      glScalef(0.75, 0.3, 0.4);",
    "      glutSolidSphere(1, detail, detail);",
    "    glPopMatrix();",
    "",
    "    // Tail flukes -- two flat libes, animated with fluke_angle",
    "    glPushMatrix();",
    "      glTranslatef(-0.65, 0, 0);",
    "      glRotatef(fluke_ang, 0, 0, 1);",
    "      glPushMatrix();",
    "        glTranslatef(-0.1, 0, 0.55);",
    "        glRotatef(15, 0, 1, 0);",
    "        glScalef(0.35, 0.06, 0.65);",
    "        glutSolidSphere(1, detail, detail); // right fluke",
    "      glPopMatrix();",
    "      glPushMatrix();",
    "        glTranslatef(-0.1, 0, -0.55);",
    "        glRotatef(-15, 0, 1, 0);",
    "        glScalef(0.35, 0.06, 0.65);",
    "        glutSolidSphere(1, detail, detail); // left fluke",
    "      glPopMatrix();",
    "    glPopMatrix(); // end flukes",
    "  glPopMatrix(); // end tail",
    "",
    "  // Pectoral fins",
    "  glPushMatrix();",
    "    glRotatef(fin_ang, 0, 0, 1);",
    "    glRotatef(fin_ang/4, 0, 1, 0);",
    "",
    "    glPushMatrix();",
    "      glTranslatef(0.45, -0.25, 1);",
    "      glRotatef(25, 0, 1, 0);",
    "      glScalef(0.4, 0.08, 0.45);",
    "      glutSolidSphere(1, 14, 10); // right pectoral fin",
    "    glPopMatrix();",
    "",
    "    glPushMatrix();",
    "      glTranslatef(0.45, -0.25, -1);",
    "      glScalef(0.4, 0.08, 0.45);",
    "      glutSolidSphere(1, 14, 10); // left pectoral fin",
    "    glPopMatrix();",
    "  glPopMatrix(); // end fins",
    "",
    "  // Eyes",
    "  glDisable(GL_LIGHTING);",
    "  glColor3f(0.04, 0.04, 0.04);",
    "  glPushMatrix();",
    "    glTranslatef(1.45, 0.18, 0.63);",
    "    glutSolidSphere(0.07, 10, 8);",
    "    glTranslatef(0, 0, -1.26);",
    "    glutSolidSphere(0.07, 10, 8);",
    "  glPopMatrix();",
    "",
    "  // Blowhole",
    "  glColor3f(0.08, 0.08, 0.12);",
    "  glPushMatrix();",
    "    glTranslatef(blowHoleX, blowHoleY, blowHoleZ);",
    "    glScalef(0.15, 0.04, 0.1);",
    "    glutSolidSphere(1, 10, 8);",
    "  glPopMatrix();",
    "}",
    "",
    "glColor4f(0.25, 0.45, 0.85, 0.46);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE);",
    "glEnable(GL_DEPTH_TEST);",
    "glDepthFunc(GL_ALWAYS);",
    "glPointSize(10);",
    "",
    "if(t > 2*emitDuration) {",
    "  t = 0;",
    "}",
    "",
    "glBegin(GL_POINTS);",
    "  for(i, 0, 350) {",
    "    launchVelX = 3 * rand2(i,1);",
    "    launchVelY = 2 + 2 * rand(i, 2);",
    "    launchVelZ = 3 * rand2(i, 3);",
    "",
    "    computeLifespan(blowHoleY);",
    "    spawnDelay = 3 * rand(i,4);",
    "",
    "    if((t - spawnDelay) > 0 && ( t <= ceil(emitDuration/particleLife)*particleLife + spawnDelay)) {",
    "      particleAge = fmod(t - spawnDelay, particleLife);",
    "",
    "      computeDriftX(particleAge, blowHoleX + 0.1 + rand2(i, 5) * 0.05);",
    "      computeVerticalMotion(particleAge, blowHoleY);",
    "      computeDriftZ(particleAge, blowHoleZ+ rand2(i, 6) * 0.05);",
    "",
    "      glVertex3f(particleX, particleY, particleZ);",
    "",
    "    }",
    "  }",
    "glEnd();",
    "",
    "glDepthFunc(GL_LESS);",
    "",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "glDisable(GL_BLEND);",
    "",
    "glEnable(GL_LIGHT0);",
    "glEnable(GL_LIGHT1);",
    "",
    "glEnable(GL_LIGHTING);",
    "",
    "drawWhale(blowHoleX, blowHoleY, blowHoleZ);",
    NULL
};

typedef unsigned int ReplExampleTagMask;

typedef struct {
    const char *name;
    const char *const *lines;
    ReplExampleTagMask tags;
    /* Optional in-flyout section subheading. Free-form display string
     * (e.g. "Basics", "Functions") — the Scene menu groups consecutive
     * examples sharing the same subheading under a chrome `### subheading`
     * header. NULL = no header. Convention enforced by
     * test_example_subheading_metadata: per tag, each non-NULL subheading
     * must appear in a single contiguous run — interleaving causes
     * duplicate headers. */
    const char *subheading;
} ReplExampleEntry;

/* REPL_EXAMPLE_TAG_ALL is a synthetic tag: every example is a member.
 * It is not listed in any g_example_entries[] mask literal; instead
 * repl_example_tag_mask() ORs its bit into every example's mask, so the
 * whole tag query API (has_tag / count_for_tag / index_for_tag /
 * visible_tag_*) — and therefore the Scene menu's "All" group and the
 * F12 cycle — pick it up with no per-entry bookkeeping. Kept at index 0
 * so "All" sorts first under "### EXAMPLES". Enum lives in examples.h. */

#define EXAMPLE_TAG_BIT(tag) (1u << (tag))
#define EXAMPLE_TAG_ALL      EXAMPLE_TAG_BIT(REPL_EXAMPLE_TAG_ALL)
#define EXAMPLE_TAG_2D       EXAMPLE_TAG_BIT(REPL_EXAMPLE_TAG_2D)
#define EXAMPLE_TAG_3D       EXAMPLE_TAG_BIT(REPL_EXAMPLE_TAG_3D)
#define EXAMPLE_TAG_POLYGONS EXAMPLE_TAG_BIT(REPL_EXAMPLE_TAG_POLYGONS)
#define EXAMPLE_TAG_LINES    EXAMPLE_TAG_BIT(REPL_EXAMPLE_TAG_LINES)

static const char *const g_example_tag_labels[] = {
    "All",
    "2D",
    "3D",
    "Polygons",
    "Lines",
};
/* Must stay 1:1 with the REPL_EXAMPLE_TAG_* enum: repl_example_tag_count()
 * returns REPL_EXAMPLE_TAG_COUNT but repl_example_tag_label() indexes this
 * table, so any drift is an out-of-bounds read. */
STATIC_ASSERT((int)(sizeof(g_example_tag_labels) /
                    sizeof(g_example_tag_labels[0])) == REPL_EXAMPLE_TAG_COUNT,
              "g_example_tag_labels[] out of sync with REPL_EXAMPLE_TAG_COUNT");

/* Catalog order matters: the Scene menu groups consecutive same-subheading
 * entries into one `### subheading` header per per-tag flyout, so each
 * subheading must run contiguously within every tag it surfaces under.
 * test_example_subheading_metadata enforces this — see the per-tag walk
 * notes in g_example_tag_labels above. Lit cube intentionally stays first
 * (F12's default scene). */
static const ReplExampleEntry g_example_entries[] = {
    { "Lit cube", g_example_cube,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Basics" },
    { "2D assignment sketch (vars only)", g_example_assign_2d,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Basics" },
    { "Animated ring (for + t)", g_example_ring,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_LINES,
      "Basics" },
    { "Conditional colors (if + t)", g_example_cond,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Basics" },

    { "Function demo (named func)", g_example_func,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Functions" },
    { "Function polygons (args + for)", g_example_func_loop,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_POLYGONS,
      "Functions" },
    { "Function branching (args + if)", g_example_func_if,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_POLYGONS,
      "Functions" },
    { "Recursive triangle tree (func + recursion)", g_example_func_recurse,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Functions" },

    { "Parametric torus (nested for)", g_example_torus,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Curves & surfaces" },
    { "Animated wave surface (analytic normals)", g_example_waves,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Curves & surfaces" },
    { "Procedural terrain (rand grid + sin ripple)", g_example_random_surface,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Curves & surfaces" },
    { "Animated spirograph curve", g_example_spirograph_curve,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Curves & surfaces" },
    { "Traveling ripple ring", g_example_traveling_ripple_ring,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Curves & surfaces" },
    { "Bezier curve with guides", g_example_bezier,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Curves & surfaces" },
    { "Scratch arrays (de Casteljau curve)", g_example_scratch_casteljau,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Curves & surfaces" },
    { "Torus knot (animated)", g_example_torus_knot,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_LINES,
      "Curves & surfaces" },

    { "Glow sprites (blend + point attenuation)", g_example_glow_particles,
      EXAMPLE_TAG_3D,
      "Effects" },
    { "Snowfall demo (550 particles)", g_example_snowfall,
      EXAMPLE_TAG_3D,
      "Effects" },
    { "Swaying grass field (rand + t)", g_example_grass_field,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Effects" },
    { "Transform stress (translate/rotate/scale guides)", g_example_xform_stress,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_LINES,
      "Effects" },

    { "GLU tessellator (concave arrow)", g_example_tess,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Tessellation" },
    { "GLU tessellator (concave arrow cutout)", g_example_tess_cutout,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Tessellation" },

    { "Stress test (all features)", g_example_stress,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS | EXAMPLE_TAG_LINES,
      "Showcase" },
    { "Annotated orbit plot (labels)", g_example_annotated_orbit_plot,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_LINES,
      "Showcase" },
    { "Orrery (labels track 3D orbits)", g_example_orrery,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_LINES,
      "Showcase" },
    { "Whale (particle system + lit model)", g_example_whale,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Showcase" },
};

static int example_catalog_entry_count(void) {
    return repl_example_count();
}

static int example_catalog_tag_count(void) {
    return REPL_EXAMPLE_TAG_COUNT;
}

static unsigned int example_catalog_tag_bit(int tag_idx) {
    return repl_example_tag_bit(tag_idx);
}

static const ReplCatalogTagOps g_example_tag_ops = {
    example_catalog_entry_count,
    example_catalog_tag_count,
    g_example_tag_labels,
    repl_example_tag_mask,
    example_catalog_tag_bit,
};

int repl_example_count(void) {
    return (int)(sizeof(g_example_entries) / sizeof(g_example_entries[0]));
}

const char *repl_example_name(int idx) {
    if (idx < 0 || idx >= repl_example_count())
        return NULL;
    return g_example_entries[idx].name;
}

const char *const *repl_example_lines(int idx) {
    if (idx < 0 || idx >= repl_example_count())
        return NULL;
    return g_example_entries[idx].lines;
}

int repl_example_tag_count(void) {
    return REPL_EXAMPLE_TAG_COUNT;
}

unsigned int repl_example_tag_mask(int example_idx) {
    if (example_idx < 0 || example_idx >= repl_example_count())
        return 0u;
    /* Fold in the synthetic "All" membership so every tag query derives
     * it uniformly; entry literals stay free of an explicit ALL bit. */
    return g_example_entries[example_idx].tags | EXAMPLE_TAG_ALL;
}

REPL_DEFINE_CATALOG_TAG_WRAPPERS(example, &g_example_tag_ops)

const char *repl_example_subheading(int example_idx) {
    if (example_idx < 0 || example_idx >= repl_example_count())
        return NULL;
    return g_example_entries[example_idx].subheading;
}
