#include <math.h>
#include "repl/examples.h"
#include "repl/catalog_tags.h"

#include <stddef.h>
#include "c_compat.h"   /* STATIC_ASSERT (C99/C11 portable) */

/* Each example is an array of source lines terminated by NULL.
 * Lines are processed sequentially:
 *   "for(...) {"  -> CMD_FOR_BEGIN + CMD_FOR_END, enters block
 *   "funcN {"     -> CMD_FUNC_DEF + CMD_FUNC_END, enters block
 *   "if(...) {"   -> CMD_IF_BEGIN + CMD_IF_END, enters block
 *   "}"           -> closes current block
 *   "x = expr;"   -> CMD_VAR_ASSIGN
 *   "funcN()"     -> CMD_CALL
 *   anything else -> parse_command() as a regular GL command
 *
 * Predefined examples can optionally start with contiguous scene-presentation
 * config metadata lines using the exported-file format:
 *   "// @cfg axes = AXES_THEME_COMPASS"
 *   "// @cfg vertex_outlines = 0"
 * Supported slugs are limited to visual scene settings such as wireframe,
 * grid, axes, vertex overlays, backdrop, and camera_rotate. These metadata
 * lines are consumed by the example loader and are not shown in the code panel.
 *
 * A camera preset may then follow immediately after the cfg lines:
 *   "// camera"
 *   "glTranslatef(0.0f, 0.0f, -dist);"
 *   "glRotatef(rx, 1.0f, 0.0f, 0.0f);"
 *   "glRotatef(ry, 0.0f, 1.0f, 0.0f);"
 *   "glTranslatef(-tx, -ty, -tz);"
 * Both cfg and camera metadata are consumed by the example loader and are not
 * shown in the code panel.
 */

/* ===========================================================================
 * Example scene color language -- the "Dusk" palette
 *
 * The built-in example scenes share one coherent palette so the set reads as a
 * designed family instead of a grab-bag of saturated primaries. The rollout
 * began with the Scene menu "2D" tag and now also covers the line/surface 3D
 * scenes (animated ring, animated wave surface, GLU tessellator + cutout,
 * transform stress); extend it to the rest of the catalog as they are touched.
 * Each covered scene clears to the same deep cool ink and draws geometry from
 * this curated accent set (mid-bright, lightly desaturated -- harmonious, not
 * garish). glClearColor channels are capped at REPL_CLEAR_COLOR_MAX_V (0.1f)
 * so the canvas always stays dark; the accents below are full-range glColor.
 *
 *   Canvas (clear)   0.05 0.06 0.08   deep cool ink (all channels <= 0.1 cap)
 *   CORAL  warm key  0.98 0.46 0.36
 *   AMBER  gold      0.98 0.76 0.36
 *   ROSE   pink      0.95 0.44 0.66
 *   VIOLET purple    0.62 0.52 0.95
 *   AZURE  sky key   0.36 0.70 0.98
 *   TEAL   aqua      0.30 0.84 0.80
 *   MIST   neutral   0.92 0.95 0.98
 *
 * Procedural color sweeps lerp between two anchors: color = A + (B-A)*s, with
 * s in [0,1]. The signature ramp is CORAL->AZURE (warm to cool); a few scenes
 * use VIOLET->AZURE or an AMBER accent for variety while staying in family.
 * Flat-colored discrete sets (triangle trios, transform groups, tess stops)
 * pick distinct palette members. When touching these colors keep the whole
 * covered set on this palette.
 * ========================================================================= */

/* Lit cube (default) */
static const char *const g_example_cube[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(20.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(35.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glShadeModel(GL_SMOOTH);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "//glEnable(GL_LINE_SMOOTH);",
    "glColor3f(1, 1, 1);",
    "glBegin(GL_QUAD_STRIP);",
    "glNormal3f(0, 1, 0);",
    "glVertex3f(1, 1, 1);",
    "glNormal3f(0, 1, 0);",
    "glVertex3f(-1, 1, 1);",
    "glNormal3f(0, 0, 1);",
    "glVertex3f(1, -1, 1);",
    "glNormal3f(0, 0, 1);",
    "glVertex3f(-1, -1, 1);",
    "glNormal3f(-0, -1, -0);",
    "glVertex3f(1, -1, -1);",
    "glNormal3f(-0, -1, -0);",
    "glVertex3f(-1, -1, -1);",
    "glNormal3f(0, 0, -1);",
    "glVertex3f(1, 1, -1);",
    "glNormal3f(0, 0, -1);",
    "glVertex3f(-1, 1, -1);",
    "glNormal3f(0, 1, -0);",
    "glVertex3f(1, 1, 1);",
    "glNormal3f(0, 1, -0);",
    "glVertex3f(-1, 1, 1);",
    "glEnd();",
    NULL
};

/* Animated ring - for-loop + t variable */
static const char *const g_example_ring[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(24.5000f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(43.7235f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "glClearColor(0.05, 0.06, 0.08, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glBegin(GL_LINE_LOOP);",
    "for(i, 0, 48) {",
        "glColor3f(0.98 - 0.62*(sin(i*TAU/48)*0.5+0.5), 0.46 + 0.24*(sin(i*TAU/48)*0.5+0.5), 0.36 + 0.62*(sin(i*TAU/48)*0.5+0.5));",
        "glVertex3f(cos(i*TAU/48+t)*2, sin(i*TAU/48+t)*2, sin(i*TAU/12+t)*0.5);",
    "}",
    "glEnd();",
    "glBegin(GL_TRIANGLE_FAN);",
    "glColor3f(0.92, 0.95, 0.98);",
    "glVertex3f(0, 0, 0);",
    "for(i, 0, 25) {",
        "glColor3f(0.98 - 0.62*(sin(i*TAU/24+t)*0.5+0.5), 0.46 + 0.24*(sin(i*TAU/24+t)*0.5+0.5), 0.36 + 0.62*(sin(i*TAU/24+t)*0.5+0.5));",
        "glVertex3f(cos(i*TAU/24)*1.5, sin(i*TAU/24)*1.5, 0);",
    "}",
    "glEnd();",
    NULL
};

/* Function demo - define a named reusable function (alias for a
 * funcN slot), call it repeatedly with transforms between calls. */
static const char *const g_example_func[] = {
    "// @cfg view_mode = RENDER3D_VIEW_2D",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -3.0f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "// @cfg vertex_points = 0",
    "glClearColor(0.05, 0.06, 0.08, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "triangle() {",
        "glBegin(GL_TRIANGLES);",
        "glNormal3f(0, 0, 1);",
        "glVertex3f(0, 0.8, 0);",
        "glVertex3f(-0.7, -0.4, 0);",
        "glVertex3f(0.7, -0.4, 0);",
        "glEnd();",
    "}",
    "glColor3f(0.98, 0.46, 0.36);",
    "triangle();",
    "glTranslatef(2, 0, 0);",
    "glColor3f(0.30, 0.84, 0.80);",
    "triangle();",
    "glTranslatef(-4, 0, 0);",
    "glColor3f(0.62, 0.52, 0.95);",
    "triangle();",
    NULL
};

/* Parametric polygon helper - function args driving local for-loops */
static const char *const g_example_func_loop[] = {
    "// @cfg view_mode = RENDER3D_VIEW_2D",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -4.0f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "glClearColor(0.05, 0.06, 0.08, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "polygon(radius, sides, phase) {",
        "glBegin(GL_TRIANGLE_FAN);",
        "glNormal3f(0, 0, 1);",
        "glColor3f(0.92, 0.95, 0.98);",
        "glVertex3f(0, 0, 0);",
        "for(i, 0, sides + 1) {",
            "glColor3f(0.98 - 0.62*(sin(i*TAU/sides + phase)*0.5+0.5), 0.46 + 0.24*(sin(i*TAU/sides + phase)*0.5+0.5), 0.36 + 0.62*(sin(i*TAU/sides + phase)*0.5+0.5));",
            "glVertex3f(cos(i*TAU/sides + phase)*radius, sin(i*TAU/sides + phase)*radius, 0);",
        "}",
        "glEnd();",
    "}",
    "glPushMatrix();",
    "glTranslatef(-2.4, 0, 0);",
    "polygon(0.9, 3, t*0.4);",
    "glPopMatrix();",
    "glPushMatrix();",
    "polygon(0.9, 6, -t*0.25);",
    "glPopMatrix();",
    "glPushMatrix();",
    "glTranslatef(2.4, 0, 0);",
    "polygon(0.9, 10, t*0.15);",
    "glPopMatrix();",
    NULL
};

/* Branching helper - function args driving local if-blocks */
static const char *const g_example_func_if[] = {
    "// @cfg view_mode = RENDER3D_VIEW_2D",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -4.0f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "glClearColor(0.05, 0.06, 0.08, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "shape(scale, phase) {",
        "if(scale > 1) {",
            "glColor3f(0.98, 0.46, 0.36);",
            "glBegin(GL_QUADS);",
            "glNormal3f(0, 0, 1);",
            "glVertex3f(-0.7*scale, -0.7*scale, 0);",
            "glVertex3f(0.7*scale, -0.7*scale, 0);",
            "glVertex3f(0.7*scale, 0.7*scale, 0);",
            "glVertex3f(-0.7*scale, 0.7*scale, 0);",
            "glEnd();",
        "}",
        "if(scale <= 1) {",
            "glColor3f(0.36, 0.70, 0.98);",
            "glBegin(GL_TRIANGLES);",
            "glNormal3f(0, 0, 1);",
            "glVertex3f(cos(phase)*0.9*scale, sin(phase)*0.9*scale, 0);",
            "glVertex3f(cos(phase+TAU/3)*0.9*scale, sin(phase+TAU/3)*0.9*scale, 0);",
            "glVertex3f(cos(phase+2*TAU/3)*0.9*scale, sin(phase+2*TAU/3)*0.9*scale, 0);",
            "glEnd();",
        "}",
    "}",
    "glPushMatrix();",
    "glTranslatef(-2.2, 0, 0);",
    "shape(0.9, t);",
    "glPopMatrix();",
    "glPushMatrix();",
    "shape(1.4, t*0.5);",
    "glPopMatrix();",
    "glPushMatrix();",
    "glTranslatef(2.2, 0, 0);",
    "shape(0.65, -t*0.8);",
    "glPopMatrix();",
    NULL
};

/* Recursive helper - transformed child calls with depth countdown */
static const char *const g_example_func_recurse[] = {
    "// @cfg view_mode = RENDER3D_VIEW_2D",
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "glClearColor(0.05, 0.06, 0.08, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "// Recursive triangle tree: child calls shrink and rotate from the parent",
    "branch(depth, size, spin) {",
        "glColor3f(0.62 - 0.065*depth, 0.52 + 0.045*depth, 0.95 + 0.0075*depth);",
        "glBegin(GL_LINE_LOOP);",
        "glNormal3f(0, 0, 1);",
        "glVertex3f(0, size, 0);",
        "glVertex3f(-0.866*size, -0.5*size, 0);",
        "glVertex3f(0.866*size, -0.5*size, 0);",
        "glEnd();",
        "if(depth <= 0) {",
            "glColor3f(0.98, 0.76, 0.36);",
            "glBegin(GL_TRIANGLES);",
            "glNormal3f(0, 0, 1);",
            "glVertex3f(0, size*0.55, 0);",
            "glVertex3f(-0.48*size, -0.25*size, 0);",
            "glVertex3f(0.48*size, -0.25*size, 0);",
            "glEnd();",
        "}",
        "if(depth > 0) {",
            "glPushMatrix();",
            "glTranslatef(0, size*1.02, 0);",
            "glRotatef(18 + spin*14, 0, 0, 1);",
            "branch(depth - 1, size*0.62, spin + 0.15);",
            "glPopMatrix();",
            "glPushMatrix();",
            "glTranslatef(-size*0.9, -size*0.38, 0);",
            "glRotatef(-30 - spin*12, 0, 0, 1);",
            "branch(depth - 1, size*0.58, spin + 0.12);",
            "glPopMatrix();",
            "glPushMatrix();",
            "glTranslatef(size*0.9, -size*0.38, 0);",
            "glRotatef(30 + spin*12, 0, 0, 1);",
            "branch(depth - 1, size*0.58, spin + 0.12);",
            "glPopMatrix();",
        "}",
    "}",
    "glRotatef(sin(t*0.35)*12, 0, 0, 1);",
    "branch(4, 1.05, sin(t*0.4));",
    NULL
};

/* Conditional colors - if-blocks + t variable */
static const char *const g_example_cond[] = {
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(20.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(35.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glBegin(GL_QUADS);",
    "if(sin(t) > 0) {",
        "glColor3f(1, 0.2, 0.2);",
    "} else {",
        "glColor3f(0.2, 0.2, 1);",
    "}",
    "glNormal3f(0, 0, 1);",
    "glVertex3f(-1, -1, 0);",
    "glVertex3f(1, -1, 0);",
    "glVertex3f(1, 1, 0);",
    "glVertex3f(-1, 1, 0);",
    "if(cos(t) > 0) {",
        "glColor3f(0.2, 1, 0.2);",
    "} else {",
        "glColor3f(1, 1, 0.2);",
    "}",
    "glNormal3f(0, 0, -1);",
    "glVertex3f(-1, -1, -1);",
    "glVertex3f(-1, 1, -1);",
    "glVertex3f(1, 1, -1);",
    "glVertex3f(1, -1, -1);",
    "glEnd();",
    NULL
};

/* Parametric torus - nested for-loops.
 * Standard parametrization:
 *   P(u, v) = ((R + r*cos v) * cos u,
 *              (R + r*cos v) * sin u,
 *              r * sin v)
 * with u sweeping the major (ring) angle and v the minor (tube) angle. */
static const char *const g_example_torus[] = {
    "// @cfg vertex_labels = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -8.0f);",
    "glRotatef(20.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(35.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "static float R = 2;  // major radius (ring center to tube center)",
    "static float r = 1;  // minor radius (tube thickness)",
    "static float n = 24; // segment count around both u and v",
    "static float u, v;   // current major/minor angles",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "//glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "glShadeModel(GL_SMOOTH);",
    "n = floor(n); // keep an an integer",
    "n = min(25, max(n, 3)); // clamp to reasonable range",
    "for(i, 0, n) {",
        "glBegin(GL_QUAD_STRIP);",
        "for(j, 0, n+1) {",
            "// step v across the tube; emit two vertices, one at u=i and one at u=i+1",
            "v = j*TAU/n;",
            "u = i*TAU/n;",
            "glColor3f(sin(u)*0.4+0.6, cos(v)*0.4+0.6, 0.5);",
            "glVertex3f((R + r*cos(v))*cos(u), (R + r*cos(v))*sin(u), r*sin(v));",
            "u = (i+1)*TAU/n;",
            "glVertex3f((R + r*cos(v))*cos(u), (R + r*cos(v))*sin(u), r*sin(v));",
        "}",
        "glEnd();",
    "}",
    NULL
};

/* GLU tessellator - concave arrow polygon with per-vertex color */
static const char *const g_example_tess[] = {
    "// @cfg grid = GRID_THEME_TRON",
    "// @cfg grid_brightness = GRID_BRIGHTNESS_DIM",
    "// @cfg light_theme = LIGHT_THEME_HEADLIGHT",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(10.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(15.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "glClearColor(0.05, 0.06, 0.08, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "glEnable(GL_LIGHT0);",
    "glShadeModel(GL_SMOOTH);",
    "glFrontFace(GL_CW);",
    "// Arrow shape - concave, tessellated with per-vertex color",
    "gluBegin(GLU_POLYGON);",
    "gluBegin(GLU_CONTOUR);",
    "gluNormal(0, 0, 1);",
    "gluColor(0.36, 0.70, 0.98, 1);",
    "gluVertex(-1.2, -0.45, 0);",
    "gluColor(0.36, 0.70, 0.98, 1);",
    "gluVertex(-1.2, 0.45, 0);",
    "gluColor(0.62, 0.52, 0.95, 1);",
    "gluVertex(0, 0.45, 0);",
    "gluColor(0.98, 0.46, 0.36, 1);",
    "gluVertex(0, 1.1, 0);",
    "gluColor(0.98, 0.76, 0.36, 1);",
    "gluVertex(1.3, 0, 0);",
    "gluColor(0.98, 0.46, 0.36, 1);",
    "gluVertex(0, -1.1, 0);",
    "gluColor(0.62, 0.52, 0.95, 1);",
    "gluVertex(0, -0.45, 0);",
    "gluEnd();",
    "gluEnd();",
    NULL
};

/* GLU tessellator - concave arrow polygon cutout */
static const char *const g_example_tess_cutout[] = {
    "// @cfg grid = GRID_THEME_TRON",
    "// @cfg grid_brightness = GRID_BRIGHTNESS_DIM",
    "// @cfg light_theme = LIGHT_THEME_HEADLIGHT",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -6.0f);",
    "glRotatef(10.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(15.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "static float z;",
    "glClearColor(0.05, 0.06, 0.08, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "glEnable(GL_LIGHT0);",
    "glShadeModel(GL_SMOOTH);",
    "glFrontFace(GL_CW);",
    "z = -0.55;",
    "glRotatef(10*t, 0, 0, 1);",
    "// glScalef(0.5, 0.5, 0.5);",
    "// Arrow shape - concave, tessellated with per-vertex color",
    "gluBegin(GLU_POLYGON);",
    "  gluBegin(GLU_CONTOUR);",
    "    glBegin(GL_QUAD_STRIP);",
    "    gluNormal(0, 0, 1);",
    "  // Side 0",
    "    gluColor(0.36, 0.70, 0.98, 1);",
    "      glColor3f(0.36, 0.70, 0.98);",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(-1.2, -0.45, 0);",
    "      glVertex3f(-1.2, -0.45, z);",
    "    gluVertex(-1.2, -0.45, 0);",
    "  // Side 1",
    "    gluColor(0.36, 0.70, 0.98, 1);",
    "      glColor3f(0.36, 0.70, 0.98);",
    "      glNormal3f(0, 1, 0);",
    "      glVertex3f(-1.2, 0.45, 0);",
    "      glVertex3f(-1.2, 0.45, z);",
    "    gluVertex(-1.2, 0.45, 0);",
    "  // Side 2",
    "    gluColor(0.62, 0.52, 0.95, 1);",
    "      glColor3f(0.62, 0.52, 0.95);",
    "      glNormal3f(-1, 1, 0);",
    "      glVertex3f(0, 0.45, 0);",
    "      glVertex3f(0, 0.45, z);",
    "    gluVertex(0, 0.45, 0);",
    "  // Side 3",
    "    gluColor(0.98, 0.46, 0.36, 1);",
    "      glColor3f(0.98, 0.46, 0.36);",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(0, 1.1, 0);",
    "      glVertex3f(0, 1.1, z);",
    "    gluVertex(0, 1.1, 0);",
    "  // Side 4",
    "    gluColor(0.98, 0.76, 0.36, 1);",
    "      glColor3f(0.98, 0.76, 0.36);",
    "      glNormal3f(1, 0, 0);",
    "      glVertex3f(1.3, 0, 0);",
    "      glVertex3f(1.3, 0, z);",
    "    gluVertex(1.3, 0, 0);",
    "  // Side 5",
    "    gluColor(0.98, 0.46, 0.36, 1);",
    "      glColor3f(0.98, 0.46, 0.36);",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(0, -1.1, 0);",
    "      glVertex3f(0, -1.1, z);",
    "    gluVertex(0, -1.1, 0);",
    "  // Side 6",
    "    gluColor(0.62, 0.52, 0.95, 1);",
    "      glColor3f(0.62, 0.52, 0.95);",
    "      glNormal3f(-1, -1, 0);",
    "      glVertex3f(0, -0.45, 0);",
    "      glVertex3f(0, -0.45, z);",
    "    gluVertex(0, -0.45, 0);",
    "  // Quade side 7",
    "      glColor3f(0.36, 0.70, 0.98);",
    "      glNormal3f(0, -1, 0);",
    "      glVertex3f(-1.2, -0.45, 0);",
    "      glVertex3f(-1.2, -0.45, z);",
    "    glEnd();",
    "  gluEnd();",
    "  gluBegin(GLU_CONTOUR);",
    "    glBegin(GL_QUAD_STRIP);",
    "      glColor3f(0.45, 0.49, 0.58);",
    "    gluNormal(0, 0, 1);",
    "  // Side 0",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(-0.6, -0.225, 0);",
    "      glVertex3f(-0.6, -0.225, z);",
    "    gluVertex(-0.6, -0.225, 0);",
    "  // Side 1",
    "      glNormal3f(0, 1, 0);",
    "      glVertex3f(-0.6, 0.225, 0);",
    "      glVertex3f(-1.2/2, 0.45/2, z);",
    "    gluVertex(-0.6, 0.225, 0);",
    "  // Side 2",
    "      glNormal3f(-1, 1, 0);",
    "      glVertex3f(0.2, 0.225, 0);",
    "      glVertex3f(0.2, 0.45/2, z);",
    "    gluVertex(0.2, 0.225, 0);",
    "  // Side 3",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(0.2, 0.55, 0);",
    "      glVertex3f(0.2, 1.1/2, z);",
    "    gluVertex(0.2, 0.55, 0);",
    "  // Side 4",
    "      glNormal3f(1, 0, 0);",
    "      glVertex3f(0.85, 0, 0);",
    "      glVertex3f(1.7/2, 0, z);",
    "    gluVertex(0.85, 0, 0);",
    "  // Side 5",
    "      glNormal3f(-1, 0, 0);",
    "      glVertex3f(0.2, -0.55, 0);",
    "      glVertex3f(0.2, -1.1/2, z);",
    "    gluVertex(0.2, -0.55, 0);",
    "  // Side 6",
    "      glNormal3f(-1, -1, 0);",
    "      glVertex3f(0.2, -0.225, 0);",
    "      glVertex3f(0.2, -0.45/2, z);",
    "    gluVertex(0.2, -0.225, 0);",
    "  // Quad side 7",
    "      glNormal3f(0, -1, 0);",
    "      glVertex3f(-0.6, -0.225, 0);",
    "      glVertex3f(-1.2/2, -0.45/2, z);",
    "    glEnd();",
    "  gluEnd();",
    "gluEnd();",
    NULL
};

/* 2D assignment sketch - runtime assignment without goto.
 * No predefined goto examples are shipped because goto support is partial:
 * top-level only, not replay-safe, and not suitable for variable-driven
 * geometry loops. Keep coverage in tests/docs instead of F12 examples. */
static const char *const g_example_assign_2d[] = {
    "// @cfg view_mode = RENDER3D_VIEW_2D",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -2.5f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "static float x, y;",
    "glClearColor(0.05, 0.06, 0.08, 1.0);",
    "// 2D assignment sketch: tests runtime variable assignment without goto",
    "glDisable(GL_LIGHTING);",
    "x = -1.7;",
    "glBegin(GL_LINE_STRIP);",
    "for(i, 0, 48) {",
    "  x = x + 0.07;",
    "  y = sin(x*2.5 + t)*0.52 + cos(i*0.25 + t*0.6)*0.16;",
    "  glColor3f(0.98 - 0.62*(i/47.0), 0.46 + 0.24*(i/47.0), 0.36 + 0.62*(i/47.0));",
    "  glVertex3f(x, y, 0);",
    "}",
    "glEnd();",
    NULL
};

/* Additive glow particles - glPointSize + distance attenuation + blend */
static const char *const g_example_glow_particles[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg grid = GRID_THEME_EMBER",
    "// @cfg grid_extent = GRID_EXTENT_MID",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -5.0f);",
    "glRotatef(15.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(10.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "static float radius, angle, x, y, z; // per-particle: orbit radius, base angle, world pos",
    "static float count = 160;       // number of glow points",
    "static float radMin = 0.4;      // nearest orbital radius (xz plane)",
    "static float radSpan = 1.8;     // additional radius range; radius in [radMin, radMin+radSpan]",
    "static float orbitRate = 0.4;   // angular speed of the xz orbit (animates with t)",
    "static float yWobbleFreq = 1.3; // y wobble frequency relative to the base angle",
    "static float yWobbleRate = 0.6; // y wobble time-rate (animates with t)",
    "static float yAmp = 0.9;        // y wobble amplitude",
    "glClearColor(0.1, 0.1, 0.1, 1.0);",
    "// Glow sprites: additive blend + distance-attenuated point size.",
    "// Each particle orbits in xz at (radius, angle) while y wobbles independently.",
    "glDisable(GL_LIGHTING);",
    "glDisable(GL_DEPTH_TEST);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE);",
    "glEnable(GL_POINT_SMOOTH);",
    "glPointSize(24);",
    "glPointParameterfv(GL_POINT_DISTANCE_ATTENUATION, 0.2, 0, 0.15);",
    "glBegin(GL_POINTS);",
    "for(i, 0, count) {",
    "  angle = rand(i, 0)*TAU;                  // random base angle in [0, TAU)",
    "  radius = radMin + rand(i, 1)*radSpan;    // random radius in the configured range",
    "  x = cos(angle + t*orbitRate)*radius;",
    "  y = sin(angle*yWobbleFreq + t*yWobbleRate)*yAmp;",
    "  z = sin(angle + t*orbitRate)*radius;",
    "  // per-particle base color: rand seeds 2/3/4 keep r/g/b stable across frames",
    "  glColor4f(0.4 + 0.6*rand(i, 2), 0.3 + 0.5*rand(i, 3), 0.8 + 0.2*rand(i, 4), 0.55);",
    "  glVertex3f(x, y, z);",
    "}",
    "glEnd();",
    NULL
};

/* Animated wave surface - y = sin(freq*x + t)*cos(freq*z + zPhase*t)*amp
 * rendered as GL_TRIANGLE_STRIP rows. Normals are the exact analytic partial
 * derivatives of the wave function (no finite-difference approximation), giving
 * correct smooth lighting across all four lights. Per-vertex color varies with
 * position and t for a shifting iridescent look. */

static const char *const g_example_waves[] = {
    "// @cfg vertex_labels = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -5.0f);",
    "glRotatef(20.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(30.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "// @cfg vertex_points = 0",
    "static float grid, extent, x, y, z, invGradMag; // strip cell index, world extent, vertex coords, 1/|gradient|",
    "static float amp = 0.4;    // wave amplitude (peak |y|)",
    "static float freq = 2.5;   // spatial frequency along x and z",
    "static float zPhase = 0.7; // z-axis time phase: z evolves slower than x (<1)",
    "glClearColor(0.05, 0.06, 0.08, 1.0);",
    "// Animated surface: y = sin(freq*x + t) * cos(freq*z + zPhase*t) * amp",
    "// Drawn as a triangle strip per row with analytic per-vertex normals.",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHT3);",
    "glEnable(GL_LIGHT2);",
    "glEnable(GL_LIGHT1);",
    "glEnable(GL_LIGHT0);",
    "glShadeModel(GL_SMOOTH);",
    "grid = 16;     // rows/cols of strip cells",
    "extent = 3.0;  // total surface width along x and z",
    "for(i, 0, grid) {",
        "glBegin(GL_TRIANGLE_STRIP);",
        "for(j, 0, grid+1) {",
            "// row i (z fixed), step j across x; emit two vertices per j to feed the strip",
            "x = -extent/2 + extent*j/grid;",
            "z = -extent/2 + extent*i/grid;",
            "y = sin(x*freq + t)*cos(z*freq + zPhase*t)*amp;",
            "// gradient = (dy/dx, 0, dy/dz); normal = (-dy/dx, 1, -dy/dz) / |...|.",
            "// invGradMag = 1 / sqrt(1 + amp^2 * freq^2 * (cos^2*cos^2 + sin^2*sin^2)).",
            "invGradMag = 1.0/sqrt(1 + amp*amp*freq*freq*(cos(x*freq + t)*cos(x*freq + t)*cos(z*freq + zPhase*t)*cos(z*freq + zPhase*t) + sin(x*freq + t)*sin(x*freq + t)*sin(z*freq + zPhase*t)*sin(z*freq + zPhase*t)));",
            "glNormal3f(-amp*freq*cos(x*freq + t)*cos(z*freq + zPhase*t)*invGradMag, invGradMag, amp*freq*sin(x*freq + t)*sin(z*freq + zPhase*t)*invGradMag);",
            "glColor3f(0.98 - 0.62*(0.5+0.5*y/amp), 0.46 + 0.24*(0.5+0.5*y/amp), 0.36 + 0.62*(0.5+0.5*y/amp));",
            "glVertex3f(x, y, z);",
            "// second strip vertex: same x, but z stepped to row i+1",
            "z = -extent/2 + extent*(i + 1)/grid;",
            "y = sin(x*freq + t)*cos(z*freq + zPhase*t)*amp;",
            "invGradMag = 1.0/sqrt(1 + amp*amp*freq*freq*(cos(x*freq + t)*cos(x*freq + t)*cos(z*freq + zPhase*t)*cos(z*freq + zPhase*t) + sin(x*freq + t)*sin(x*freq + t)*sin(z*freq + zPhase*t)*sin(z*freq + zPhase*t)));",
            "glNormal3f(-amp*freq*cos(x*freq + t)*cos(z*freq + zPhase*t)*invGradMag, invGradMag, amp*freq*sin(x*freq + t)*sin(z*freq + zPhase*t)*invGradMag);",
            "glColor3f(0.98 - 0.62*(0.5+0.5*y/amp), 0.46 + 0.24*(0.5+0.5*y/amp), 0.36 + 0.62*(0.5+0.5*y/amp));",
            "glVertex3f(x, y, z);",
        "}",
        "glEnd();",
    "}",
    NULL
};

/* Animated spirograph curve - closed parametric line loop
 * driven by t, showing dense iteration and trig-heavy vertex generation. */
static const char *const g_example_spirograph_curve[] = {
    "// @cfg view_mode = RENDER3D_VIEW_2D",
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg poly_highlight = 0",
    "// @cfg vertex_labels = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -7.5f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "static float dist, n, x, y, ang;",
    "glClearColor(0.05, 0.06, 0.08, 1.0);",
    "dist = 1.4;",
    "n = 400;",
    "glBegin(GL_LINE_LOOP);",
    "  for(i, 0, n) {",
    "    ang = TAU * i/n;",
    "    x = dist * cos(t*ang) + cos(ang);",
    "    y = dist * sin(t*ang) + sin(ang);",
    "    glColor3f(0.98 - 0.62*(0.5+0.5*sin(ang + t)), 0.46 + 0.24*(0.5+0.5*sin(ang + t)), 0.36 + 0.62*(0.5+0.5*sin(ang + t)));",
    "    glVertex3f(x, y, 0);",
    "  }",
    "glEnd();",
    NULL
};

/* Traveling ripple ring - circular line loop with a narrow
 * modulo-selected radial wave, exercising fmod math and conditional edits. */
static const char *const g_example_traveling_ripple_ring[] = {
    "// @cfg view_mode = RENDER3D_VIEW_2D",
    "// @cfg fit_frame = 1.15",
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -3.5f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "// Traveling ripple ring: nested for + fmod + conditional deformation",
    "static float phase, width, delta, amp, x, y;",
    "glClearColor(0.05, 0.06, 0.08, 1.0);",
    "amp = 0.1 * sin(t * TAU);",
    "phase = fmod(t / 3, TAU);",
    "width = PI / 8;",
    "glBegin(GL_LINE_LOOP);",
    "  for(i, 0, 400) {",
    "    glColor3f(0.36, 0.70, 0.98);",
    "    x = cos(TAU * i / 400);",
    "    y = sin(TAU * i / 400);",
    "    delta = fmod(TAU * i / 400 - phase + TAU, TAU);",
    "    if(delta < width) {",
    "      glColor3f(0.98, 0.76, 0.36);",
    "      x = x + amp * x * sin(delta * TAU / width);",
    "      y = y + amp * y * sin(delta * TAU / width);",
    "    }",
    "    glVertex3f(x, y, 0);",
    "  }",
    "glEnd();",
    NULL
};

/* Animated quadratic Bezier curve - vertex + line loop with parametric
 * function, showing variable assignment and reuse across calls. */
static const char *const g_example_bezier[] = {
    "// @cfg view_mode = RENDER3D_VIEW_2D",
    "// @cfg grid_brightness = GRID_BRIGHTNESS_BRIGHT",
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// @cfg poly_highlight = 0",
    "// @cfg msaa = 0",
    "// @cfg line_smooth = 1",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -3.5f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(-1.0f, -0.5f, 0.0f);",
    "static float x, y, x0, y0, x1 = 1, y1 = 1, x2 = 2, y2;",
    "static float period = 5;",
    "static float x_a, x_b, y_a, y_b;",
    "// current progress",
    "static float t0;",
    "bezier(x0, y0, x1, y1, x2, y2, u) {",
    "  x = pow(1-u, 2) * x0 + 2 * (1-u)*u * x1 + u*u * x2;",
    "  y = pow(1-u, 2) * y0 + 2 * (1-u)*u * y1 + u*u * y2;",
    "}",
    "glClearColor(0.05, 0.06, 0.08, 1);",
    "glEnable(GL_DEPTH_TEST);",
    "glDisable(GL_LIGHTING);",
    "glDisable(GL_MULTISAMPLE);",
    "glEnable(GL_LINE_SMOOTH);",
    "glEnable(GL_BLEND);",
    "glPointSize(8);",
    "glColor4f(0.98, 0.76, 0.36, 0.95);",
    "glLineWidth(1.3);",
    "t0 = (fmod(t, period)) / period;",
    "glBegin(GL_POINTS);",
    "  glVertex2f(x0, y0);",
    "  glVertex3f(x1, y1, 0);",
    "  glVertex2f(x2, y2);",
    "  bezier(x0, y0, x1, y1, x2, y2, t0);",
    "  glColor3f(0.98, 0.46, 0.36);",
    "  glVertex2f(x, y);",
    "glEnd();",
    "glColor4f(0.92, 0.95, 0.98, 0.95);",
    "glBegin(GL_LINE_STRIP);",
    "  for (u, 0, 1, 0.01f) {",
    "    bezier(x0, y0, x1, y1, x2, y2, u);",
    "    glVertex2f(x, y);",
    "  }",
    "glEnd();",
    "glColor4f(0.62, 0.52, 0.95, 0.40);",
    "x_a = x0*(1-t0) + x1*t0;",
    "y_a = y0*(1-t0) + y1*t0;",
    "x_b = x1*(1-t0) + x2*t0;",
    "y_b = y1*(1-t0) + y2*t0;",
    "glBegin(GL_POINTS);",
    "  glVertex2f(x_a, y_a);",
    "  glVertex2f(x_b, y_b);",
    "glEnd();",
    "glBegin(GL_LINES);",
    "  // Guide Line 1",
    "  glVertex2f(x0, y0);",
    "  glVertex2f(x1, y1);",
    "  // Guide Line 2",
    "  glVertex2f(x1, y1);",
    "  glVertex2f(x2, y2);",
    "  // Derived Line",
    "  glVertex2f(x_a, y_a);",
    "  glVertex2f(x_b, y_b);",
    "glEnd();",
    NULL
};

/* Snowfall - 550 GL_POINTS with x/y/z from rand(seed, iter) + time,
 * creating a looping field of falling points with depth-based color. */
static const char *const g_example_snowfall[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// @cfg poly_highlight = 0",
    "// @cfg grid = GRID_THEME_OFF",
    "// @cfg msaa = 1",
    "// @cfg line_smooth = 0",
    "// @cfg variable_panel = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -13.5f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "static float flakeCount = 550; // @tune",
    "static float flakeX, flakeY; // particle position",
    "static float drift, fall; // per-flake horizontal drift, vertical fall speed",
    "static float depth; // [0,1] random; depth and shade both derive from it",
    "static float driftMax = 0.5; // max horizontal drift magnitude",
    "static float fallBase = -1.5; // base fall speed (NOT gravity)",
    "static float wrapX = 12, wrapY = 5; // half-extents of the wrap region",
    "static float depthScale = 10; // multiplier on `depth` for z position",
    "glClearColor(0.05, 0.05, 0.05, 1);",
    "glEnable(GL_DEPTH_TEST);",
    "glPointSize(10);",
    "glBegin(GL_POINTS);",
    "  for (p, 0, flakeCount) {",
    "    drift = driftMax * rand2(p, 1);",
    "    flakeX = rem(wrapX * rand2(p,4) + t * drift, 2 * wrapX);",
    "",
    "    fall = fallBase - rand(p, 2);",
    "    flakeY = rem(wrapY * rand2(p,3) + t * fall, 2 * wrapY);",
    "",
    "    depth = rand(p, 5); // z affects color and distance",
    "",
    "    glColor3f(0.5 + 0.5 * depth, 0.5 + 0.5 * depth, 0.5 + 0.5 * depth);",
    "    glVertex3f(flakeX, flakeY, depthScale * depth);",
    "  }",
    "glEnd();",
    NULL
};

/* Grass field - deterministic blades from rand(seed, iter), with wind bend
 * derived from t so the scene stays stateless and REPL-friendly. */
static const char *const g_example_grass_field[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// @cfg poly_highlight = 0",
    "// @cfg vertex_labels = 0",
    "// @cfg grid = GRID_THEME_SOIL",
    "// @cfg grid_extent = GRID_EXTENT_CLOSE",
    "// @cfg axes = AXES_THEME_OFF",
    "// @cfg msaa = 1",
    "// @cfg variable_panel = 0",
    "// camera",
    "glTranslatef(0.0000f, 0.0000f, -6.0020f);",
    "glRotatef(5.0000f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(32.6714f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(-0.0074f, -0.9000f, -0.4837f);",
    "",
    "static float bladeCount = 77.05; // @tune",
    "static float field = 3.65; // half-width @tune",
    "static float x, z, h, w, angle, phase, flex;",
    "static float wind, wave, bend, u, cx, cz, halfW, shade;",
    "blade(seed, x0, z0, height, width, ang, ph, stiffness) {",
    "  wind = 0.55 + 0.25*sin(t*0.23);",
    "  wave = sin(t*2.2 + ph + x0*0.35 + z0*0.20) + 0.35*sin(t*4.9 + ph*1.7);",
    "  bend = (0.65 + 0.35*sin(t*0.75))*wave*stiffness*height*0.26;",
    "  glBegin(GL_TRIANGLE_STRIP);",
    "    for(s, 0, 5) {",
    "      u = s/4;",
    "      cx = x0 + 0.08*rand2(seed, 6)*u + cos(wind)*bend*u*u;",
    "      cz = z0 + 0.08*rand2(seed, 7)*u + sin(wind)*bend*u*u;",
    "      halfW = width*(1 - 0.82*u);",
    "      shade = 0.65 + 0.45*u;",
    "      glColor4f((0.08 + 0.07*rand(seed, 8))*shade, (0.38 + 0.32*rand(seed, 9))*shade, (0.06 + 0.07*rand(seed, 10))*shade, 0.95);",
    "      glVertex3f(cx - cos(ang)*halfW, height*u, cz - sin(ang)*halfW);",
    "      glVertex3f(cx + cos(ang)*halfW, height*u, cz + sin(ang)*halfW);",
    "    }",
    "  glEnd();",
    "}",
    "glClearColor(0.025, 0.055, 0.035, 1);",
    "glEnable(GL_DEPTH_TEST);",
    "glDisable(GL_LIGHTING);",
    "glDisable(GL_CULL_FACE);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);",
    "for(p, 0, bladeCount) {",
    "  x = (rand(p, 0)*2 - 1)*field;",
    "  z = (rand(p, 1)*2 - 1)*field;",
    "  h = 0.28 + rand(p, 2)*0.72;",
    "  w = 0.018 + rand(p, 3)*0.026;",
    "  angle = rand(p, 4)*TAU;",
    "  phase = rand(p, 5)*TAU;",
    "  flex = 0.55 + rand(p, 6)*1.1;",
    "  blade(p, x, z, h, w, angle, phase, flex);",
    "}",
    "glDisable(GL_BLEND);",
    NULL
};

/* Deep-sea jellyfish - every surface is translucent: additive blending with
 * glDepthMask(GL_FALSE) keeps the depth buffer read-only so the bell layers,
 * rim frill, and tentacles glow through one another instead of z-fighting
 * (first roster use of glDepthMask). The bell is latitude TRIANGLE_STRIPs
 * whose radius/height breathe in opposition; tentacles are sine-swayed
 * LINE_STRIPs whose tips lag the pulse. Marine snow drifts upward through
 * the frame via rem() wrapping. */
static const char *const g_example_jellyfish[] = {
    "// @cfg vertex_labels = 0",
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// @cfg normal_vectors = 0",
    "// @cfg grid = GRID_THEME_OFF",
    "// @cfg axes = AXES_THEME_OFF",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -7.5f);",
    "glRotatef(4.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.7f, 0.0f);",
    "static float pulse, bellR, bellH; // breath phase; bell radius/height pulse in opposition",
    "static float ang, phi, phi2, rad, rad2, topY, botY; // bell strip scratch",
    "static float ax, az, sway, drop; // tentacle scratch",
    "static float segs = 26;      // bell azimuth segments",
    "static float rings = 9;      // bell latitude strips",
    "static float tentacles = 15; // @tune",
    "static float tentLen = 2.4;  // @tune",
    "glClearColor(0.015, 0.03, 0.07, 1);",
    "// Everything glows: additive blend with depth WRITES off (reads stay on).",
    "// glDepthMask(GL_FALSE) is the classic translucency trick - without it the",
    "// bell's far side would z-fight its near side and the tentacles would",
    "// punch holes through the bell.",
    "glDisable(GL_LIGHTING);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE);",
    "glEnable(GL_LINE_SMOOTH);",
    "glEnable(GL_POINT_SMOOTH);",
    "glDepthMask(GL_FALSE);",
    "pulse = sin(t*1.6);",
    "bellR = 1.5*(1 + 0.10*pulse);",
    "bellH = 1.1*(1 - 0.14*pulse);",
    "",
    "// marine snow: slow upward drift, wrapped with rem() so the field loops",
    "glPointSize(5);",
    "glBegin(GL_POINTS);",
    "for(p, 0, 110) {",
    "  glColor4f(0.55, 0.75, 0.95, 0.08 + 0.22*rand(p, 4));",
    "  // rise speed 0.15..0.5 per mote; rem() wraps y into [-3.2, 3.2]",
    "  glVertex3f(4.5*rand2(p, 0) + 0.2*sin(t*0.4 + p), rem(3.2*rand2(p, 1) + t*(0.15 + 0.35*rand(p, 3)), 6.4), 4.5*rand2(p, 2));",
    "}",
    "glEnd();",
    "",
    "// gentle bob + tilt for the whole animal",
    "glTranslatef(0.2*sin(t*0.4), 0.18*sin(t*0.5), 0);",
    "glRotatef(8*sin(t*0.23), 0, 0, 1);",
    "",
    "// bell: latitude strips from crown to just past the equator (it curls",
    "// under). Ring geometry depends only on i, so it is hoisted out of the",
    "// inner loop - per-vertex assignments would blow the flat-command budget.",
    "for(i, 0, rings) {",
    "  phi = (i/rings)*PI*0.52;",
    "  phi2 = ((i+1)/rings)*PI*0.52;",
    "  rad = bellR*sin(phi);",
    "  topY = bellH*cos(phi);",
    "  rad2 = bellR*sin(phi2);",
    "  botY = bellH*cos(phi2);",
    "  glBegin(GL_TRIANGLE_STRIP);",
    "  for(j, 0, segs+1) {",
    "    ang = j*TAU/segs;",
    "    glColor4f(0.10 + 0.30*i/rings, 0.35 + 0.45*i/rings, 0.95, 0.05 + 0.20*(i/rings)*(i/rings) + 0.04*sin(ang*6 - t*2));",
    "    glVertex3f(rad*cos(ang), topY, rad*sin(ang));",
    "    glColor4f(0.10 + 0.30*(i+1)/rings, 0.35 + 0.45*(i+1)/rings, 0.95, 0.05 + 0.20*((i+1)/rings)*((i+1)/rings) + 0.04*sin(ang*6 - t*2));",
    "    glVertex3f(rad2*cos(ang), botY, rad2*sin(ang));",
    "  }",
    "  glEnd();",
    "}",
    "",
    "// scalloped frill hanging off the rim",
    "rad = bellR*sin(PI*0.52);",
    "topY = bellH*cos(PI*0.52);",
    "glBegin(GL_TRIANGLE_STRIP);",
    "for(j, 0, segs+1) {",
    "  ang = j*TAU/segs;",
    "  sway = -0.18 - 0.10*pulse + 0.10*sin(ang*9 + t*2.6);",
    "  glColor4f(0.45, 0.85, 1.0, 0.30);",
    "  glVertex3f(rad*cos(ang), topY, rad*sin(ang));",
    "  glColor4f(0.45, 0.85, 1.0, 0.03);",
    "  glVertex3f(rad*1.04*cos(ang), topY + sway, rad*1.04*sin(ang));",
    "}",
    "glEnd();",
    "",
    "// one tentacle: a swaying line strip; alpha fades toward the tip and the",
    "// pulse tugs the strand upward (the drop*drop term makes tips lag the bell)",
    "tentacle(angAt, attach, len, phase, amp, cr, cg, cb) {",
    "  ax = cos(angAt)*attach;",
    "  az = sin(angAt)*attach;",
    "  glBegin(GL_LINE_STRIP);",
    "  for(s, 0, 14) {",
    "    drop = s/13;",
    "    sway = amp*(sin(t*1.4 + phase + drop*3.5) + 0.4*sin(t*2.3 + phase*1.7 + drop*6))*drop;",
    "    glColor4f(cr, cg, cb, 0.04 + 0.40*(1 - drop)*(1 - drop));",
    "    glVertex3f(ax*(1 + 0.2*drop) + sway, topY - drop*len + 0.15*pulse*drop*drop, az*(1 + 0.2*drop) + sway*0.55);",
    "  }",
    "  glEnd();",
    "}",
    "glLineWidth(1.6);",
    "for(k, 0, tentacles) {",
    "  tentacle(k*TAU/tentacles + 0.2*rand2(k, 1), bellR*0.85, tentLen*(0.75 + 0.5*rand(k, 2)), rand(k, 3)*TAU, 0.3, 0.35, 0.75, 1.0);",
    "}",
    "// four thicker oral arms under the crown",
    "glLineWidth(3.2);",
    "for(k, 0, 4) {",
    "  tentacle(k*TAU/4 + 0.4, bellR*0.3, tentLen*1.2, k*1.7, 0.55, 1.0, 0.45, 0.75);",
    "}",
    "glLineWidth(1);",
    "",
    "// bioluminescent core: two stacked soft points",
    "glPointSize(30);",
    "glBegin(GL_POINTS);",
    "glColor4f(1.0, 0.55, 0.75, 0.30);",
    "glVertex3f(0, bellH*0.3, 0);",
    "glEnd();",
    "glPointSize(13);",
    "glBegin(GL_POINTS);",
    "glColor4f(1.0, 0.8, 0.9, 0.55);",
    "glVertex3f(0, bellH*0.32, 0);",
    "glEnd();",
    "",
    "// leave shared GL state the way we found it",
    "glDepthMask(GL_TRUE);",
    "glDisable(GL_BLEND);",
    NULL
};

/* Stress test ("Dusk lighthouse atoll") - one coherent scene that still
 * exercises the kitchen sink: nested for-loops, recursion with
 * if / else if / else, multiple functions with args, the matrix stack,
 * GLU tessellation with a cutout, GLUT solids, a parametric surface with
 * analytic normals, additive-blended points, lines, per-fragment material
 * shininess, depth-mask translucency, bitmap text, and animation. All
 * geometry draws from the shared Dusk palette (see the header comment).
 * Stays well under the 4096 flattened-command budget. */
static const char *const g_example_stress[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 1",
    "// @cfg axes = AXES_THEME_OFF",
    "// @cfg grid = GRID_THEME_OFF",
    "// @cfg backdrop = RENDER3D_BACKDROP_STARS",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -15.0f);",
    "glRotatef(26.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(-20.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, -0.3f, 0.0f);",
    "",
    "static float x, y, z, n, k, s;",
    "glClearColor(0.05, 0.06, 0.08, 1.0);",
    "// ===== Dusk lighthouse atoll - a coherent feature tour =====",
    "// One scene, many features: a parametric sea, a tessellated island with a",
    "// lagoon cutout, a lighthouse of stacked GLUT solids with a sweeping",
    "// translucent beam, a recursive tree (if / else if / else), GLUT-solid",
    "// rocks, additive-blended firefly points, and a moon with a halo ring.",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_COLOR_MATERIAL);",
    "glColorMaterial(GL_FRONT_AND_BACK, GL_AMBIENT_AND_DIFFUSE);",
    "glEnable(GL_LIGHT0);",
    "glEnable(GL_LIGHT2);",
    "glEnable(GL_LIGHT3);",
    "glShadeModel(GL_SMOOTH);",
    "glLightModeli(GL_LIGHT_MODEL_TWO_SIDE, 1);",
    "glMaterialf(GL_FRONT_AND_BACK, GL_SHININESS, 16);",
    "",
    "// --- sea(): animated water sheet (nested for + analytic normals) ---",
    "// Colored by wave height: deep azure troughs lift to bright azure crests.",
    "sea(half, cells, amp) {",
    "  for(i, 0, cells) {",
    "    glBegin(GL_TRIANGLE_STRIP);",
    "    for(j, 0, cells + 1) {",
    "      x = -half + 2*half*j/cells;",
    "      z = -half + 2*half*i/cells;",
    "      y = amp*sin(x*1.5 + t)*cos(z*1.5 + t*0.6);",
    "      n = 1.0/sqrt(1 + amp*amp*2.25*(cos(x*1.5 + t)*cos(x*1.5 + t)*cos(z*1.5 + t*0.6)*cos(z*1.5 + t*0.6) + sin(x*1.5 + t)*sin(x*1.5 + t)*sin(z*1.5 + t*0.6)*sin(z*1.5 + t*0.6)));",
    "      glNormal3f(-amp*1.5*cos(x*1.5 + t)*cos(z*1.5 + t*0.6)*n, n, amp*1.5*sin(x*1.5 + t)*sin(z*1.5 + t*0.6)*n);",
    "      glColor3f(0.18 + 0.18*(0.5+0.5*y/amp), 0.34 + 0.36*(0.5+0.5*y/amp), 0.55 + 0.43*(0.5+0.5*y/amp));",
    "      glVertex3f(x, y, z);",
    "      z = -half + 2*half*(i + 1)/cells;",
    "      y = amp*sin(x*1.5 + t)*cos(z*1.5 + t*0.6);",
    "      n = 1.0/sqrt(1 + amp*amp*2.25*(cos(x*1.5 + t)*cos(x*1.5 + t)*cos(z*1.5 + t*0.6)*cos(z*1.5 + t*0.6) + sin(x*1.5 + t)*sin(x*1.5 + t)*sin(z*1.5 + t*0.6)*sin(z*1.5 + t*0.6)));",
    "      glNormal3f(-amp*1.5*cos(x*1.5 + t)*cos(z*1.5 + t*0.6)*n, n, amp*1.5*sin(x*1.5 + t)*sin(z*1.5 + t*0.6)*n);",
    "      glColor3f(0.18 + 0.18*(0.5+0.5*y/amp), 0.34 + 0.36*(0.5+0.5*y/amp), 0.55 + 0.43*(0.5+0.5*y/amp));",
    "      glVertex3f(x, y, z);",
    "    }",
    "    glEnd();",
    "  }",
    "}",
    "",
    "// --- island(): tessellated landmass with a lagoon cutout (GLU tess) ---",
    "island(r, lagoon) {",
    "  glFrontFace(GL_CW);",
    "  gluBegin(GLU_POLYGON);",
    "  // Outer wobbly coastline",
    "  gluBegin(GLU_CONTOUR);",
    "  gluNormal(0, 1, 0);",
    "  for(i, 0, 30) {",
    "    k = r*(1 + 0.16*sin(i*0.9) + 0.09*cos(i*1.7));",
    "    gluColor(0.22 + 0.12*sin(i*0.5), 0.40 + 0.10*cos(i*0.7), 0.46 + 0.08*sin(i));",
    "    gluVertex(k*cos(i*TAU/30), 0, k*sin(i*TAU/30));",
    "  }",
    "  gluEnd();",
    "  // Inner lagoon contour (tessellator infers the hole from the overlap)",
    "  gluBegin(GLU_CONTOUR);",
    "  for(i, 0, 20) {",
    "    x = lagoon*cos(-i*TAU/20) - r*0.35;",
    "    z = lagoon*sin(-i*TAU/20) + r*0.2;",
    "    gluColor(0.08, 0.14, 0.20);",
    "    gluVertex(x, 0, z);",
    "  }",
    "  gluEnd();",
    "  gluEnd();",
    "  glFrontFace(GL_CCW);",
    "}",
    "",
    "// --- lighthouse(): stacked GLUT solids (cone / torus / sphere) ---",
    "lighthouse() {",
    "  glPushMatrix();",
    "  // Base rock - cone, apex up",
    "  glColor3f(0.30, 0.34, 0.42);",
    "  glPushMatrix();",
    "  glRotatef(-90, 1, 0, 0);",
    "  glutSolidCone(0.55, 0.5, 18, 3);",
    "  glPopMatrix();",
    "  glTranslatef(0, 0.42, 0);",
    "  // Tapered tower",
    "  glColor3f(0.90, 0.93, 0.97);",
    "  glPushMatrix();",
    "  glRotatef(-90, 1, 0, 0);",
    "  glutSolidCone(0.34, 1.5, 22, 1);",
    "  glPopMatrix();",
    "  // Coral band wrapping the tower",
    "  glPushMatrix();",
    "  glTranslatef(0, 0.62, 0);",
    "  glRotatef(90, 1, 0, 0);",
    "  glColor3f(0.98, 0.46, 0.36);",
    "  glutSolidTorus(0.04, 0.22, 10, 22);",
    "  glPopMatrix();",
    "  // Lantern - shiny amber bulb",
    "  glTranslatef(0, 1.5, 0);",
    "  glColor3f(0.98, 0.82, 0.45);",
    "  glMaterialf(GL_FRONT_AND_BACK, GL_SHININESS, 90);",
    "  glutSolidSphere(0.2, 16, 12);",
    "  glMaterialf(GL_FRONT_AND_BACK, GL_SHININESS, 16);",
    "  // Violet roof cone",
    "  glColor3f(0.62, 0.52, 0.95);",
    "  glPushMatrix();",
    "  glTranslatef(0, 0.16, 0);",
    "  glRotatef(-90, 1, 0, 0);",
    "  glutSolidCone(0.24, 0.32, 14, 1);",
    "  glPopMatrix();",
    "  glPopMatrix();",
    "}",
    "",
    "// --- tree(): recursion with if / else if / else tiered coloring ---",
    "tree(depth, len, twist) {",
    "  if(depth >= 3) {",
    "    glColor3f(0.40, 0.36, 0.50);",
    "  } else if(depth >= 1) {",
    "    glColor3f(0.50 - 0.03*depth, 0.50, 0.92);",
    "  } else {",
    "    glColor3f(0.98, 0.74, 0.40);",
    "  }",
    "  glLineWidth(depth + 1);",
    "  glBegin(GL_LINES);",
    "  glNormal3f(0, 0, 1);",
    "  glVertex3f(0, 0, 0);",
    "  glVertex3f(0, len, 0);",
    "  glEnd();",
    "  if(depth > 0) {",
    "    glPushMatrix();",
    "    glTranslatef(0, len, 0);",
    "    glRotatef(26 + 7*sin(twist), 0, 0, 1);",
    "    glScalef(0.74, 0.74, 0.74);",
    "    tree(depth - 1, len, twist + 0.4);",
    "    glPopMatrix();",
    "    glPushMatrix();",
    "    glTranslatef(0, len, 0);",
    "    glRotatef(-29 - 6*cos(twist), 0, 0, 1);",
    "    glScalef(0.70, 0.70, 0.70);",
    "    tree(depth - 1, len, twist + 0.3);",
    "    glPopMatrix();",
    "    glPushMatrix();",
    "    glTranslatef(0, len*0.92, 0);",
    "    glRotatef(16 + 5*sin(twist*1.3), 1, 0, 0);",
    "    glScalef(0.60, 0.60, 0.60);",
    "    tree(depth - 1, len*0.86, twist + 0.5);",
    "    glPopMatrix();",
    "  } else {",
    "    // Blossom - small lit sphere at the twig tip",
    "    glColor3f(0.98, 0.55, 0.42);",
    "    glPushMatrix();",
    "    glTranslatef(0, len, 0);",
    "    glutSolidSphere(len*0.55, 8, 6);",
    "    glPopMatrix();",
    "  }",
    "}",
    "",
    "// ===== Scene composition =====",
    "glLineWidth(1);",
    "",
    "// Sea sheet under everything",
    "glPushMatrix();",
    "glTranslatef(0, -0.62, 0);",
    "sea(5.5, 10, 0.16);",
    "glPopMatrix();",
    "",
    "// Island shelf just above the water",
    "glPushMatrix();",
    "glTranslatef(0, -0.5, 0);",
    "island(2.2, 0.45);",
    "glPopMatrix();",
    "",
    "// Lighthouse on the island",
    "glPushMatrix();",
    "glTranslatef(0.5, -0.5, 0.1);",
    "lighthouse();",
    "glPopMatrix();",
    "",
    "// Sweeping light beams from the lantern (blend + depth-mask off)",
    "glPushMatrix();",
    "glTranslatef(0.5, 1.42, 0.1);",
    "glRotatef(t*55, 0, 1, 0);",
    "glDisable(GL_LIGHTING);",
    "glDepthMask(GL_FALSE);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE);",
    "glBegin(GL_TRIANGLES);",
    "glColor4f(0.98, 0.82, 0.45, 0.55);",
    "glVertex3f(0, 0, 0);",
    "glColor4f(0.98, 0.82, 0.45, 0.0);",
    "glVertex3f(7, -0.5, 0.7);",
    "glVertex3f(7, 0.5, -0.7);",
    "glColor4f(0.98, 0.82, 0.45, 0.55);",
    "glVertex3f(0, 0, 0);",
    "glColor4f(0.98, 0.82, 0.45, 0.0);",
    "glVertex3f(-7, 0.5, 0.7);",
    "glVertex3f(-7, -0.5, -0.7);",
    "glEnd();",
    "glDepthMask(GL_TRUE);",
    "glDisable(GL_BLEND);",
    "glEnable(GL_LIGHTING);",
    "glPopMatrix();",
    "",
    "// Wind-swayed tree across the island",
    "glPushMatrix();",
    "glTranslatef(-1.2, -0.5, 0.4);",
    "glRotatef(4*sin(t*0.4), 0, 0, 1);",
    "tree(3, 0.62, t*0.2);",
    "glPopMatrix();",
    "",
    "// Ring of rocks around the shoreline (loop + GLUT solids)",
    "for(i, 0, 7) {",
    "  glPushMatrix();",
    "  glRotatef(i*360/7 + 20, 0, 1, 0);",
    "  glTranslatef(2.0, -0.55, 0);",
    "  glColor3f(0.28, 0.31, 0.40);",
    "  glScalef(1, 0.55, 1);",
    "  glutSolidSphere(0.16 + 0.07*rand(i, 7), 8, 6);",
    "  glPopMatrix();",
    "}",
    "",
    "// Fireflies - additive point sprites drifting over the atoll",
    "glDisable(GL_LIGHTING);",
    "glDepthMask(GL_FALSE);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE);",
    "glEnable(GL_POINT_SMOOTH);",
    "glPointSize(7);",
    "glBegin(GL_POINTS);",
    "for(i, 0, 44) {",
    "  k = rand(i, 0)*TAU;",
    "  s = 1.2 + rand(i, 1)*2.6;",
    "  x = cos(k + t*(0.25 + rand(i, 2)*0.4))*s;",
    "  z = sin(k + t*(0.25 + rand(i, 2)*0.4))*s;",
    "  y = 0.1 + 1.4*rand(i, 3) + 0.18*sin(t*2 + i);",
    "  glColor4f(0.98, 0.74 + 0.22*rand(i, 4), 0.42, 0.75);",
    "  glVertex3f(x, y, z);",
    "}",
    "glEnd();",
    "glDisable(GL_POINT_SMOOTH);",
    "glDepthMask(GL_TRUE);",
    "glDisable(GL_BLEND);",
    "glEnable(GL_LIGHTING);",
    "",
    "// Moon with a violet halo ring, parked in the sky",
    "glPushMatrix();",
    "glTranslatef(-3.6, 3.0, -2.0);",
    "glDisable(GL_LIGHTING);",
    "glColor3f(0.92, 0.95, 0.98);",
    "glutSolidSphere(0.55, 22, 16);",
    "glBegin(GL_LINE_LOOP);",
    "for(i, 0, 48) {",
    "  glColor3f(0.62, 0.52, 0.95);",
    "  glVertex3f(0.92*cos(i*TAU/48), 0.92*sin(i*TAU/48), 0);",
    "}",
    "glEnd();",
    "glEnable(GL_LIGHTING);",
    "glPopMatrix();",
    "",
    "// Caption readout (glRasterPos + bitmap label)",
    "glDisable(GL_LIGHTING);",
    "glColor3f(0.92, 0.95, 0.98);",
    "glRasterPos3f(-3.2, 2.2, 0);",
    "label(\"dusk atoll\");",
    "glEnable(GL_LIGHTING);",
    NULL
};

/* Transformation stress test - exercises translate/rotate/scale guides in
 * varied contexts: nested push/pop, time-varying args (t), for-loop
 * unrolling, function scopes, and scale-of-origin (3-axis gizmo fallback).
 * Park the cursor on any transform line to see its guide overlay. */
static const char *const g_example_xform_stress[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -5.0f);",
    "glRotatef(00.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, -0.8f, 0.0f);",
    "",
    "glClearColor(0.05, 0.06, 0.08, 1);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_LIGHT0);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_COLOR_MATERIAL);",
    "tri() {",
        "glBegin(GL_TRIANGLES);",
        "glNormal3f(0, 0, 1);",
        "glVertex3f(-0.3, -0.3, 0);",
        "glVertex3f(0.3, -0.3, 0);",
        "glVertex3f(0, 0.4, 0);",
        "glEnd();",
    "}",
    "glColor3f(0.98, 0.46, 0.36);",
    "glPushMatrix();",
    "glTranslatef(0, 0, 2);",
    "glRotatef(45, 0, 1, 0);",
    "glTranslatef(0, 0, -2);",
    "tri();",
    "glPopMatrix();",
    "glColor3f(0.30, 0.84, 0.80);",
    "glPushMatrix();",
    "glTranslatef(-2, 0, 0);",
    "glRotatef(3*t, 0, 1, 0);",
    "glScalef(1.5, 0.5, 1);",
    "tri();",
    "glPopMatrix();",
    "glColor3f(0.36, 0.70, 0.98);",
    "for(i, 0, 6) {",
        "glPushMatrix();",
        "glRotatef(i*60, 0, 1, 0);",
        "glTranslatef(2.5, 0, 0);",
        "glScalef(0.6, 0.6, 0.6);",
        "tri();",
        "glPopMatrix();",
    "}",
    "glColor3f(0.95, 0.44, 0.66);",
    "glPushMatrix();",
    "glTranslatef(0, 2, 0);",
    "glScalef(0.8, 0.8, 0.8);",
    "tri();",
    "glPopMatrix();",
    "glColor3f(0.98, 0.76, 0.36);",
    "glPushMatrix();",
    "glRotatef(t*30, 0, 1, 0);",
    "tri();",
    "glPopMatrix();",
    NULL
};

/* Scratch-array demo - cubic Bezier evaluation via de Casteljau updates.
 * A/B/C hold the x/y/z control-point lanes while collapse() implements one
 * in-place interpolation step using ordinary expression math. */
static const char *const g_example_scratch_casteljau[] = {
    "// @cfg view_mode = RENDER3D_VIEW_2D",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -8.0f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "glClearColor(0.05, 0.06, 0.08, 1);",
    "glEnable(GL_DEPTH_TEST);",
    "glDisable(GL_LIGHTING);",
    "glLineWidth(3);",
    "static float u;",
    "// collapse(dst, lo, hi, blend): collapse one Bezier edge in place.",
    "collapse(dst, lo, hi, blend) {",
        "A[dst] = A[lo] + (A[hi] - A[lo])*blend;",
        "B[dst] = B[lo] + (B[hi] - B[lo])*blend;",
        "C[dst] = C[lo] + (C[hi] - C[lo])*blend;",
    "}",
    "// Seed A/B/C with control points, then overwrite them with collapse().",
    "glColor3f(0.98, 0.46, 0.36);",
    "glBegin(GL_LINE_STRIP);",
    "for(i, 0, 48) {",
        "A[0] = -3.2;",
        "B[0] = -1.8;",
        "C[0] = -0.8;",
        "A[1] = -1.1 + 0.4*sin(t*0.9);",
        "B[1] = 2.4;",
        "C[1] = -0.1;",
        "A[2] = 1.0;",
        "B[2] = -2.1 + 0.5*cos(t*0.7);",
        "C[2] = 0.5;",
        "A[3] = 3.1;",
        "B[3] = 1.6;",
        "C[3] = 1.0 + 0.25*sin(t*0.5);",
        "u = i/48.0;",
        "collapse(0, 0, 1, u);",
        "collapse(1, 1, 2, u);",
        "collapse(2, 2, 3, u);",
        "collapse(0, 0, 1, u);",
        "collapse(1, 1, 2, u);",
        "collapse(0, 0, 1, u);",
        "glVertex3f(A[0], B[0], C[0]);",
    "}",
    "glEnd();",
    "",
    "// Rebuild the same control polygon from scratch-array state.",
    "A[0] = -3.2;",
    "B[0] = -1.8;",
    "C[0] = -0.8;",
    "A[1] = -1.1 + 0.4*sin(t*0.9);",
    "B[1] = 2.4;",
    "C[1] = -0.1;",
    "A[2] = 1.0;",
    "B[2] = -2.1 + 0.5*cos(t*0.7);",
    "C[2] = 0.5;",
    "A[3] = 3.1;",
    "B[3] = 1.6;",
    "C[3] = 1.0 + 0.25*sin(t*0.5);",
    "glColor3f(0.36, 0.70, 0.98);",
    "glBegin(GL_LINE_STRIP);",
    "glVertex3f(A[0], B[0], C[0]);",
    "glVertex3f(A[1], B[1], C[1]);",
    "glVertex3f(A[2], B[2], C[2]);",
    "glVertex3f(A[3], B[3], C[3]);",
    "glEnd();",
    "glPointSize(9);",
    "glColor3f(0.98, 0.76, 0.36);",
    "glBegin(GL_POINTS);",
    "glVertex3f(A[0], B[0], C[0]);",
    "glVertex3f(A[1], B[1], C[1]);",
    "glVertex3f(A[2], B[2], C[2]);",
    "glVertex3f(A[3], B[3], C[3]);",
    "glEnd();",
    NULL
};

/* Text annotation demo - pairs glRasterPos3f with label() so scene data can
 * carry live numeric readouts instead of geometry alone. */
static const char *const g_example_annotated_orbit_plot[] = {
    "// @cfg view_mode = RENDER3D_VIEW_2D",
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -7.0f);",
    "glRotatef(0.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "static float n, r, x, y, phase, sample;",
    "glClearColor(0.06, 0.07, 0.09, 1);",
    "glDisable(GL_LIGHTING);",
    "glDisable(GL_DEPTH_TEST);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);",
    "glLineWidth(1.4);",
    "// Annotation demo: geometry plus live numeric labels.",
    "phase = fmod(t*0.2, 1);",
    "n = 72;",
    "for(r, 1, 4) {",
        "glColor4f(0.2, 0.35, 0.55, 0.45);",
        "glBegin(GL_LINE_LOOP);",
        "for(i, 0, n) {",
            "glVertex3f(cos(i*TAU/n)*r*0.6, sin(i*TAU/n)*r*0.6, 0);",
        "}",
        "glEnd();",
        "glRasterPos3f(r*0.6 + 0.08, 0, 0);",
        "label(\"r=%f\", r*0.6);",
    "}",
    "glColor4f(0.45, 0.5, 0.65, 0.45);",
    "glBegin(GL_LINES);",
    "for(i, 0, 12) {",
        "glVertex3f(0, 0, 0);",
        "glVertex3f(cos(i*TAU/12)*2.4, sin(i*TAU/12)*2.4, 0);",
    "}",
    "glEnd();",
    "glColor3f(1.0, 0.75, 0.25);",
    "glLineWidth(3);",
    "glBegin(GL_LINE_STRIP);",
    "for(i, 0, n+1) {",
        "sample = i/n;",
        "r = 1.0 + 0.5*sin(sample*TAU*3 + t);",
        "glVertex3f(cos(sample*TAU)*r, sin(sample*TAU)*r, 0);",
    "}",
    "glEnd();",
    "sample = phase;",
    "r = 1.0 + 0.5*sin(sample*TAU*3 + t);",
    "x = cos(sample*TAU)*r;",
    "y = sin(sample*TAU)*r;",
    "glPointSize(11);",
    "glColor3f(0.1, 0.9, 1.0);",
    "glBegin(GL_POINTS);",
    "glVertex3f(x, y, 0);",
    "glEnd();",
    "glColor3f(1.0, 1.0, 1.0);",
    "glRasterPos3f(-2.35, 2.35, 0);",
    "label(\"phase=%f\", phase);",
    "glRasterPos3f(x + 0.12, y + 0.12, 0);",
    "label(\"r=%f\", r);",
    "glRasterPos3f(-2.35, -2.35, 0);",
    "label(\"label text follows glRasterPos3f\");",
    NULL
};

/* 3D raster-text demo: an orrery of all eight planets. One shared planet()
 * function places each body (Kepler-flavored: rates fall with distance) and
 * leaves th/px/py/pz set so the caller can anchor a glRasterPos3f label next
 * to the sphere it just drew — the bitmap text follows the moving body in
 * depth rather than sitting in a flat HUD; a live %f readout reports Earth's
 * orbital phase. Radii are square-root compressed from the true Earth ratios
 * (Jupiter at its honest 11.2x would swallow the inner system) — relative
 * order is preserved. Saturn gets a two-band translucent ring with a Cassini
 * gap, Uranus a thin near-vertical ring (its ~98-degree axial tilt), Earth a
 * moon. All bodies share one specular material for a sun-glint; orbit
 * distances are compressed and the sun is NOT to scale. */
static const char *const g_example_orrery[] = {
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// @cfg axes = AXES_THEME_OFF",
    "// @cfg grid = GRID_THEME_OFF",
    "// @cfg light_theme = LIGHT_THEME_SOLAR",
    "// @cfg backdrop = RENDER3D_BACKDROP_STARS",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -19.0f);",
    "glRotatef(30.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "",
    "static float th, px, py, pz; // shared orbit scratch: angle + world position",
    "OrbitRings(rad, tilt) {",
    "  glBegin(GL_LINE_LOOP);",
    "    for(i, 0, 96) {",
    "      glVertex3f(cos(i*TAU/96)*rad, sin(i*TAU/96)*rad*sin(tilt), sin(i*TAU/96)*rad*cos(tilt));",
    "    }",
    "  glEnd();",
    "}",
    "// planet(): one lit sphere on an inclined circular orbit. th/px/py/pz",
    "// stay set after the call so the caller can hang a label off the body.",
    "planet(orbitR, rate, phase, incl, prad, cr, cg, cb) {",
    "  th = t*rate + phase;",
    "  px = cos(th)*orbitR;",
    "  py = sin(th)*orbitR*sin(incl);",
    "  pz = sin(th)*orbitR*cos(incl);",
    "  glEnable(GL_LIGHTING);",
    "  glColor3f(cr, cg, cb);",
    "  glPushMatrix();",
    "    glTranslatef(px, py, pz);",
    "    glutSolidSphere(prad, 24, 18);",
    "  glPopMatrix();",
    "  glDisable(GL_LIGHTING);",
    "}",
    "glClearColor(0.02, 0.02, 0.05, 1);",
    "glEnable(GL_NORMALIZE);",
    "// use cull face since we are using blending we want the effect to be view independent",
    "glEnable(GL_CULL_FACE);",
    "",
    "// the sun: drawn unlit so it glows (it sits on the SOLAR light at origin)",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE);",
    "glDisable(GL_DEPTH_TEST);",
    "// soft corona, then two pulsing shells at different frequencies",
    "glColor4f(1, 0.72, 0.22, 0.16);",
    "glutSolidSphere(0.72 + sin(t*1.3)*0.02, 24, 24);",
    "glColor4f(1, 0.85, 0.3, 0.5);",
    "glutSolidSphere(0.56 + cos(2*t)*0.012, 24, 24);",
    "glutSolidSphere(0.5 + sin(t)*0.012, 24, 24);",
    "glEnable(GL_DEPTH_TEST);",
    "glutSolidSphere(0.45, 24, 24);",
    "glColor3f(1, 0.9, 0.5);",
    "glRasterPos3f(0.62, 0.58, 0);",
    "label(\"Sun\");",
    "",
    "// planets: lit by the central SOLAR light; glColor rides GL_COLOR_MATERIAL",
    "// and one shared specular material gives every body a sun-glint",
    "glEnable(GL_LIGHT0);",
    "glEnable(GL_COLOR_MATERIAL);",
    "glMaterialfv(GL_FRONT_AND_BACK, GL_SPECULAR, (GLfloat[]){0.35, 0.33, 0.3, 1});",
    "glMaterialfv(GL_FRONT_AND_BACK, GL_SHININESS, (GLfloat[]){18});",
    "// Mercury (0.38 Earth radii)",
    "planet(1.4, 1.6, 0.0, 0.18, 0.105, 0.63, 0.58, 0.54);",
    "glColor3f(0.9, 0.85, 0.8);",
    "glRasterPos3f(px + 0.14, py + 0.16, pz);",
    "label(\"Mercury\");",
    "// Venus (0.95 Earth radii)",
    "planet(2.05, 1.15, 1.0, 0.06, 0.165, 0.93, 0.81, 0.55);",
    "glColor3f(1, 0.9, 0.65);",
    "glRasterPos3f(px + 0.2, py + 0.22, pz);",
    "label(\"Venus\");",
    "// Earth (the reference radius) + Moon circling it",
    "planet(2.7, 0.85, 2.5, 0.0, 0.17, 0.3, 0.52, 0.95);",
    "glPushMatrix();",
    "  glTranslatef(px, py, pz);",
    "  glRotatef(t*160, 0, 1, 0);",
    "  glTranslatef(0.34, 0.03, 0);",
    "  glEnable(GL_LIGHTING);",
    "  glColor3f(0.72, 0.72, 0.7);",
    "  glutSolidSphere(0.046, 12, 10);",
    "  glDisable(GL_LIGHTING);",
    "glPopMatrix();",
    "glColor3f(0.6, 0.8, 1);",
    "glRasterPos3f(px + 0.2, py + 0.22, pz);",
    "label(\"Earth\");",
    "// Mars (0.53 Earth radii)",
    "planet(3.35, 0.62, 4.0, 0.22, 0.125, 0.88, 0.45, 0.26);",
    "glColor3f(1, 0.6, 0.45);",
    "glRasterPos3f(px + 0.16, py + 0.18, pz);",
    "label(\"Mars\");",
    "// Jupiter (11.2 Earth radii before compression)",
    "planet(4.5, 0.36, 1.8, 0.05, 0.57, 0.83, 0.69, 0.52);",
    "glColor3f(1, 0.85, 0.65);",
    "glRasterPos3f(px + 0.62, py + 0.5, pz);",
    "label(\"Jupiter\");",
    "// Saturn (9.4 Earth radii) + two ring bands with a Cassini gap.",
    "// Rings are flat strips, so culling is off while they draw - either",
    "// face may point at the camera.",
    "planet(5.8, 0.26, 3.4, 0.10, 0.52, 0.9, 0.8, 0.58);",
    "glPushMatrix();",
    "  glTranslatef(px, py, pz);",
    "  glRotatef(27, 1, 0, 0.35);",
    "  glDisable(GL_CULL_FACE);",
    "  glBegin(GL_TRIANGLE_STRIP);",
    "  for(s, 0, 33) {",
    "    glColor4f(0.85, 0.75, 0.55, 0.5);",
    "    glVertex3f(cos(s*TAU/32)*0.66, 0, sin(s*TAU/32)*0.66);",
    "    glColor4f(0.9, 0.82, 0.6, 0.3);",
    "    glVertex3f(cos(s*TAU/32)*0.88, 0, sin(s*TAU/32)*0.88);",
    "  }",
    "  glEnd();",
    "  glBegin(GL_TRIANGLE_STRIP);",
    "  for(s, 0, 33) {",
    "    glColor4f(0.8, 0.72, 0.5, 0.35);",
    "    glVertex3f(cos(s*TAU/32)*0.93, 0, sin(s*TAU/32)*0.93);",
    "    glColor4f(0.75, 0.68, 0.48, 0.12);",
    "    glVertex3f(cos(s*TAU/32)*1.05, 0, sin(s*TAU/32)*1.05);",
    "  }",
    "  glEnd();",
    "  glEnable(GL_CULL_FACE);",
    "glPopMatrix();",
    "glColor3f(1, 0.9, 0.7);",
    "glRasterPos3f(px + 1.1, py + 0.4, pz);",
    "label(\"Saturn\");",
    "// Uranus (4.0 Earth radii) + a thin ring standing nearly on end:",
    "// the planet is tipped ~98 degrees, so its rings face the sun pole-on",
    "planet(6.8, 0.18, 5.2, 0.07, 0.34, 0.58, 0.82, 0.88);",
    "glPushMatrix();",
    "  glTranslatef(px, py, pz);",
    "  glRotatef(98, 0, 0, 1);",
    "  glDisable(GL_CULL_FACE);",
    "  glBegin(GL_TRIANGLE_STRIP);",
    "  for(s, 0, 33) {",
    "    glColor4f(0.72, 0.88, 0.92, 0.4);",
    "    glVertex3f(cos(s*TAU/32)*0.44, 0, sin(s*TAU/32)*0.44);",
    "    glColor4f(0.72, 0.88, 0.92, 0.1);",
    "    glVertex3f(cos(s*TAU/32)*0.58, 0, sin(s*TAU/32)*0.58);",
    "  }",
    "  glEnd();",
    "  glEnable(GL_CULL_FACE);",
    "glPopMatrix();",
    "glColor3f(0.75, 0.92, 0.95);",
    "glRasterPos3f(px + 0.6, py + 0.35, pz);",
    "label(\"Uranus\");",
    "// Neptune (3.9 Earth radii)",
    "planet(7.7, 0.13, 0.7, 0.14, 0.335, 0.28, 0.42, 0.9);",
    "glColor3f(0.55, 0.65, 1);",
    "glRasterPos3f(px + 0.42, py + 0.34, pz);",
    "label(\"Neptune\");",
    "// live readout: Earth's orbital phase, anchored in 3D below the system",
    "glColor3f(0.75, 0.8, 0.9);",
    "glRasterPos3f(-2.6, -5.6, 0);",
    "label(\"Earth phase = %f\", fmod(t*0.85 + 2.5, TAU));",
    "",
    "// faint orbit rings (unlit lines), one per planet at its inclination",
    "glDisable(GL_LIGHTING);",
    "glColor3f(0.22, 0.24, 0.34);",
    "glLineWidth(1.2);",
    "OrbitRings(1.4, 0.18);",
    "OrbitRings(2.05, 0.06);",
    "OrbitRings(2.7, 0.0);",
    "OrbitRings(3.35, 0.22);",
    "OrbitRings(4.5, 0.05);",
    "OrbitRings(5.8, 0.10);",
    "OrbitRings(6.8, 0.07);",
    "OrbitRings(7.7, 0.14);",
    NULL
};

/* Torus knot: a single closed (p, q) curve winding p times around the
 * torus axis and q times through the hole, drawn as one GL_LINE_LOOP.
 * Per-vertex color sweeps the hue around the curve and drifts with t, so
 * a rainbow band flows along the knot. Pure trig in one for-loop. */
static const char *const g_example_torus_knot[] = {
    "// @cfg poly_highlight = 0",
    "// @cfg vertex_labels = 0",
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -9.0f);",
    "glRotatef(25.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(0.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, 0.0f, 0.0f);",
    "static float n, p, q, ang, rr, x, y, z; // samples, winds, angle, ring radius, coords",
    "glClearColor(0.05, 0.05, 0.08, 1.0);",
    "glLineWidth(2.0);",
    "n = 400;   // samples around the closed curve",
    "p = 2;     // turns around the torus axis",
    "q = 3;     // turns through the torus hole",
    "glBegin(GL_LINE_LOOP);",
    "  for(i, 0, n) {",
    "    ang = TAU * i/n;",
    "    rr = 2.0 + cos(q*ang);          // distance from the axis",
    "    x = rr * cos(p*ang);",
    "    y = rr * sin(p*ang);",
    "    z = sin(q*ang);",
    "    glColor3f(0.5 + 0.5*sin(ang + t), 0.5 + 0.5*sin(ang + t + 2.0), 0.5 + 0.5*sin(ang + t + 4.0));",
    "    glVertex3f(x, y, z);",
    "  }",
    "glEnd();",
    NULL
};

static const char *const g_example_whale[] = {
    "// @cfg grid = GRID_THEME_OCEAN",
    "// @cfg axes = AXES_THEME_OFF",
    "// @cfg grid_extent = GRID_EXTENT_MID",
    "// @cfg light_theme = LIGHT_THEME_DEFAULT",
    "// @cfg normal_vectors = 0",
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// camera",
    "glTranslatef(0.0000f, 0.0000f, -6.5473f);",
    "glRotatef(20.6076f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(-114.3999f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.2893f, -0.0000f, -0.0242f);",
    "",
    "static float launchVelX, launchVelY, launchVelZ;",
    "static float currentVelY;",
    "static float particleLife, particleAge;",
    "static float dragDecay = 0.9;",
    "static float gravityY = -3.5;",
    "static float dragRate = 10;",
    "static float particleX, particleY, particleZ;",
    "static float floorY = 0;",
    "static float spawnDelay;",
    "static float emitDuration = 5.99568;",
    "static float fluke_ang, fin_ang;",
    "static float speed = 0.5;",
    "static float detail = 30;",
    "static float blowHoleX = 0.95, blowHoleY = 0.71, blowHoleZ;",
    "static float waterDroplets = 250; // @tune",
    "computeVerticalMotion(ageSeconds, launchY) {",
    "  // Velocity is linear in age: currentVelY = gravityY*ageSeconds + launchVelY.",
    "  // Position is its integral:",
    "  //   (gravityY/2)*ageSeconds^2 + launchVelY*ageSeconds + launchY",
    "  currentVelY = launchVelY + gravityY*ageSeconds;",
    "  particleY = launchY + gravityY/2 * ageSeconds * ageSeconds + launchVelY * ageSeconds;",
    "}",
    "",
    "computeLifespan(launchY) {",
    "  // Solve particleY(age) = floorY for age: how long the particle takes to fall",
    "  // from launchY to the floor. particleY is the projectile",
    "  //   (gravityY/2)*age^2 + launchVelY*age + (launchY - floorY) = 0",
    "  // a quadratic with a = gravityY/2, b = launchVelY, c = launchY - floorY, so",
    "  //   age = (-b - sqrt(b^2 - 4ac)) / 2a",
    "  // Substituting a = gravityY/2: 4ac = 2*gravityY*c and 2a = gravityY.",
    "  particleLife = (-launchVelY - sqrt(launchVelY*launchVelY - 2 * gravityY*(launchY - floorY))) / gravityY;",
    "}",
    "",
    "computeDriftX(ageSeconds, launchX) {",
    "  // Integral over [0, age] of the decaying horizontal velocity",
    "  //   velX(s) = launchVelX * dragDecay^(dragRate*s)",
    "  particleX = launchX + (launchVelX * pow(dragDecay, ageSeconds*dragRate) - launchVelX) / (dragRate*ln(dragDecay));",
    "}",
    "",
    "computeDriftZ(ageSeconds, launchZ) {",
    "  // Integral over [0, age] of the decaying horizontal velocity",
    "  //   velZ(s) = launchVelZ * dragDecay^(dragRate*s)",
    "  particleZ = launchZ + (launchVelZ * pow(dragDecay, ageSeconds*dragRate) - launchVelZ) / (dragRate*ln(dragDecay));",
    "}",
    "",
    "drawWhale(blowHoleX, blowHoleY, blowHoleZ) {",
    "  fluke_ang = sin(speed*t*TAU)* 30;",
    "  fin_ang = cos(speed*t*TAU)* 5;",
    "  detail = max(12, floor(detail));",
    "",
    "  // Shiny wet whale",
    "  glMaterialfv(GL_FRONT_AND_BACK, GL_SPECULAR, (GLfloat[]){0.2, 0.2, 0.2, 1});",
    "  glMaterialf(GL_FRONT_AND_BACK, GL_SHININESS, 100);",
    "",
    "  // Main body: elongated ellipsiod, dark blue-grey on top",
    "  glColor3f(0.24, 0.3, 0.4);",
    "",
    "  glPushMatrix();",
    "    glScalef(2, 0.85, 1.05);",
    "    glutSolidSphere(1, detail, detail);",
    "  glPopMatrix();",
    "",
    "  // Belly: lighter, sits just under the body so it shows the underside",
    "  glColor3f(0.72, 0.76, 0.78);",
    "  glPushMatrix();",
    "    glTranslatef(0.05, -0.42, 0);",
    "    glScalef(1.65, 0.45, 0.75);",
    "    glutSolidSphere(1, detail, detail);",
    "  glPopMatrix();",
    "",
    "  glColor3f(0.24, 0.3, 0.4);",
    "  glPushMatrix(); // begin tail",
    "    glTranslatef(-1.85, -0.2, 0);",
    "    glRotatef(fluke_ang/2, 0, 0, 1);",
    "",
    "    // Tail peduncle (narrow part before the flukes)",
    "    glPushMatrix();",
    "      glScalef(0.75, 0.3, 0.4);",
    "      glutSolidSphere(1, detail, detail);",
    "    glPopMatrix();",
    "",
    "    // Tail flukes -- two flat libes, animated with fluke_angle",
    "    glPushMatrix();",
    "      glTranslatef(-0.65, 0, 0);",
    "      glRotatef(fluke_ang, 0, 0, 1);",
    "      glPushMatrix();",
    "        glTranslatef(-0.1, 0, 0.55);",
    "        glRotatef(15, 0, 1, 0);",
    "        glScalef(0.35, 0.06, 0.65);",
    "        glutSolidSphere(1, detail, detail); // right fluke",
    "      glPopMatrix();",
    "      glPushMatrix();",
    "        glTranslatef(-0.1, 0, -0.55);",
    "        glRotatef(-15, 0, 1, 0);",
    "        glScalef(0.35, 0.06, 0.65);",
    "        glutSolidSphere(1, detail, detail); // left fluke",
    "      glPopMatrix();",
    "    glPopMatrix(); // end flukes",
    "  glPopMatrix(); // end tail",
    "",
    "  // Pectoral fins",
    "  glPushMatrix();",
    "    glRotatef(fin_ang, 0, 0, 1);",
    "    glRotatef(fin_ang/4, 0, 1, 0);",
    "",
    "    glPushMatrix();",
    "      glTranslatef(0.45, -0.25, 1);",
    "      glRotatef(25, 0, 1, 0);",
    "      glScalef(0.4, 0.08, 0.45);",
    "      glutSolidSphere(1, 14, 10); // right pectoral fin",
    "    glPopMatrix();",
    "",
    "    glPushMatrix();",
    "      glTranslatef(0.45, -0.25, -1);",
    "      glScalef(0.4, 0.08, 0.45);",
    "      glutSolidSphere(1, 14, 10); // left pectoral fin",
    "    glPopMatrix();",
    "  glPopMatrix(); // end fins",
    "",
    "  // Eyes",
    "  glDisable(GL_LIGHTING);",
    "  glColor3f(0.04, 0.04, 0.04);",
    "  glPushMatrix();",
    "    glTranslatef(1.45, 0.18, 0.63);",
    "    glutSolidSphere(0.07, 10, 8);",
    "    glTranslatef(0, 0, -1.26);",
    "    glutSolidSphere(0.07, 10, 8);",
    "  glPopMatrix();",
    "",
    "  // Blowhole",
    "  glColor3f(0.08, 0.08, 0.12);",
    "  glPushMatrix();",
    "    glTranslatef(blowHoleX, blowHoleY, blowHoleZ);",
    "    glScalef(0.15, 0.04, 0.1);",
    "    glutSolidSphere(1, 10, 8);",
    "  glPopMatrix();",
    "}",
    "",
    "glColor4f(0.25, 0.45, 0.85, 0.46);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE);",
    "glEnable(GL_DEPTH_TEST);",
    "glDepthFunc(GL_ALWAYS);",
    "glPointSize(10);",
    "",
    "if(t > 2*emitDuration) {",
    "  t = 0;",
    "}",
    "",
    "glBegin(GL_POINTS);",
    "  for(i, 0, waterDroplets) {",
    "    launchVelX = 3 * rand2(i,1);",
    "    launchVelY = 2 + 2 * rand(i, 2);",
    "    launchVelZ = 3 * rand2(i, 3);",
    "",
    "    computeLifespan(blowHoleY);",
    "    spawnDelay = 3 * rand(i,4);",
    "",
    "    if((t - spawnDelay) > 0 && ( t <= ceil(emitDuration/particleLife)*particleLife + spawnDelay)) {",
    "      particleAge = fmod(t - spawnDelay, particleLife);",
    "",
    "      computeDriftX(particleAge, blowHoleX);",
    "      computeVerticalMotion(particleAge, blowHoleY);",
    "      computeDriftZ(particleAge, blowHoleZ);",
    "",
    "      glVertex3f(particleX + 0.05, particleY, particleZ);",
    "    }",
    "  }",
    "glEnd();",
    "",
    "glDepthFunc(GL_LESS);",
    "",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "glDisable(GL_BLEND);",
    "",
    "glEnable(GL_LIGHT0);",
    "glEnable(GL_LIGHT1);",
    "",
    "glEnable(GL_LIGHTING);",
    "",
    "drawWhale(blowHoleX, blowHoleY, blowHoleZ);",
    NULL
};

static const char *const g_example_carousel[] = {
    "// @cfg grid = GRID_THEME_CLASSIC",
    "// @cfg axes = AXES_THEME_OFF",
    "// @cfg backdrop = RENDER3D_BACKDROP_CITY_AND_STARS",
    "// @cfg light_theme = LIGHT_THEME_DEFAULT",
    "// @cfg normal_vectors = 0",
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// camera",
    "glTranslatef(0.0000f, 0.0000f, -8.8000f);",
    "glRotatef(10.0000f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(24.0000f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0000f, -1.2000f, 0.0000f);",
    "",
    "static float spinRate = 0.06;",
    "static float seats = 8;",
    "static float bulbs = 28;",
    "static float bob, glow, sel;",
    "",
    "drawSeat(ang) {",
    "  glPushMatrix();",
    "    glRotatef(ang, 0, 1, 0);",
    "    glTranslatef(2, 0, 0);",
    "",
    "    // Brass pole, deck to canopy",
    "    glColor3f(0.72, 0.58, 0.28);",
    "    glPushMatrix();",
    "      glTranslatef(0, 1, 0);",
    "      glScalef(0.05, 2, 0.05);",
    "      glutSolidCube(1);",
    "    glPopMatrix();",
    "",
    "    // Teapot seat: bobs with a per-seat phase, faces the travel direction",
    "    bob = 0.2 * sin(t*TAU*0.7 + ang*PI/180);",
    "    sel = fmod(ang/45, 3);",
    "    if(sel < 0.5) {",
    "      glColor3f(0.85, 0.22, 0.25);",
    "    }",
    "    if(sel > 0.5 && sel < 1.5) {",
    "      glColor3f(0.2, 0.6, 0.62);",
    "    }",
    "    if(sel > 1.5) {",
    "      glColor3f(0.9, 0.7, 0.25);",
    "    }",
    "    glPushMatrix();",
    "      glTranslatef(0, 0.55 + bob, 0);",
    "      glRotatef(90, 0, 1, 0);",
    "      glutSolidTeapot(0.38);",
    "    glPopMatrix();",
    "  glPopMatrix();",
    "}",
    "",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_NORMALIZE);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_LIGHT0);",
    "glEnable(GL_LIGHT1);",
    "",
    "glPushMatrix();",
    "  glRotatef(t * spinRate * 360, 0, 1, 0);",
    "",
    "  // Deck: triangle-fan disc, rim swept by the bulb chase phase",
    "  // (i*TAU*4/bulbs ~= the bulbs' i*0.9 step, but closes the loop exactly)",
    "  glDisable(GL_LIGHTING);",
    "  glBegin(GL_TRIANGLE_FAN);",
    "    glColor3f(0.2, 0.12, 0.06);",
    "    glVertex3f(0, 0, 0);",
    "    for(i, 0, bulbs + 1) {",
    "      glow = 0.6 + 0.4 * sin(6*t + i*TAU*4/bulbs);",
    "      glColor3f(0.45, 0.07 + 0.31*glow, 0.16*glow);",
    "      glVertex3f(2.6*cos(i*TAU/bulbs), 0, 2.6*sin(i*TAU/bulbs));",
    "    }",
    "  glEnd();",
    "  glEnable(GL_LIGHTING);",
    "",
    "  // Center column",
    "  glColor3f(0.72, 0.58, 0.28);",
    "  glPushMatrix();",
    "    glTranslatef(0, 1, 0);",
    "    glScalef(0.16, 2, 0.16);",
    "    glutSolidCube(1);",
    "  glPopMatrix();",
    "",
    "  // Striped canopy: three stacked squashed spheres + gold finial",
    "  glColor3f(0.78, 0.16, 0.2);",
    "  glPushMatrix();",
    "    glTranslatef(0, 2, 0);",
    "    glScalef(2.9, 0.6, 2.9);",
    "    glutSolidSphere(1, 36, 18);",
    "  glPopMatrix();",
    "  glColor3f(0.92, 0.88, 0.8);",
    "  glPushMatrix();",
    "    glTranslatef(0, 2.22, 0);",
    "    glScalef(2.1, 0.5, 2.1);",
    "    glutSolidSphere(1, 32, 16);",
    "  glPopMatrix();",
    "  glColor3f(0.78, 0.16, 0.2);",
    "  glPushMatrix();",
    "    glTranslatef(0, 2.46, 0);",
    "    glScalef(1.3, 0.42, 1.3);",
    "    glutSolidSphere(1, 28, 14);",
    "  glPopMatrix();",
    "  glColor3f(0.95, 0.78, 0.3);",
    "  glPushMatrix();",
    "    glTranslatef(0, 2.95, 0);",
    "    glutSolidSphere(0.12, 16, 12);",
    "  glPopMatrix();",
    "",
    "  // Gold rim ring at the canopy edge -- mounts the bulb chase",
    "  glColor3f(0.72, 0.58, 0.28);",
    "  glPushMatrix();",
    "    glTranslatef(0, 1.75, 0);",
    "    glRotatef(90, 1, 0, 0);",
    "    glutSolidTorus(0.05, 2.7, 12, 48);",
    "  glPopMatrix();",
    "",
    "  for(i, 0, seats) {",
    "    drawSeat(i * 360 / seats);",
    "  }",
    "",
    "  // Fairground bulbs: additive points chasing around both rims",
    "  glDisable(GL_LIGHTING);",
    "  glEnable(GL_BLEND);",
    "  glBlendFunc(GL_SRC_ALPHA, GL_ONE);",
    "  glEnable(GL_POINT_SMOOTH);",
    "  glDepthMask(GL_FALSE);",
    "  glPointSize(26);",
    "  glBegin(GL_POINTS);",
    "  for(i, 0, bulbs) {",
    "    glow = 0.6 + 0.4 * sin(6*t - i*0.9);",
    "    glColor4f(1, 0.15 + 0.7*glow, 0.35*glow, glow);",
    "    glVertex3f(2.84*cos(i*TAU/bulbs), 1.78, 2.84*sin(i*TAU/bulbs));",
    "  }",
    "  glEnd();",
    "  glBegin(GL_POINTS);",
    "  for(i, 0, bulbs) {",
    "    glow = 0.6 + 0.4 * sin(6*t + i*0.9);",
    "    glColor4f(1, 0.15 + 0.7*glow, 0.35*glow, glow);",
    "    glVertex3f(2.66*cos(i*TAU/bulbs + 0.11), 0.06, 2.66*sin(i*TAU/bulbs + 0.11));",
    "  }",
    "  glEnd();",
    "  glDepthMask(GL_TRUE);",
    "glPopMatrix();",
    NULL
};

/* Ringed planet - hero showcase for the Star Chart grid + Nebula
 * backdrop trio: a lit banded gas giant (quad-strip sphere with
 * t-swirled latitude bands), two moons on tilted orbits, translucent
 * double rings drawn depth-read-only over everything, and a comet
 * sweeping an eccentric path with a fading line tail. The nebula's
 * GL_LIGHT4..6 rig tints the lit surfaces violet/teal so the model
 * sits inside the backdrop instead of on top of it. */
static const char *const g_example_ringed_planet[] = {
    "// @cfg axes = AXES_THEME_OFF",
    "// @cfg vertex_outlines = 0",
    "// @cfg vertex_points = 0",
    "// @cfg light_indicators = 0",
    "// @cfg grid = GRID_THEME_STARCHART",
    "// @cfg backdrop = RENDER3D_BACKDROP_NEBULA",
    "// camera",
    "glTranslatef(0.0f, 0.0f, -12.5f);",
    "glRotatef(16.0f, 1.0f, 0.0f, 0.0f);",
    "glRotatef(-30.0f, 0.0f, 1.0f, 0.0f);",
    "glTranslatef(0.0f, -1.2f, 0.0f);",
    "static float y, c, a;",
    "// ===== Ringed gas giant under nebula skies =====",
    "// NOTE: stays well under the 4096 flattened-command budget --",
    "// the sphere loop costs stacks*(slices + 1)*10 flat commands.",
    "glClearColor(0.04, 0.04, 0.1, 1.0);",
    "glEnable(GL_DEPTH_TEST);",
    "glEnable(GL_LIGHTING);",
    "glEnable(GL_LIGHT0);",
    "glEnable(GL_COLOR_MATERIAL);",
    "glEnable(GL_NORMALIZE);",
    "glShadeModel(GL_SMOOTH);",
    "",
    "// banded gas giant: quad strips over latitude, bands swirled by t",
    "planet(rad, stacks, slices) {",
    "  for(i, 0, stacks) {",
    "    glBegin(GL_QUAD_STRIP);",
    "    for(j, 0, slices + 1) {",
    "      y = sin(-PI/2 + PI*i/stacks);",
    "      c = 0.5 + 0.5*sin(9*y + 0.5*sin(3*j*TAU/slices + 0.6*t) + 0.4*t);",
    "      glColor3f(0.46 + 0.34*c, 0.30 + 0.16*c, 0.62 - 0.20*c);",
    "      glNormal3f(cos(-PI/2 + PI*i/stacks)*cos(j*TAU/slices), y, cos(-PI/2 + PI*i/stacks)*sin(j*TAU/slices));",
    "      glVertex3f(rad*cos(-PI/2 + PI*i/stacks)*cos(j*TAU/slices), rad*y, rad*cos(-PI/2 + PI*i/stacks)*sin(j*TAU/slices));",
    "      y = sin(-PI/2 + PI*(i + 1)/stacks);",
    "      c = 0.5 + 0.5*sin(9*y + 0.5*sin(3*j*TAU/slices + 0.6*t) + 0.4*t);",
    "      glColor3f(0.46 + 0.34*c, 0.30 + 0.16*c, 0.62 - 0.20*c);",
    "      glNormal3f(cos(-PI/2 + PI*(i + 1)/stacks)*cos(j*TAU/slices), y, cos(-PI/2 + PI*(i + 1)/stacks)*sin(j*TAU/slices));",
    "      glVertex3f(rad*cos(-PI/2 + PI*(i + 1)/stacks)*cos(j*TAU/slices), rad*y, rad*cos(-PI/2 + PI*(i + 1)/stacks)*sin(j*TAU/slices));",
    "    }",
    "    glEnd();",
    "  }",
    "}",
    "",
    "// moon on a tilted circular orbit; caller sets the color",
    "moon(orbit, rad, speed, tilt) {",
    "  glPushMatrix();",
    "  glRotatef(tilt, 0, 0, 1);",
    "  glRotatef(speed*t, 0, 1, 0);",
    "  glTranslatef(orbit, 0, 0);",
    "  glutSolidSphere(rad, 16, 12);",
    "  glPopMatrix();",
    "}",
    "",
    "// translucent ring band: bright inner lip fading outward",
    "ring(inner, outer, fade) {",
    "  glBegin(GL_QUAD_STRIP);",
    "  for(j, 0, 41) {",
    "    c = 0.75 + 0.25*sin(j*0.9);",
    "    glColor4f(0.70*c, 0.58*c, 0.88*c, fade);",
    "    glVertex3f(inner*cos(j*TAU/40), 0, inner*sin(j*TAU/40));",
    "    glColor4f(0.45*c, 0.50*c, 0.85*c, 0.25*fade);",
    "    glVertex3f(outer*cos(j*TAU/40), 0, outer*sin(j*TAU/40));",
    "  }",
    "  glEnd();",
    "}",
    "",
    "glPushMatrix();",
    "glTranslatef(0, 1.7, 0);",
    "",
    "glPushMatrix();",
    "glRotatef(-6*t, 0, 1, 0);",
    "planet(1.55, 18, 18);",
    "glPopMatrix();",
    "",
    "glColor3f(0.78, 0.72, 0.64);",
    "moon(3.9, 0.22, 34, 9);",
    "glColor3f(0.55, 0.66, 0.80);",
    "moon(5.1, 0.16, -21, -14);",
    "",
    "// translucent passes last: rings over the planet, then the comet",
    "glDisable(GL_LIGHTING);",
    "glEnable(GL_BLEND);",
    "glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);",
    "glDepthMask(GL_FALSE);",
    "glPushMatrix();",
    "glRotatef(26, 1, 0, 0.3);",
    "ring(1.95, 2.45, 0.40);",
    "ring(2.55, 3.05, 0.20);",
    "glPopMatrix();",
    "",
    "// comet: bright head + tail fading along its eccentric orbit",
    "glBegin(GL_LINE_STRIP);",
    "for(i, 0, 30) {",
    "  a = 0.7*t - 0.06*i;",
    "  glColor4f(0.55, 0.85, 1.0, 0.6*(1 - i/30));",
    "  glVertex3f(5.6*cos(a), 1.1*sin(2*a), 4.2*sin(a));",
    "}",
    "glEnd();",
    "glPointSize(6);",
    "glBegin(GL_POINTS);",
    "glColor4f(0.85, 0.97, 1.0, 0.95);",
    "glVertex3f(5.6*cos(0.7*t), 1.1*sin(1.4*t), 4.2*sin(0.7*t));",
    "glEnd();",
    "",
    "// leave shared GL state the way we found it",
    "glDepthMask(GL_TRUE);",
    "glDisable(GL_BLEND);",
    "glPopMatrix();",
    NULL
};

typedef unsigned int ReplExampleTagMask;

typedef struct {
    const char *name;
    const char *const *lines;
    ReplExampleTagMask tags;
    /* Optional in-flyout section subheading. Free-form display string
     * (e.g. "Basics", "Functions") — the Scene menu groups consecutive
     * examples sharing the same subheading under a chrome `### subheading`
     * header. NULL = no header. Convention enforced by
     * test_example_subheading_metadata: per tag, each non-NULL subheading
     * must appear in a single contiguous run — interleaving causes
     * duplicate headers. */
    const char *subheading;
} ReplExampleEntry;

/* REPL_EXAMPLE_TAG_ALL is a synthetic tag: every example is a member.
 * It is not listed in any g_example_entries[] mask literal; instead
 * repl_example_tag_mask() ORs its bit into every example's mask, so the
 * whole tag query API (has_tag / count_for_tag / index_for_tag /
 * visible_tag_*) — and therefore the Scene menu's "All" group and the
 * F12 cycle — pick it up with no per-entry bookkeeping. Kept at index 0
 * so "All" sorts first under "### EXAMPLES". Enum lives in examples.h. */

#define EXAMPLE_TAG_BIT(tag) (1u << (tag))
#define EXAMPLE_TAG_ALL      EXAMPLE_TAG_BIT(REPL_EXAMPLE_TAG_ALL)
#define EXAMPLE_TAG_2D       EXAMPLE_TAG_BIT(REPL_EXAMPLE_TAG_2D)
#define EXAMPLE_TAG_3D       EXAMPLE_TAG_BIT(REPL_EXAMPLE_TAG_3D)
#define EXAMPLE_TAG_POLYGONS EXAMPLE_TAG_BIT(REPL_EXAMPLE_TAG_POLYGONS)
#define EXAMPLE_TAG_LINES    EXAMPLE_TAG_BIT(REPL_EXAMPLE_TAG_LINES)

static const char *const g_example_tag_labels[] = {
    "All",
    "2D",
    "3D",
    "Polygons",
    "Lines",
};
/* Must stay 1:1 with the REPL_EXAMPLE_TAG_* enum: repl_example_tag_count()
 * returns REPL_EXAMPLE_TAG_COUNT but repl_example_tag_label() indexes this
 * table, so any drift is an out-of-bounds read. */
STATIC_ASSERT((int)(sizeof(g_example_tag_labels) /
                    sizeof(g_example_tag_labels[0])) == REPL_EXAMPLE_TAG_COUNT,
              "g_example_tag_labels[] out of sync with REPL_EXAMPLE_TAG_COUNT");

/* Catalog order matters: the Scene menu groups consecutive same-subheading
 * entries into one `### subheading` header per per-tag flyout, so each
 * subheading must run contiguously within every tag it surfaces under.
 * test_example_subheading_metadata enforces this — see the per-tag walk
 * notes in g_example_tag_labels above. Lit cube intentionally stays first
 * (F12's default scene). */
static const ReplExampleEntry g_example_entries[] = {
    { "Lit cube", g_example_cube,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Basics" },
    { "Animated ring (for + t)", g_example_ring,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_LINES,
      "Basics" },
    { "Conditional colors (if + t)", g_example_cond,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Basics" },
    { "Transform stress (translate/rotate/scale guides)", g_example_xform_stress,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Basics" },

    { "Parametric torus (nested for)", g_example_torus,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Curves & surfaces" },
    { "Animated wave surface (analytic normals)", g_example_waves,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Curves & surfaces" },
    { "Torus knot (animated)", g_example_torus_knot,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_LINES,
      "Curves & surfaces" },

    { "2D assignment sketch (vars only)", g_example_assign_2d,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Curves & surfaces" },
    { "Function demo (named func)", g_example_func,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Functions" },
    { "Function polygons (args + for)", g_example_func_loop,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_POLYGONS,
      "Functions" },
    { "Function branching (args + if)", g_example_func_if,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_POLYGONS,
      "Functions" },
    { "Recursive triangle tree (func + recursion)", g_example_func_recurse,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Functions" },
    { "Animated spirograph curve", g_example_spirograph_curve,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Parametric curves" },
    { "Traveling ripple ring", g_example_traveling_ripple_ring,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Parametric curves" },
    { "Bezier curve with guides", g_example_bezier,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Parametric curves" },
    { "Scratch arrays (de Casteljau curve)", g_example_scratch_casteljau,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Parametric curves" },
    { "Annotated orbit plot (labels)", g_example_annotated_orbit_plot,
      EXAMPLE_TAG_2D | EXAMPLE_TAG_LINES,
      "Parametric curves" },

    { "GLU tessellator (concave arrow)", g_example_tess,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Tessellation" },
    { "GLU tessellator (concave arrow cutout)", g_example_tess_cutout,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Tessellation" },

    { "Glow sprites (blend + point attenuation)", g_example_glow_particles,
      EXAMPLE_TAG_3D,
      "Particles" },
    { "Snowfall demo (550 particles)", g_example_snowfall,
      EXAMPLE_TAG_3D,
      "Particles" },

    { "Swaying grass field (rand + t)", g_example_grass_field,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Showcase" },
    { "Jellyfish (glDepthMask translucency)", g_example_jellyfish,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS | EXAMPLE_TAG_LINES,
      "Showcase" },
    { "Dusk lighthouse atoll (stress test)", g_example_stress,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS | EXAMPLE_TAG_LINES,
      "Showcase" },
    { "Orrery (labels track 3D orbits)", g_example_orrery,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_LINES,
      "Showcase" },
    { "Whale (particle system + lit model)", g_example_whale,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Showcase" },
    { "Teapot carousel (transform stacks + glow points)", g_example_carousel,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS,
      "Showcase" },
    { "Ringed planet (nebula skies)", g_example_ringed_planet,
      EXAMPLE_TAG_3D | EXAMPLE_TAG_POLYGONS | EXAMPLE_TAG_LINES,
      "Showcase" },
};

static int example_catalog_entry_count(void) {
    return repl_example_count();
}

static int example_catalog_tag_count(void) {
    return REPL_EXAMPLE_TAG_COUNT;
}

static unsigned int example_catalog_tag_bit(int tag_idx) {
    return repl_example_tag_bit(tag_idx);
}

static const ReplCatalogTagOps g_example_tag_ops = {
    example_catalog_entry_count,
    example_catalog_tag_count,
    g_example_tag_labels,
    repl_example_tag_mask,
    example_catalog_tag_bit,
};

int repl_example_count(void) {
    return (int)(sizeof(g_example_entries) / sizeof(g_example_entries[0]));
}

const char *repl_example_name(int idx) {
    if (idx < 0 || idx >= repl_example_count())
        return NULL;
    return g_example_entries[idx].name;
}

const char *const *repl_example_lines(int idx) {
    if (idx < 0 || idx >= repl_example_count())
        return NULL;
    return g_example_entries[idx].lines;
}

int repl_example_tag_count(void) {
    return REPL_EXAMPLE_TAG_COUNT;
}

unsigned int repl_example_tag_mask(int example_idx) {
    if (example_idx < 0 || example_idx >= repl_example_count())
        return 0u;
    /* Fold in the synthetic "All" membership so every tag query derives
     * it uniformly; entry literals stay free of an explicit ALL bit. */
    return g_example_entries[example_idx].tags | EXAMPLE_TAG_ALL;
}

REPL_DEFINE_CATALOG_TAG_WRAPPERS(example, &g_example_tag_ops)

const char *repl_example_subheading(int example_idx) {
    if (example_idx < 0 || example_idx >= repl_example_count())
        return NULL;
    return g_example_entries[example_idx].subheading;
}
