#!/usr/bin/env python3
"""Generate the soft pastel perspective-cube icon SVG(s).

A unit cube is run through a real pinhole camera (yaw 45 / pitch 30, looking
slightly down) so its vertical edges genuinely converge -- true perspective,
not a parallel projection. Palette, shading and thin dark edges match the
hand-tuned look; only the projection is computed.

Usage:
    python3 packaging/macos/gen_soft_cube.py [DIST [OUTFILE]]

    DIST     camera distance. Smaller = stronger perspective (more taper).
             8 = subtle (matches the reference); 5.5 = strong. Default 8.
    OUTFILE  basename written under packaging/macos/. Default gl-repl-soft-cube.svg.

Shipped SVGs:
    make icon-cube         -> gl-repl-soft-cube.svg        (DIST 8, subtle; used by `make app`)
    make icon-cube-strong  -> gl-repl-soft-cube-strong.svg (DIST 5.5, strong)
"""
import math, os, sys

YAW, PITCH, FOV, PAD = 45.0, 30.0, 42.0, 150
EDGE_W  = 7.0          # cube outline width (pure black)
DIST    = float(sys.argv[1]) if len(sys.argv) > 1 else 8.0
OUTNAME = sys.argv[2] if len(sys.argv) > 2 else "gl-repl-soft-cube.svg"

cy, sy = math.cos(math.radians(YAW)), math.sin(math.radians(YAW))
cp, sp = math.cos(math.radians(PITCH)), math.sin(math.radians(PITCH))
f = 1.0 / math.tan(math.radians(FOV) / 2.0)

corners = {(ix, iy, iz): (ix, iy, iz) for ix in (-1, 1) for iy in (-1, 1) for iz in (-1, 1)}

def project(p):
    x, y, z = p
    x1, z1, y1 = x*cy + z*sy, -x*sy + z*cy, y
    y2, z2, x2 = y1*cp - z1*sp, y1*sp + z1*cp, x1
    zc = z2 - DIST
    return (f*x2/(-zc), f*y2/(-zc), z2)

proj = {k: project(v) for k, v in corners.items()}
us = [p[0] for p in proj.values()]; vs = [p[1] for p in proj.values()]
umin, umax, vmin, vmax = min(us), max(us), min(vs), max(vs)
scale = (1024 - 2*PAD) / max(umax-umin, vmax-vmin)

def to_screen(p):
    u, v, _ = p
    sx = PAD + (u-umin)*scale + (1024 - 2*PAD - (umax-umin)*scale)/2
    sy_ = PAD + (vmax-v)*scale + (1024 - 2*PAD - (vmax-vmin)*scale)/2
    return (round(sx, 1), round(sy_, 1))

S = {k: to_screen(p) for k, p in proj.items()}

by_depth = sorted(corners, key=lambda k: proj[k][2], reverse=True)
n0 = by_depth[0]
F, Fb = (n0[0], 1, n0[2]), (n0[0], -1, n0[2])
top = [k for k in corners if k[1] == 1]
B = max(top, key=lambda k: -S[k][1])
L = min(top, key=lambda k: S[k][0])
R = max(top, key=lambda k: S[k][0])
Lb, Rb = (L[0], -1, L[2]), (R[0], -1, R[2])

def pt(k): return f"{S[k][0]},{S[k][1]}"
Bx,By = S[B]; Fx,Fy = S[F]; Lx,Ly = S[L]; Rx,Ry = S[R]; Fbx,Fby = S[Fb]
midY = round((Ly + Fby)/2, 1)
# warm light pools in the upper-left (top face front-left + top of left face)
warm_cx = round((Lx + Fx) / 2, 1)
warm_cy = round((Ly + Fy) / 2 - 30, 1)
warm_r  = round(0.62 * (Fby - By), 1)

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024" role="img" aria-label="gl-repl">
  <!-- Soft pastel cube in true perspective (yaw {YAW:.0f} / pitch {PITCH:.0f}, dist {DIST}).
       Generated by gen_soft_cube.py; vertical edges converge. -->
  <defs>
    <radialGradient id="bg" cx="0.5" cy="0.44" r="0.78">
      <stop offset="0"   stop-color="#8d8d91" />
      <stop offset="0.6" stop-color="#6b6b70" />
      <stop offset="1"   stop-color="#4d4d52" />
    </radialGradient>
    <linearGradient id="gtop" gradientUnits="userSpaceOnUse" x1="{Bx}" y1="{By}" x2="{Fx}" y2="{Fy}">
      <stop offset="0" stop-color="#dadcef" />
      <stop offset="1" stop-color="#d1d4ec" />
    </linearGradient>
    <linearGradient id="gleft" gradientUnits="userSpaceOnUse" x1="{Lx}" y1="{midY}" x2="{Fx}" y2="{midY}">
      <stop offset="0" stop-color="#c8cce6" />
      <stop offset="1" stop-color="#d3d6ed" />
    </linearGradient>
    <linearGradient id="gright" gradientUnits="userSpaceOnUse" x1="{Rx}" y1="{midY}" x2="{Fx}" y2="{midY}">
      <stop offset="0" stop-color="#cacee8" />
      <stop offset="1" stop-color="#d4d7ee" />
    </linearGradient>
    <radialGradient id="warm" gradientUnits="userSpaceOnUse" cx="{warm_cx}" cy="{warm_cy}" r="{warm_r}">
      <stop offset="0"   stop-color="#f4cfc9" stop-opacity="0.9" />
      <stop offset="0.5" stop-color="#eecccf" stop-opacity="0.36" />
      <stop offset="1"   stop-color="#eecccf" stop-opacity="0" />
    </radialGradient>
    <clipPath id="round"><rect x="0" y="0" width="1024" height="1024" rx="229" ry="229" /></clipPath>
    <clipPath id="cube"><polygon points="{pt(B)} {pt(R)} {pt(Rb)} {pt(Fb)} {pt(Lb)} {pt(L)}" /></clipPath>
  </defs>

  <rect x="0" y="0" width="1024" height="1024" rx="229" ry="229" fill="url(#bg)" />

  <g clip-path="url(#round)">
    <polygon points="{pt(L)} {pt(B)} {pt(R)} {pt(F)}" fill="url(#gtop)" />
    <polygon points="{pt(L)} {pt(F)} {pt(Fb)} {pt(Lb)}" fill="url(#gleft)" />
    <polygon points="{pt(F)} {pt(R)} {pt(Rb)} {pt(Fb)}" fill="url(#gright)" />
    <g clip-path="url(#cube)">
      <rect x="0" y="0" width="1024" height="1024" fill="url(#warm)" />
    </g>
    <g fill="none" stroke="#000000" stroke-width="{EDGE_W}" stroke-linejoin="round" stroke-linecap="round">
      <polyline points="{pt(B)} {pt(R)} {pt(Rb)} {pt(Fb)} {pt(Lb)} {pt(L)} {pt(B)}" />
      <polyline points="{pt(L)} {pt(F)} {pt(R)}" />
      <polyline points="{pt(F)} {pt(Fb)}" />
    </g>
  </g>
</svg>
'''
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), OUTNAME)
with open(out, "w") as fh:
    fh.write(svg)
print(f"wrote {out}  dist={DIST}")
