#!/usr/bin/env python3
"""Generate packaging/macos/gl-repl-retro-A.svg.

The icon is a garish early-90s WordArt-style "gl-repl": chrome letters
extruded in *perspective* toward a vanishing point up in the sunset, over a
neon synthwave grid that converges on the same point. The extrusion is a
stack of <use> copies of the word, each scaled toward the vanishing point
and tinted darker with depth -- tedious to hand-author, so this script emits
it from three knobs.

Usage:
    python3 packaging/macos/gen_retro_a.py [VPy [TY [SHRINK]]]

    VPy     vanishing-point height (smaller = farther up = MORE extrusion
            body on screen; larger/closer to TY = less). Default 370.
    TY      front-face baseline y. Default 624.
    SHRINK  how small the deepest layer gets (0..1). Default 0.52.

Re-run after editing to refresh the SVG, then `make app` to rebake the
.icns / app bundle. The emitted SVG is the source of truth committed to
the repo; this script just makes it reproducible.
"""
import os
import sys

# --- tunable defaults (match the committed gl-repl-retro-A.svg) -------------
VPx      = 512           # vanishing point x (= canvas center, keeps it symmetric)
VPy      = 370           # vanishing point y (the grid converges here too)
TY       = 624           # front-face baseline
N        = 26            # number of extrusion layers
SHRINK   = 0.52          # deepest layer scales to (1 - SHRINK)
DEEP     = "#0a0118"     # extrusion color at the vanishing point
NEAR     = "#7a1fb0"     # extrusion color just behind the face

# positional overrides: VPy TY SHRINK
if len(sys.argv) > 1: VPy = float(sys.argv[1])
if len(sys.argv) > 2: TY = float(sys.argv[2])
if len(sys.argv) > 3: SHRINK = float(sys.argv[3])


def interp(a, b, t):
    a = a.lstrip('#'); b = b.lstrip('#')
    ar, ag, ab = int(a[0:2], 16), int(a[2:4], 16), int(a[4:6], 16)
    br, bg, bb = int(b[0:2], 16), int(b[2:4], 16), int(b[4:6], 16)
    r = round(ar + (br - ar) * t); g = round(ag + (bg - ag) * t); bl = round(ab + (bb - ab) * t)
    return f"#{r:02x}{g:02x}{bl:02x}"


layers = []
for i in range(N, 0, -1):            # deepest (smallest) drawn first
    t = i / N
    s = round(1 - t * SHRINK, 4)
    col = interp(NEAR, DEEP, t)
    tr = f"translate({VPx} {VPy}) scale({s}) translate({-VPx} {-VPy}) translate(0 {TY})"
    layers.append(f'      <use href="#word" transform="{tr}" fill="{col}" />')
ext = "\n".join(layers)

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024" role="img" aria-label="gl-repl">
  <!-- Garish early-90s 3D-WordArt icon: chrome "gl-repl" extruded in perspective
       toward the grid's vanishing point. Generated by gen_retro_a.py.
       gl-repl.svg keeps the cube. -->
  <defs>
    <linearGradient id="rbg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0"   stop-color="#ff2db8" />
      <stop offset="0.5" stop-color="#6a1ea8" />
      <stop offset="1"   stop-color="#0a0626" />
    </linearGradient>
    <radialGradient id="rsun" cx="0.5" cy="0.40" r="0.6">
      <stop offset="0"   stop-color="#ffe14d" stop-opacity="0.95" />
      <stop offset="0.5" stop-color="#ff6a3d" stop-opacity="0.5" />
      <stop offset="1"   stop-color="#ff6a3d" stop-opacity="0" />
    </radialGradient>
    <linearGradient id="face" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffffff"/><stop offset="0.40" stop-color="#bfefff"/>
      <stop offset="0.50" stop-color="#2a86d8"/><stop offset="0.52" stop-color="#0b2f6b"/>
      <stop offset="0.88" stop-color="#79d2ff"/><stop offset="1" stop-color="#ffffff"/>
    </linearGradient>
    <linearGradient id="grid" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#00e5ff" stop-opacity="0" />
      <stop offset="1" stop-color="#00e5ff" stop-opacity="0.9" />
    </linearGradient>
    <filter id="rglow" x="-25%" y="-25%" width="150%" height="150%">
      <feGaussianBlur stdDeviation="6" result="b" />
      <feMerge><feMergeNode in="b" /><feMergeNode in="SourceGraphic" /></feMerge>
    </filter>
    <g id="word">
      <text x="512" y="0" text-anchor="middle"
            font-family="Futura, 'Helvetica Neue', Helvetica, sans-serif"
            font-weight="700" font-size="244" letter-spacing="-8">gl-repl</text>
    </g>
    <clipPath id="round"><rect x="0" y="0" width="1024" height="1024" rx="229" ry="229" /></clipPath>
  </defs>

  <rect x="0" y="0" width="1024" height="1024" rx="229" ry="229" fill="url(#rbg)" />
  <rect x="0" y="0" width="1024" height="1024" rx="229" ry="229" fill="url(#rsun)" />

  <g clip-path="url(#round)" stroke="url(#grid)" stroke-width="3" opacity="0.85">
    <line x1="0" y1="730" x2="1024" y2="730" /><line x1="0" y1="772" x2="1024" y2="772" />
    <line x1="0" y1="826" x2="1024" y2="826" /><line x1="0" y1="892" x2="1024" y2="892" />
    <line x1="0" y1="970" x2="1024" y2="970" />
    <line x1="512" y1="715" x2="-260" y2="1024" /><line x1="512" y1="715" x2="40" y2="1024" />
    <line x1="512" y1="715" x2="250" y2="1024" /><line x1="512" y1="715" x2="410" y2="1024" />
    <line x1="512" y1="715" x2="512" y2="1024" /><line x1="512" y1="715" x2="614" y2="1024" />
    <line x1="512" y1="715" x2="774" y2="1024" /><line x1="512" y1="715" x2="984" y2="1024" />
    <line x1="512" y1="715" x2="1284" y2="1024" />
  </g>

  <g filter="url(#rglow)">
{ext}
    <use href="#word" transform="translate(0 {TY})" fill="none" stroke="#0a0118" stroke-width="11" stroke-linejoin="round" />
    <use href="#word" transform="translate(0 {TY})" fill="url(#face)" stroke="#16264d" stroke-width="2.5" stroke-linejoin="round" />
  </g>
</svg>
'''

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "gl-repl-retro-A.svg")
with open(out, "w") as f:
    f.write(svg)
print(f"wrote {out}  VP=(512,{VPy}) TY={TY} SHRINK={SHRINK}")
