#!/usr/bin/env python3
"""Generate the frozen benchmark scene corpus as C data."""

from __future__ import annotations

import argparse
import configparser
from pathlib import Path


def c_string(text: str) -> str:
    out = ['"']
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 32 or ord(ch) > 126:
            out.append("\\x%02x" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def read_entries(catalog: Path) -> list[tuple[str, str, list[str]]]:
    parser = configparser.ConfigParser(interpolation=None, strict=True)
    parser.optionxform = str
    with catalog.open("r", encoding="utf-8") as stream:
        parser.read_file(stream)

    entries = []
    for section in parser.sections():
        name = parser[section]["name"].strip()
        rel_file = parser[section]["file"].strip()
        if not rel_file.endswith(".glr"):
            raise ValueError(f"[{section}] benchmark corpus only supports .glr scenes")
        scene = catalog.parent / rel_file
        if not scene.is_file():
            raise ValueError(f"[{section}] missing scene: {rel_file}")
        entries.append((section, name, scene.read_text(encoding="utf-8").splitlines()))
    if not entries:
        raise ValueError("benchmark catalog is empty")
    return entries


def render(entries: list[tuple[str, str, list[str]]]) -> str:
    out = ["/* Generated by scripts/gen_bench_examples.py. Do not edit. */", ""]
    for idx, (section, _name, lines) in enumerate(entries):
        symbol = f"g_bench_scene_{idx:02d}"
        out.append(f"/* [{section}] */")
        out.append(f"static const char *const {symbol}[] = {{")
        out.extend(f"    {c_string(line)}," for line in lines)
        out.extend(["    NULL", "};", ""])

    out.append("const BenchExample g_bench_examples[] = {")
    for idx, (_section, name, _lines) in enumerate(entries):
        out.append(f"    {{{c_string(name)}, g_bench_scene_{idx:02d}}},")
    out.extend([
        "};",
        "",
        "const int g_bench_example_count =",
        "    (int)(sizeof(g_bench_examples) / sizeof(g_bench_examples[0]));",
        "",
    ])
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    try:
        output = render(read_entries(args.catalog))
    except (OSError, KeyError, configparser.Error, ValueError) as exc:
        parser.error(str(exc))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(output, encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
